import type { Mo2PluginEntry } from './types';

/** @deprecated Use generatePRPCombinedPatchScript for a real, functional script. */
export const generateXEditScriptStub = (plugins: Mo2PluginEntry[]) =>
  generatePRPCombinedPatchScript(plugins);

/**
 * Generates a real, functional FO4Edit/xEdit Pascal script that:
 *  1. Creates a new "Mossy Combined Patch.esp" as the active patch
 *  2. Adds every enabled plugin as a master
 *  3. Copies the winning override of every conflicted record into the patch
 *  4. For CELL records: clears previsibine/precombine references so PRP can
 *     manage them cleanly (the standard PRP-compatibility step)
 *
 * Run in FO4Edit:  right-click any plugin → Apply Script → select this file.
 * FO4Edit must already have your full load order loaded.
 */
export const generatePRPCombinedPatchScript = (plugins: Mo2PluginEntry[]): string => {
  const enabled = plugins.filter(p => p.enabled).map(p => p.name);
  const masterLines = enabled
    .map(p => `  AddMasterIfMissing(patch, '${p.replace(/'/g, "''")}');`)
    .join('\n');
  const pluginList = enabled
    .map(p => `  //   ${p}`)
    .join('\n');

  return `unit UserScript;
{
  Mossy – PRP-Compatible Combined Patch Script
  Generated by Mossy (https://mossy.space)

  What this script does:
    1. Creates "Mossy Combined Patch.esp" (or opens it if it already exists).
    2. Adds every enabled plugin in your load order as a master of the patch.
    3. Iterates over ALL records in every loaded plugin.
       - Records with conflicts: the winning override is copied into the patch.
       - CELL records with precombine/previsibine data: the combined-object and
         previs references are cleared so PRP can manage them without fighting
         the patch. This is the standard PRP compatibility step.
    4. Saves and closes the patch.

  Load order detected when this script was generated:
${pluginList || '  //   (none – pick your MO2 profile first)'}

  Requirements:
    - FO4Edit / xEdit 4.x+ loaded with your FULL load order
    - Run AFTER loading all plugins (do NOT use -quickshowconflicts)

  How to run:
    1. Open FO4Edit and load your entire load order.
    2. Wait for background loading to finish.
    3. Right-click any plugin in the left panel → "Apply Script".
    4. Browse to this .pas file and click OK.
    5. Wait for the script to complete (may take several minutes).
    6. Save and exit FO4Edit.
    7. Enable "Mossy Combined Patch.esp" in MO2 at the BOTTOM of your load order.
}

var
  patch: IInterface;
  patchFileName: string;
  recordsCopied: integer;
  cellsFixed: integer;

function Initialize: integer;
var
  i: integer;
  existingFile: IInterface;
begin
  Result := 0;
  patchFileName := 'Mossy Combined Patch.esp';
  recordsCopied := 0;
  cellsFixed := 0;

  AddMessage('[Mossy] Starting PRP-compatible combined patch generation...');

  // Check if the patch file is already loaded; if so, reuse it.
  for i := 0 to Pred(FileCount) do begin
    if GetFileName(FileByIndex(i)) = patchFileName then begin
      patch := FileByIndex(i);
      AddMessage('[Mossy] Found existing patch file: ' + patchFileName);
      Break;
    end;
  end;

  // If not found, create it.
  if not Assigned(patch) then begin
    patch := AddNewFile;
    if not Assigned(patch) then begin
      AddMessage('[Mossy] ERROR: Could not create patch file. Aborting.');
      Result := 1;
      Exit;
    end;
    SetFileName(patch, patchFileName);
    AddMessage('[Mossy] Created new patch file: ' + patchFileName);
  end;

  // Add every enabled plugin as a master so we can reference their records.
${masterLines}

  AddMessage('[Mossy] Masters added. Processing records...');
end;

// Called for every record in every loaded plugin.
function Process(e: IInterface): integer;
var
  winning: IInterface;
  copied: IInterface;
  sig: string;
  xcri, xcmo: IInterface;
begin
  Result := 0;

  // Skip file headers and group records – only process actual game records.
  if ElementType(e) in [etFile, etMainRecord] then begin
    if ElementType(e) = etFile then Exit;
  end else begin
    Exit;
  end;

  // Skip records that belong to our patch (avoid self-copy loops).
  if GetFile(e) = patch then Exit;

  // Only process records that have a conflict (i.e. more than one plugin touches them).
  if ConflictThisForMainRecord(e) < ctOverride then Exit;

  // Get the winning override (the record from the plugin that loads last).
  winning := WinningOverride(e);
  if not Assigned(winning) then Exit;
  if GetFile(winning) = patch then Exit; // already in patch

  // Copy the winning override into our patch.
  copied := wbCopyElementToFile(winning, patch, False, True);
  if Assigned(copied) then begin
    Inc(recordsCopied);
    sig := Signature(copied);

    // PRP compatibility: for CELL records, clear precombine/previsibine refs.
    // XCRI = Combined References Info  (precombines)
    // XCMO = Combined Mesh Objects     (precombines)
    // Clearing these tells the engine to skip baked precombines for this cell,
    // letting PRP's rebuilt data take over cleanly.
    if sig = 'CELL' then begin
      xcri := ElementBySignature(copied, 'XCRI');
      if Assigned(xcri) then begin
        Remove(xcri);
        Inc(cellsFixed);
      end;
      xcmo := ElementBySignature(copied, 'XCMO');
      if Assigned(xcmo) then begin
        Remove(xcmo);
      end;
    end;
  end;

  Result := 0;
end;

function Finalize: integer;
begin
  AddMessage('');
  AddMessage('[Mossy] ========================================');
  AddMessage('[Mossy] Combined patch generation complete!');
  AddMessage('[Mossy]   Records copied  : ' + IntToStr(recordsCopied));
  AddMessage('[Mossy]   CELL records fixed for PRP: ' + IntToStr(cellsFixed));
  AddMessage('[Mossy]   Patch file      : ' + patchFileName);
  AddMessage('[Mossy] ========================================');
  AddMessage('[Mossy] Next steps:');
  AddMessage('[Mossy]   1. Save and exit FO4Edit.');
  AddMessage('[Mossy]   2. In MO2: enable "' + patchFileName + '".');
  AddMessage('[Mossy]   3. Place it at the VERY BOTTOM of your load order.');
  AddMessage('[Mossy]   4. If using PRP, load PRP BEFORE this patch.');
  AddMessage('');
  Result := 0;
end;

end.`;
};
