import React, { useState, useCallback } from 'react';
import {
  User, Brain, Sword, Heart, MessageSquare, Download,
  Zap, Shield, ChevronDown, ChevronRight, Sliders, Star,
  Code, Play, RotateCcw, Plus, Trash2, Save
} from 'lucide-react';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

interface PersonalityTrait {
  label: string;
  key: string;
  value: number;
  description: string;
}

interface DialogueLine {
  id: string;
  condition: string;
  line: string;
  voiceType: string;
}

interface CombatBehavior {
  style: 'aggressive' | 'balanced' | 'defensive' | 'sniper' | 'stealth';
  retreatHealth: number;
  flankingEnabled: boolean;
  coverUsage: 'always' | 'sometimes' | 'never';
  meleeRange: number;
  grenadeUsage: boolean;
}

interface CompanionProfile {
  name: string;
  race: string;
  faction: string;
  voiceType: string;
  personality: PersonalityTrait[];
  combat: CombatBehavior;
  dialogue: DialogueLine[];
  affinityThresholds: { like: number; dislike: number; loathe: number; idolize: number };
}

// ─────────────────────────────────────────────────────────────────────────────
// Defaults
// ─────────────────────────────────────────────────────────────────────────────

const DEFAULT_PERSONALITY: PersonalityTrait[] = [
  { label: 'Aggression',   key: 'aggression',   value: 30, description: 'Willingness to initiate combat' },
  { label: 'Confidence',   key: 'confidence',   value: 70, description: 'Fearlessness under threat' },
  { label: 'Energy',       key: 'energy',       value: 60, description: 'Activity level and responsiveness' },
  { label: 'Morality',     key: 'morality',     value: 50, description: 'Good/evil alignment' },
  { label: 'Mood',         key: 'mood',         value: 65, description: 'Default emotional disposition' },
  { label: 'Assistance',   key: 'assistance',   value: 80, description: 'Eagerness to help the player' },
];

const DEFAULT_COMBAT: CombatBehavior = {
  style: 'balanced',
  retreatHealth: 20,
  flankingEnabled: true,
  coverUsage: 'sometimes',
  meleeRange: 150,
  grenadeUsage: true,
};

const DEFAULT_PROFILE: CompanionProfile = {
  name: 'Axiom',
  race: 'HumanRace',
  faction: 'CompanionFaction',
  voiceType: 'MaleEvenToned',
  personality: DEFAULT_PERSONALITY,
  combat: DEFAULT_COMBAT,
  dialogue: [
    { id: '1', condition: 'OnPlayerAcquireItem', line: 'Nice find. Could be useful.', voiceType: 'MaleEvenToned' },
    { id: '2', condition: 'OnCombatStart',        line: 'Contact! Watch your six.', voiceType: 'MaleEvenToned' },
    { id: '3', condition: 'OnPlayerLevelUp',      line: 'Keeps getting stronger. Respect.', voiceType: 'MaleEvenToned' },
    { id: '4', condition: 'OnArriveAtLocation',   line: 'Never thought I\'d see this place again.', voiceType: 'MaleEvenToned' },
  ],
  affinityThresholds: { like: 250, dislike: -250, loathe: -750, idolize: 750 },
};

// ─────────────────────────────────────────────────────────────────────────────
// Papyrus Generator
// ─────────────────────────────────────────────────────────────────────────────

function generatePapyrusScript(profile: CompanionProfile): string {
  return `; ─────────────────────────────────────────────────────────────────────────
; ${profile.name} Companion AI Script — Generated by Mossy FO4 Advanced AI
; ─────────────────────────────────────────────────────────────────────────
Scriptname ${profile.name}CompanionScript extends Actor

; ── Personality Constants ──────────────────────────────────────────────────
${profile.personality.map(t => `float Property ${t.key.charAt(0).toUpperCase() + t.key.slice(1)}Base = ${t.value / 100.0} Auto`).join('\n')}

; ── Affinity Thresholds ────────────────────────────────────────────────────
int Property AffinityLike    = ${profile.affinityThresholds.like}    Auto
int Property AffinityDislike = ${profile.affinityThresholds.dislike} Auto
int Property AffinityLoathe  = ${profile.affinityThresholds.loathe}  Auto
int Property AffinityIdolize = ${profile.affinityThresholds.idolize} Auto

; ── Combat Properties ──────────────────────────────────────────────────────
float Property RetreatHealthPct = ${profile.combat.retreatHealth / 100.0} Auto
bool  Property FlankingEnabled  = ${profile.combat.flankingEnabled} Auto
bool  Property GrenadeUsage     = ${profile.combat.grenadeUsage}    Auto

; ── Events ─────────────────────────────────────────────────────────────────
Event OnInit()
  RegisterForRemoteEvent(Game.GetPlayer(), "OnPlayerLoadGame")
  RegisterForRemoteEvent(Game.GetPlayer(), "OnCombatStateChanged")
  InitializePersonality()
EndEvent

Function InitializePersonality()
  ; Apply personality weights to combat style
  ActorValue kAggression = Game.GetFormFromFile(0x000002E7, "Fallout4.esm") as ActorValue
  Self.SetValue(kAggression, AggressionBase * 100.0)
  Debug.Notification("[${profile.name}] AI initialized — Style: ${profile.combat.style}")
EndFunction

Event OnCombatStateChanged(int aeCombatState)
  If aeCombatState == 1 ; Entering combat
    HandleCombatEntry()
  ElseIf aeCombatState == 0 ; Leaving combat
    HandleCombatExit()
  EndIf
EndEvent

Function HandleCombatEntry()
  Actor player = Game.GetPlayer()
  ${profile.combat.flankingEnabled ? `; Flanking logic\n  If Self.GetDistance(player.GetCombatTarget()) > ${profile.combat.meleeRange}\n    Self.SetValue(Game.GetFormFromFile(0x000002E8, "Fallout4.esm") as ActorValue, ConfidenceBase * 100)\n  EndIf` : '; Flanking disabled'}
  ${profile.combat.grenadeUsage ? `; Enable grenade package\n  Self.EvaluatePackage()` : ''}
EndFunction

Function HandleCombatExit()
  Float hpPct = Self.GetValue(Game.GetFormFromFile(0x00000015, "Fallout4.esm") as ActorValue) / Self.GetBaseValue(Game.GetFormFromFile(0x00000015, "Fallout4.esm") as ActorValue)
  If hpPct < RetreatHealthPct
    Debug.Notification("[${profile.name}] Low health — seeking cover")
  EndIf
EndFunction

; ── Affinity System ─────────────────────────────────────────────────────────
Int _currentAffinity = 0

Function ModAffinity(int delta)
  _currentAffinity += delta
  _currentAffinity = Math.Clamp(_currentAffinity, AffinityLoathe, AffinityIdolize) as Int
  EvaluateAffinityState()
EndFunction

Function EvaluateAffinityState()
  If _currentAffinity >= AffinityIdolize
    Debug.Notification("[${profile.name}] Idolizes player — unlocking perk")
  ElseIf _currentAffinity >= AffinityLike
    Debug.Notification("[${profile.name}] Likes player")
  ElseIf _currentAffinity <= AffinityLoathe
    Debug.Notification("[${profile.name}] Loathes player — may leave")
  ElseIf _currentAffinity <= AffinityDislike
    Debug.Notification("[${profile.name}] Dislikes player")
  EndIf
EndFunction
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Sub-components
// ─────────────────────────────────────────────────────────────────────────────

const SliderRow: React.FC<{
  trait: PersonalityTrait;
  onChange: (key: string, val: number) => void;
}> = ({ trait, onChange }) => (
  <div className="group space-y-1">
    <div className="flex items-center justify-between">
      <span className="text-xs font-mono text-slate-300">{trait.label}</span>
      <span className="text-xs font-mono text-emerald-400 w-8 text-right">{trait.value}</span>
    </div>
    <input
      type="range" min={0} max={100} value={trait.value}
      onChange={e => onChange(trait.key, parseInt(e.target.value))}
      className="w-full h-1.5 rounded-full appearance-none cursor-pointer
                 bg-slate-700 accent-emerald-500"
    />
    <p className="text-[10px] text-slate-500 group-hover:text-slate-400 transition-colors">{trait.description}</p>
  </div>
);

const Section: React.FC<{ title: string; icon: React.ReactNode; children: React.ReactNode; defaultOpen?: boolean }> = ({
  title, icon, children, defaultOpen = true
}) => {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="border border-slate-700/50 rounded-lg overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-4 py-3
                   bg-slate-800/60 hover:bg-slate-800 transition-colors text-left"
      >
        <div className="flex items-center gap-2 text-sm font-mono text-emerald-400">
          {icon} {title}
        </div>
        {open ? <ChevronDown className="w-4 h-4 text-slate-500" /> : <ChevronRight className="w-4 h-4 text-slate-500" />}
      </button>
      {open && <div className="p-4 bg-slate-900/40 space-y-3">{children}</div>}
    </div>
  );
};

// ─────────────────────────────────────────────────────────────────────────────
// Main Component
// ─────────────────────────────────────────────────────────────────────────────

const CompanionAI: React.FC = () => {
  const [profile, setProfile] = useState<CompanionProfile>(DEFAULT_PROFILE);
  const [activeTab, setActiveTab] = useState<'personality' | 'combat' | 'dialogue' | 'affinity' | 'export'>('personality');
  const [generatedScript, setGeneratedScript] = useState('');
  const [newDialogue, setNewDialogue] = useState({ condition: '', line: '' });
  const [aiGenerating, setAiGenerating] = useState(false);

  const updatePersonality = useCallback((key: string, value: number) => {
    setProfile(p => ({
      ...p,
      personality: p.personality.map(t => t.key === key ? { ...t, value } : t)
    }));
  }, []);

  const updateCombat = useCallback(<K extends keyof CombatBehavior>(key: K, value: CombatBehavior[K]) => {
    setProfile(p => ({ ...p, combat: { ...p.combat, [key]: value } }));
  }, []);

  const addDialogue = useCallback(() => {
    if (!newDialogue.condition || !newDialogue.line) return;
    setProfile(p => ({
      ...p,
      dialogue: [...p.dialogue, {
        id: Date.now().toString(),
        condition: newDialogue.condition,
        line: newDialogue.line,
        voiceType: p.voiceType,
      }]
    }));
    setNewDialogue({ condition: '', line: '' });
  }, [newDialogue]);

  const removeDialogue = useCallback((id: string) => {
    setProfile(p => ({ ...p, dialogue: p.dialogue.filter(d => d.id !== id) }));
  }, []);

  const generateScript = useCallback(() => {
    setGeneratedScript(generatePapyrusScript(profile));
    setActiveTab('export');
  }, [profile]);

  const simulateAIGenerate = useCallback(() => {
    setAiGenerating(true);
    const aiLines = [
      { condition: 'OnPlayerKillEnemy',   line: `Wasteland justice. ${profile.name} approves.` },
      { condition: 'OnPlayerStealth',     line: 'Quiet. I like that.' },
      { condition: 'OnWeatherChange',     line: 'Storm rolling in. Stay sharp.' },
      { condition: 'OnPlayerHarvest',     line: 'Every cap counts out here.' },
      { condition: 'OnEnterNewLocation',  line: 'Eyes open. Could be anything in there.' },
    ];
    setTimeout(() => {
      setProfile(p => ({
        ...p,
        dialogue: [
          ...p.dialogue,
          ...aiLines.map((l, i) => ({ ...l, id: `ai-${Date.now()}-${i}`, voiceType: p.voiceType }))
        ]
      }));
      setAiGenerating(false);
    }, 1200);
  }, [profile.name]);

  const COMBAT_STYLES = ['aggressive', 'balanced', 'defensive', 'sniper', 'stealth'] as const;
  const COVER_OPTIONS = ['always', 'sometimes', 'never'] as const;
  const RACES = ['HumanRace', 'GhoulRace', 'SynthGen2Race', 'RobotAssaultronRace', 'SuperMutantRace'];
  const VOICE_TYPES = ['MaleEvenToned', 'MaleBoston', 'FemaleSultry', 'FemaleYoung', 'MaleRobot'];

  const tabs = [
    { id: 'personality', label: 'Personality', icon: <Brain className="w-3.5 h-3.5" /> },
    { id: 'combat',      label: 'Combat AI',   icon: <Sword className="w-3.5 h-3.5" /> },
    { id: 'dialogue',    label: 'Dialogue',    icon: <MessageSquare className="w-3.5 h-3.5" /> },
    { id: 'affinity',    label: 'Affinity',    icon: <Heart className="w-3.5 h-3.5" /> },
    { id: 'export',      label: 'Export',      icon: <Code className="w-3.5 h-3.5" /> },
  ] as const;

  return (
    <div className="flex flex-col h-full bg-[#050910] text-slate-200 overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/60 flex-shrink-0">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
            <User className="w-5 h-5 text-emerald-400" />
          </div>
          <div>
            <h1 className="text-base font-mono font-semibold text-slate-100">Companion AI Designer</h1>
            <p className="text-xs text-slate-500">Build advanced NPC companions with AI-driven behavior</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setProfile(DEFAULT_PROFILE)}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono
                       border border-slate-700 rounded-md text-slate-400
                       hover:border-slate-500 hover:text-slate-200 transition-colors"
          >
            <RotateCcw className="w-3 h-3" /> Reset
          </button>
          <button
            onClick={generateScript}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono
                       bg-emerald-500/10 border border-emerald-500/30 rounded-md
                       text-emerald-400 hover:bg-emerald-500/20 transition-colors"
          >
            <Download className="w-3 h-3" /> Export Papyrus
          </button>
        </div>
      </div>

      {/* Identity Bar */}
      <div className="px-6 py-3 border-b border-slate-800/60 bg-slate-900/30 flex-shrink-0">
        <div className="grid grid-cols-4 gap-3">
          {[
            { label: 'Name',       value: profile.name,      key: 'name',      type: 'text' },
            { label: 'Race',       value: profile.race,      key: 'race',      options: RACES },
            { label: 'Voice Type', value: profile.voiceType, key: 'voiceType', options: VOICE_TYPES },
            { label: 'Faction',    value: profile.faction,   key: 'faction',   type: 'text' },
          ].map(field => (
            <div key={field.key}>
              <label className="block text-[10px] font-mono text-slate-500 mb-1 uppercase tracking-wider">{field.label}</label>
              {'options' in field ? (
                <select
                  value={field.value}
                  onChange={e => setProfile(p => ({ ...p, [field.key]: e.target.value }))}
                  className="w-full px-2 py-1.5 text-xs font-mono bg-slate-800/60 border border-slate-700/50
                             rounded text-slate-200 focus:outline-none focus:border-emerald-500/50"
                >
                  {field.options!.map(o => <option key={o}>{o}</option>)}
                </select>
              ) : (
                <input
                  type="text" value={field.value}
                  onChange={e => setProfile(p => ({ ...p, [field.key]: e.target.value }))}
                  className="w-full px-2 py-1.5 text-xs font-mono bg-slate-800/60 border border-slate-700/50
                             rounded text-slate-200 focus:outline-none focus:border-emerald-500/50"
                />
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 px-6 pt-3 flex-shrink-0 border-b border-slate-800/60">
        {tabs.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-1.5 px-3 py-2 text-xs font-mono rounded-t transition-colors
              ${activeTab === tab.id
                ? 'text-emerald-400 border-b-2 border-emerald-500 bg-emerald-500/5'
                : 'text-slate-500 hover:text-slate-300'}`}
          >
            {tab.icon} {tab.label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      <div className="flex-1 overflow-y-auto p-6">

        {/* PERSONALITY TAB */}
        {activeTab === 'personality' && (
          <div className="max-w-2xl space-y-6">
            <div className="p-4 rounded-lg border border-emerald-500/20 bg-emerald-500/5">
              <div className="flex items-center gap-2 mb-1">
                <Zap className="w-4 h-4 text-emerald-400" />
                <span className="text-xs font-mono text-emerald-400">AI Personality Matrix</span>
              </div>
              <p className="text-xs text-slate-400">
                These values map directly to Fallout 4's ActorValues (Aggression, Confidence, etc.)
                and are embedded in the generated Papyrus script.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-6">
              {profile.personality.map(trait => (
                <SliderRow key={trait.key} trait={trait} onChange={updatePersonality} />
              ))}
            </div>

            {/* Personality Summary */}
            <div className="p-4 rounded-lg bg-slate-800/40 border border-slate-700/50">
              <p className="text-xs font-mono text-slate-500 mb-2 uppercase tracking-wider">AI Summary</p>
              <p className="text-xs text-slate-300 leading-relaxed">
                {profile.name} is a{' '}
                <span className="text-emerald-400">
                  {profile.personality.find(t => t.key === 'aggression')!.value < 30 ? 'pacifist' :
                   profile.personality.find(t => t.key === 'aggression')!.value < 60 ? 'moderate' : 'aggressive'}
                </span>{' '}
                companion with{' '}
                <span className="text-emerald-400">
                  {profile.personality.find(t => t.key === 'confidence')!.value < 40 ? 'low' :
                   profile.personality.find(t => t.key === 'confidence')!.value < 70 ? 'average' : 'high'}
                </span>{' '}
                confidence. Their{' '}
                <span className="text-emerald-400">
                  {profile.personality.find(t => t.key === 'morality')!.value < 30 ? 'dark' :
                   profile.personality.find(t => t.key === 'morality')!.value < 60 ? 'neutral' : 'honorable'}
                </span>{' '}
                morality makes them{' '}
                {profile.personality.find(t => t.key === 'assistance')!.value > 70 ? 'highly responsive to player needs' : 'selective about when to help'}.
              </p>
            </div>
          </div>
        )}

        {/* COMBAT TAB */}
        {activeTab === 'combat' && (
          <div className="max-w-2xl space-y-4">
            <Section title="Combat Style" icon={<Sword className="w-3.5 h-3.5" />}>
              <div className="grid grid-cols-5 gap-2">
                {COMBAT_STYLES.map(style => (
                  <button
                    key={style}
                    onClick={() => updateCombat('style', style)}
                    className={`px-3 py-2 text-xs font-mono rounded-md border capitalize transition-colors
                      ${profile.combat.style === style
                        ? 'bg-emerald-500/15 border-emerald-500/40 text-emerald-300'
                        : 'bg-slate-800/60 border-slate-700/50 text-slate-400 hover:border-slate-500'}`}
                  >
                    {style}
                  </button>
                ))}
              </div>
            </Section>

            <Section title="Tactical Parameters" icon={<Sliders className="w-3.5 h-3.5" />}>
              <div className="space-y-4">
                <div>
                  <div className="flex justify-between mb-1">
                    <span className="text-xs font-mono text-slate-300">Retreat at Health %</span>
                    <span className="text-xs font-mono text-emerald-400">{profile.combat.retreatHealth}%</span>
                  </div>
                  <input
                    type="range" min={5} max={75} value={profile.combat.retreatHealth}
                    onChange={e => updateCombat('retreatHealth', parseInt(e.target.value))}
                    className="w-full h-1.5 rounded-full appearance-none cursor-pointer bg-slate-700 accent-emerald-500"
                  />
                </div>
                <div>
                  <div className="flex justify-between mb-1">
                    <span className="text-xs font-mono text-slate-300">Melee Engagement Range</span>
                    <span className="text-xs font-mono text-emerald-400">{profile.combat.meleeRange} units</span>
                  </div>
                  <input
                    type="range" min={50} max={500} step={25} value={profile.combat.meleeRange}
                    onChange={e => updateCombat('meleeRange', parseInt(e.target.value))}
                    className="w-full h-1.5 rounded-full appearance-none cursor-pointer bg-slate-700 accent-emerald-500"
                  />
                </div>
              </div>
            </Section>

            <Section title="Behavior Flags" icon={<Shield className="w-3.5 h-3.5" />}>
              <div className="space-y-3">
                {[
                  { key: 'flankingEnabled', label: 'Flanking Maneuvers', desc: 'Companion attempts to flank enemies' },
                  { key: 'grenadeUsage',    label: 'Grenade Usage',       desc: 'Use grenades and throwables in combat' },
                ].map(flag => (
                  <label key={flag.key} className="flex items-start gap-3 cursor-pointer group">
                    <div className="relative mt-0.5">
                      <input
                        type="checkbox"
                        checked={profile.combat[flag.key as keyof CombatBehavior] as boolean}
                        onChange={e => updateCombat(flag.key as keyof CombatBehavior, e.target.checked as never)}
                        className="sr-only"
                      />
                      <div className={`w-4 h-4 rounded border-2 flex items-center justify-center transition-colors
                        ${profile.combat[flag.key as keyof CombatBehavior]
                          ? 'border-emerald-500 bg-emerald-500'
                          : 'border-slate-600 bg-slate-800'}`}
                      >
                        {profile.combat[flag.key as keyof CombatBehavior] && (
                          <svg className="w-2.5 h-2.5 text-slate-900" fill="currentColor" viewBox="0 0 12 12">
                            <path d="M10 3L5 8.5 2 5.5" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
                          </svg>
                        )}
                      </div>
                    </div>
                    <div>
                      <p className="text-xs font-mono text-slate-300 group-hover:text-slate-100 transition-colors">{flag.label}</p>
                      <p className="text-[10px] text-slate-500">{flag.desc}</p>
                    </div>
                  </label>
                ))}

                <div>
                  <label className="text-xs font-mono text-slate-300 mb-2 block">Cover Usage</label>
                  <div className="flex gap-2">
                    {COVER_OPTIONS.map(opt => (
                      <button
                        key={opt}
                        onClick={() => updateCombat('coverUsage', opt)}
                        className={`px-3 py-1.5 text-xs font-mono rounded-md border capitalize transition-colors
                          ${profile.combat.coverUsage === opt
                            ? 'bg-emerald-500/15 border-emerald-500/40 text-emerald-300'
                            : 'bg-slate-800/60 border-slate-700/50 text-slate-400 hover:border-slate-500'}`}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </Section>
          </div>
        )}

        {/* DIALOGUE TAB */}
        {activeTab === 'dialogue' && (
          <div className="max-w-3xl space-y-4">
            <div className="flex items-center justify-between">
              <p className="text-xs text-slate-500">{profile.dialogue.length} dialogue lines configured</p>
              <button
                onClick={simulateAIGenerate}
                disabled={aiGenerating}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono
                           bg-emerald-500/10 border border-emerald-500/30 rounded-md
                           text-emerald-400 hover:bg-emerald-500/20 transition-colors
                           disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {aiGenerating ? (
                  <><div className="w-3 h-3 border border-emerald-400 border-t-transparent rounded-full animate-spin" /> Generating...</>
                ) : (
                  <><Zap className="w-3 h-3" /> AI Generate Lines</>
                )}
              </button>
            </div>

            <div className="space-y-2">
              {profile.dialogue.map(d => (
                <div key={d.id} className="flex items-start gap-3 p-3 rounded-lg bg-slate-800/40 border border-slate-700/40 group">
                  <div className="flex-1 min-w-0">
                    <span className="inline-block px-2 py-0.5 text-[10px] font-mono text-amber-400 bg-amber-500/10 rounded border border-amber-500/20 mb-1.5">
                      {d.condition}
                    </span>
                    <p className="text-xs text-slate-300 italic">"{d.line}"</p>
                  </div>
                  <button
                    onClick={() => removeDialogue(d.id)}
                    className="opacity-0 group-hover:opacity-100 p-1 text-slate-500 hover:text-red-400 transition-all"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>

            <div className="p-4 rounded-lg border border-slate-700/50 bg-slate-800/30 space-y-3">
              <p className="text-xs font-mono text-slate-400">Add Dialogue Line</p>
              <div className="grid grid-cols-2 gap-3">
                <input
                  type="text" placeholder="Condition (e.g. OnCombatStart)"
                  value={newDialogue.condition}
                  onChange={e => setNewDialogue(n => ({ ...n, condition: e.target.value }))}
                  className="px-3 py-2 text-xs font-mono bg-slate-800 border border-slate-700/50 rounded
                             text-slate-200 placeholder-slate-600 focus:outline-none focus:border-emerald-500/50"
                />
                <input
                  type="text" placeholder="Dialogue line text..."
                  value={newDialogue.line}
                  onChange={e => setNewDialogue(n => ({ ...n, line: e.target.value }))}
                  className="px-3 py-2 text-xs font-mono bg-slate-800 border border-slate-700/50 rounded
                             text-slate-200 placeholder-slate-600 focus:outline-none focus:border-emerald-500/50"
                />
              </div>
              <button
                onClick={addDialogue}
                className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono
                           border border-slate-600 rounded-md text-slate-300
                           hover:border-emerald-500/50 hover:text-emerald-400 transition-colors"
              >
                <Plus className="w-3.5 h-3.5" /> Add Line
              </button>
            </div>
          </div>
        )}

        {/* AFFINITY TAB */}
        {activeTab === 'affinity' && (
          <div className="max-w-xl space-y-6">
            <div className="p-4 rounded-lg border border-slate-700/50 bg-slate-800/30">
              <p className="text-xs font-mono text-slate-400 mb-4 uppercase tracking-wider">Affinity Thresholds</p>
              <div className="space-y-4">
                {[
                  { key: 'idolize', label: 'Idolize',  color: 'text-emerald-400', desc: 'Max positive — unlock companion perk' },
                  { key: 'like',    label: 'Like',      color: 'text-blue-400',    desc: 'Companion enjoys player choices' },
                  { key: 'dislike', label: 'Dislike',   color: 'text-amber-400',   desc: 'Companion voices displeasure' },
                  { key: 'loathe',  label: 'Loathe',    color: 'text-red-400',     desc: 'Max negative — companion may leave' },
                ].map(({ key, label, color, desc }) => (
                  <div key={key}>
                    <div className="flex items-center justify-between mb-1">
                      <div>
                        <span className={`text-xs font-mono ${color}`}>{label}</span>
                        <span className="text-[10px] text-slate-500 ml-2">{desc}</span>
                      </div>
                      <span className={`text-xs font-mono ${color}`}>
                        {profile.affinityThresholds[key as keyof typeof profile.affinityThresholds]}
                      </span>
                    </div>
                    <input
                      type="range"
                      min={key === 'loathe' ? -1000 : key === 'dislike' ? -500 : key === 'like' ? 0 : 500}
                      max={key === 'loathe' ? -500 : key === 'dislike' ? 0 : key === 'like' ? 500 : 1000}
                      value={profile.affinityThresholds[key as keyof typeof profile.affinityThresholds]}
                      onChange={e => setProfile(p => ({
                        ...p,
                        affinityThresholds: { ...p.affinityThresholds, [key]: parseInt(e.target.value) }
                      }))}
                      className="w-full h-1.5 rounded-full appearance-none cursor-pointer bg-slate-700 accent-emerald-500"
                    />
                  </div>
                ))}
              </div>
            </div>

            {/* Affinity Timeline Visualization */}
            <div className="p-4 rounded-lg border border-slate-700/50 bg-slate-800/30">
              <p className="text-xs font-mono text-slate-400 mb-3 uppercase tracking-wider">Affinity Scale</p>
              <div className="relative h-6 rounded-full bg-gradient-to-r from-red-900/60 via-slate-700 to-emerald-900/60 border border-slate-600">
                {[
                  { val: profile.affinityThresholds.loathe,  color: 'bg-red-500',     label: 'Loathe' },
                  { val: profile.affinityThresholds.dislike, color: 'bg-amber-500',   label: 'Dislike' },
                  { val: profile.affinityThresholds.like,    color: 'bg-blue-500',    label: 'Like' },
                  { val: profile.affinityThresholds.idolize, color: 'bg-emerald-500', label: 'Idolize' },
                ].map(m => (
                  <div
                    key={m.label}
                    className={`absolute top-0 bottom-0 w-0.5 ${m.color}`}
                    style={{ left: `${((m.val + 1000) / 2000) * 100}%` }}
                    title={`${m.label}: ${m.val}`}
                  />
                ))}
              </div>
              <div className="flex justify-between mt-1 text-[9px] font-mono text-slate-600">
                <span>-1000</span><span>0</span><span>+1000</span>
              </div>
            </div>
          </div>
        )}

        {/* EXPORT TAB */}
        {activeTab === 'export' && (
          <div className="max-w-3xl space-y-4">
            {!generatedScript ? (
              <div className="flex flex-col items-center justify-center py-16 gap-4 text-center">
                <Code className="w-10 h-10 text-slate-600" />
                <p className="text-sm font-mono text-slate-400">No script generated yet</p>
                <button
                  onClick={generateScript}
                  className="flex items-center gap-2 px-4 py-2 text-xs font-mono
                             bg-emerald-500/10 border border-emerald-500/30 rounded-md
                             text-emerald-400 hover:bg-emerald-500/20 transition-colors"
                >
                  <Play className="w-3.5 h-3.5" /> Generate Papyrus Script
                </button>
              </div>
            ) : (
              <>
                <div className="flex items-center justify-between">
                  <span className="text-xs font-mono text-slate-400">{profile.name}CompanionScript.psc</span>
                  <div className="flex gap-2">
                    <button
                      onClick={() => navigator.clipboard.writeText(generatedScript)}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono
                                 border border-slate-700 rounded-md text-slate-400
                                 hover:border-slate-500 hover:text-slate-200 transition-colors"
                    >
                      <Save className="w-3 h-3" /> Copy
                    </button>
                    <button
                      onClick={() => {
                        const blob = new Blob([generatedScript], { type: 'text/plain' });
                        const a = document.createElement('a');
                        a.href = URL.createObjectURL(blob);
                        a.download = `${profile.name}CompanionScript.psc`;
                        a.click();
                      }}
                      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-mono
                                 bg-emerald-500/10 border border-emerald-500/30 rounded-md
                                 text-emerald-400 hover:bg-emerald-500/20 transition-colors"
                    >
                      <Download className="w-3 h-3" /> Download .psc
                    </button>
                  </div>
                </div>
                <pre className="p-4 rounded-lg bg-slate-900 border border-slate-700/50 text-xs font-mono
                               text-slate-300 overflow-x-auto leading-relaxed whitespace-pre-wrap">
                  {generatedScript}
                </pre>
              </>
            )}
          </div>
        )}

      </div>
    </div>
  );
};

export default CompanionAI;
