/**
 * Material Definition Generator - Creates .mossy_material.json metadata
 * 
 * Format: Standardized material definitions for enhanced mod textures
 * Used for: PBR material properties, texture map relationships, auto-detection
 */

import fs from 'fs';
import path from 'path';

export interface MaterialMapSet {
  baseName: string;
  diffuse?: string;
  normal?: string;
  specular?: string;
  roughness?: string;
  metallic?: string;
  ao?: string;
  cavity?: string;
}

export interface MaterialDefinition {
  name: string;
  baseTexture: string;
  pbr: {
    hasMetallic: boolean;
    hasAO: boolean;
    hasCavity: boolean;
    hasRoughness: boolean;
    roughnessChannel?: 'alpha' | 'rgb' | 'r' | 'g' | 'b';
  };
  textures: {
    diffuse: string;
    normal: string;
    specular: string;
    maps: {
      metallic?: string;
      ao?: string;
      cavity?: string;
    };
  };
}

export interface MossyMaterialManifest {
  version: '1.0';
  modName: string;
  modAuthor?: string;
  enhancedAt: string;
  enhancementLevel: 4 | 8 | 16;
  totalTextures: number;
  materials: MaterialDefinition[];
  textureStatistics: {
    diffuseCount: number;
    normalCount: number;
    specularCount: number;
    totalSize: number;
    enhancedSize: number;
  };
  metadata: {
    generator: 'Mossy v5.6.0';
    blenderVersion?: string;
    gpuUsed: boolean;
    processingTimeSeconds: number;
  };
}

/**
 * Generate material definitions from texture analysis
 */
export function generateMaterialDefinitions(
  modPath: string,
  textures: {
    diffuse: string[];
    normal: string[];
    specular: string[];
  },
  enhancementLevel: 4 | 8 | 16,
  modName: string,
  processingTime: number
): MossyMaterialManifest {
  // Create material map from base names
  const materialMap = new Map<string, MaterialMapSet>();

  // Group textures by base name (remove _d, _n, _s suffixes)
  const extractBaseName = (texturePath: string): string => {
    const filename = path.basename(texturePath);
    return filename
      .replace(/_d\.dds$/i, '')
      .replace(/_n\.dds$/i, '')
      .replace(/_s\.dds$/i, '')
      .replace(/_diffuse\.dds$/i, '')
      .replace(/_normal\.dds$/i, '')
      .replace(/_specular\.dds$/i, '')
      .replace(/\.dds$/i, '');
  };

  // Group diffuse
  textures.diffuse.forEach(tex => {
    const baseName = extractBaseName(tex);
    if (!materialMap.has(baseName)) {
      materialMap.set(baseName, { baseName });
    }
    materialMap.get(baseName)!.diffuse = tex;
  });

  // Group normal
  textures.normal.forEach(tex => {
    const baseName = extractBaseName(tex);
    if (!materialMap.has(baseName)) {
      materialMap.set(baseName, { baseName });
    }
    materialMap.get(baseName)!.normal = tex;
  });

  // Group specular
  textures.specular.forEach(tex => {
    const baseName = extractBaseName(tex);
    if (!materialMap.has(baseName)) {
      materialMap.set(baseName, { baseName });
    }
    materialMap.get(baseName)!.specular = tex;
  });

  // Create material definitions
  const materials: MaterialDefinition[] = [];
  for (const [baseName, maps] of materialMap.entries()) {
    if (!maps.diffuse) continue; // Skip if no diffuse (base texture)

    const material: MaterialDefinition = {
      name: baseName,
      baseTexture: maps.diffuse,
      pbr: {
        hasMetallic: true, // Generated by enhancer
        hasAO: true, // Generated by enhancer
        hasCavity: true, // Generated by enhancer
        hasRoughness: !!maps.specular,
        roughnessChannel: 'alpha', // Fallout 4 standard
      },
      textures: {
        diffuse: maps.diffuse,
        normal: maps.normal || 'auto-generated',
        specular: maps.specular || 'auto-generated',
        maps: {
          metallic: `${baseName}_metallic.dds`,
          ao: `${baseName}_ao.dds`,
          cavity: `${baseName}_cavity.dds`,
        },
      },
    };

    materials.push(material);
  }

  // Calculate statistics
  const totalSize = [...textures.diffuse, ...textures.normal, ...textures.specular]
    .reduce((sum, texPath) => {
      try {
        const fullPath = path.join(modPath, texPath);
        const stat = fs.statSync(fullPath);
        return sum + stat.size;
      } catch {
        return sum;
      }
    }, 0);

  const manifest: MossyMaterialManifest = {
    version: '1.0',
    modName,
    enhancedAt: new Date().toISOString(),
    enhancementLevel,
    totalTextures: materials.length,
    materials,
    textureStatistics: {
      diffuseCount: textures.diffuse.length,
      normalCount: textures.normal.length,
      specularCount: textures.specular.length,
      totalSize,
      enhancedSize: totalSize * enhancementLevel,
    },
    metadata: {
      generator: 'Mossy v5.6.0',
      gpuUsed: true,
      processingTimeSeconds: processingTime,
    },
  };

  return manifest;
}

/**
 * Save material manifest to .mossy_material.json
 */
export function saveMaterialManifest(
  outputDir: string,
  manifest: MossyMaterialManifest
): boolean {
  try {
    const manifestPath = path.join(outputDir, '.mossy_material.json');
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
    console.log(`[TextureEnhancer] Material manifest saved: ${manifestPath}`);
    return true;
  } catch (err) {
    console.error('[TextureEnhancer] Failed to save material manifest:', err);
    return false;
  }
}

/**
 * Load material manifest from .mossy_material.json
 */
export function loadMaterialManifest(modPath: string): MossyMaterialManifest | null {
  try {
    const manifestPath = path.join(modPath, '.mossy_material.json');
    if (!fs.existsSync(manifestPath)) {
      return null;
    }
    const content = fs.readFileSync(manifestPath, 'utf-8');
    return JSON.parse(content) as MossyMaterialManifest;
  } catch (err) {
    console.error('[TextureEnhancer] Failed to load material manifest:', err);
    return null;
  }
}

/**
 * Validate material manifest
 */
export function validateMaterialManifest(manifest: MossyMaterialManifest): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];

  if (manifest.version !== '1.0') {
    errors.push('Invalid manifest version');
  }

  if (!manifest.modName) {
    errors.push('Missing modName');
  }

  if (!manifest.materials || manifest.materials.length === 0) {
    errors.push('No materials defined');
  }

  for (const material of manifest.materials || []) {
    if (!material.name) errors.push('Material missing name');
    if (!material.baseTexture) errors.push(`Material ${material.name} missing baseTexture`);
    if (!material.textures?.diffuse)
      errors.push(`Material ${material.name} missing diffuse texture`);
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

export default {
  generateMaterialDefinitions,
  saveMaterialManifest,
  loadMaterialManifest,
  validateMaterialManifest,
};
