"""
Papyrus Script Template Generator
===================================
Generates complete, ready-to-compile Fallout 4 Papyrus scripts for the most
common mod patterns.  Every template produces a valid ``.psc`` source file
with:

- Correct ``ScriptName … extends …`` header
- The standard event handlers for that script type (OnInit, OnActivate, etc.)
- Inline comments explaining every block
- Import statements for the most-used FO4 utility scripts
- Placeholder variables and properties that the modder fills in

Supported template types
------------------------
``OBJECT``       – Generic ObjectReference (catch-all for placed objects)
``WEAPON``       – Weapon script (equip, fire, unequip events)
``ARMOR``        – Armor / apparel (equip, unequip)
``ACTIVATOR``    – Activator trigger (OnActivate, proximity)
``CONTAINER``    – Container (open, close, item add / remove)
``DOOR``         – Door (lock/unlock, teleport marker)
``QUEST``        – Quest controller (stage progression, aliases)
``MAGIC_EFFECT`` – Magic effect / spell script
``ALIAS_ACTOR``  – Actor alias (for quests)
``ALIAS_REF``    – Reference alias (for quests)
``TERMINAL``     – Terminal menu (pages, entries, keywords)
``HOLOTAPE``     – Holotape game / recording
``WORKSHOP``     – Settlement / workshop placeable object
``NPC``          – NPC AI package / dialogue trigger

Usage
-----
>>> from papyrus_helpers import PapyrusHelpers
>>> ok, text = PapyrusHelpers.generate("QUEST", "MyMod_QuestController")
>>> ok2, msg = PapyrusHelpers.export("QUEST", "MyMod_QuestController",
...                                   "/path/to/Scripts/Source/")
"""

from __future__ import annotations
import os
import bpy

# ---------------------------------------------------------------------------
# Template library
# ---------------------------------------------------------------------------

# Each template is a callable that takes (script_name: str) and returns a str.
# They are defined as plain string templates (format strings) for clarity.

def _t_object(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – ObjectReference script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   ============================================================ /;

ScriptName {name} extends ObjectReference

; ── Properties ─────────────────────────────────────────────────────────────
; Drag-and-drop references from the Creation Kit Property window.
; ObjectReference Property LinkedDoor Auto
; Actor Property PlayerRef Auto
; Sound Property ActivateSound Auto

; ── Variables ───────────────────────────────────────────────────────────────
bool bHasBeenActivated = false

; ── Events ──────────────────────────────────────────────────────────────────

Event OnInit()
    ; Runs once when this object is first placed / loaded into the game world.
    ; Good place for one-time setup.
    Debug.Notification("{name} initialised")
EndEvent

Event OnActivate(ObjectReference akActionRef)
    ; Fires when a player or NPC activates (interacts with) this object.
    If akActionRef == Game.GetPlayer()
        If !bHasBeenActivated
            bHasBeenActivated = true
            ; TODO: add your first-activation logic here
            Debug.Notification("{name} activated for the first time")
        Else
            ; TODO: add repeat-activation logic here
            Debug.Notification("{name} activated again")
        EndIf
    EndIf
EndEvent

Event OnCellAttach()
    ; Fires when the cell this object is in is loaded.
EndEvent

Event OnCellDetach()
    ; Fires when the cell is unloaded.
EndEvent
"""

def _t_weapon(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Weapon script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   ============================================================ /;

ScriptName {name} extends Weapon

; ── Properties ──────────────────────────────────────────────────────────────
; Actor Property PlayerRef Auto
; Sound Property FireSound Auto
; Explosion Property MuzzleExplosion Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnEquipped(Actor akActor)
    ; Fires when any actor equips this weapon.
    If akActor == Game.GetPlayer()
        Debug.Notification("{name} equipped by player")
        ; TODO: apply equip effects, start animations, etc.
    EndIf
EndEvent

Event OnUnequipped(Actor akActor)
    ; Fires when any actor un-equips this weapon.
    If akActor == Game.GetPlayer()
        Debug.Notification("{name} unequipped by player")
        ; TODO: remove equip effects
    EndIf
EndEvent

; Note: there is no OnFire event for weapons in FO4.
; Use a MagicEffect script on the projectile instead, or
; an EnchantmentScript to trigger on hit.
"""

def _t_armor(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Armor / Apparel script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   ============================================================ /;

ScriptName {name} extends Armor

; ── Properties ──────────────────────────────────────────────────────────────
; Actor Property PlayerRef Auto
; Perk Property ArmorPerk Auto          ; perk granted while wearing
; Spell Property ArmorAbility Auto      ; ability spell active while wearing
; Sound Property EquipSound Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnEquipped(Actor akActor)
    If akActor == Game.GetPlayer()
        Debug.Notification("{name} equipped")
        ; Add perk / ability while worn
        ; akActor.AddPerk(ArmorPerk)
        ; akActor.AddSpell(ArmorAbility)
    EndIf
EndEvent

Event OnUnequipped(Actor akActor)
    If akActor == Game.GetPlayer()
        Debug.Notification("{name} unequipped")
        ; Remove perk / ability when taken off
        ; akActor.RemovePerk(ArmorPerk)
        ; akActor.RemoveSpell(ArmorAbility)
    EndIf
EndEvent
"""

def _t_activator(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Activator trigger script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   ============================================================ /;

ScriptName {name} extends ObjectReference

; ── Properties ──────────────────────────────────────────────────────────────
; ObjectReference Property TargetObject Auto     ; object to affect on trigger
; GlobalVariable Property TriggerCount Auto       ; optional counter
; Bool Property bOneShot = true Auto              ; fire only once?
; Sound Property TriggerSound Auto

; ── Variables ───────────────────────────────────────────────────────────────
bool bTriggered = false

; ── Events ──────────────────────────────────────────────────────────────────

Event OnTriggerEnter(ObjectReference akActionRef)
    ; Fires when an object enters the trigger volume.
    Actor akActor = akActionRef as Actor
    If akActor && !bTriggered
        If bOneShot
            bTriggered = true
        EndIf
        ; TODO: trigger effect
        ; TargetObject.Activate(akActor)
        Debug.Notification("{name}: trigger entered")
    EndIf
EndEvent

Event OnTriggerLeave(ObjectReference akActionRef)
    ; Fires when the object leaves the trigger volume.
    ; TODO: on-leave logic
EndEvent

Event OnActivate(ObjectReference akActionRef)
    ; Can also be activated manually (e.g. a button).
    Debug.Notification("{name}: manually activated")
EndEvent
"""

def _t_container(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Container script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   ============================================================ /;

ScriptName {name} extends ObjectReference

; ── Properties ──────────────────────────────────────────────────────────────
; MiscObject Property SpawnItem Auto      ; item to pre-fill on first open
; Int Property SpawnCount = 1 Auto
; Sound Property OpenSound Auto
; Sound Property CloseSound Auto

; ── Variables ───────────────────────────────────────────────────────────────
bool bFirstOpen = true

; ── Events ──────────────────────────────────────────────────────────────────

Event OnOpen(ObjectReference akActionRef)
    ; Fires when the container is opened.
    If bFirstOpen
        bFirstOpen = false
        ; Pre-populate on first open
        ; If SpawnItem
        ;     Self.AddItem(SpawnItem, SpawnCount)
        ; EndIf
        Debug.Notification("{name}: opened for the first time")
    EndIf
EndEvent

Event OnClose(ObjectReference akActionRef)
    ; Fires when the container is closed.
    Debug.Notification("{name}: closed")
EndEvent

Event OnItemAdded(Form akBaseItem, int aiItemCount, ObjectReference akItemRef, ObjectReference akSourceContainer)
    ; Fires when an item is added (player deposits something).
    ; Debug.Trace("{name}: " + akBaseItem.GetName() + " x" + aiItemCount + " added")
EndEvent

Event OnItemRemoved(Form akBaseItem, int aiItemCount, ObjectReference akItemRef, ObjectReference akDestContainer)
    ; Fires when an item is removed (player takes something).
    ; Debug.Trace("{name}: " + akBaseItem.GetName() + " x" + aiItemCount + " removed")
EndEvent
"""

def _t_door(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Door script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   ============================================================ /;

ScriptName {name} extends ObjectReference

; ── Properties ──────────────────────────────────────────────────────────────
; ObjectReference Property TeleportMarker Auto   ; optional teleport destination
; Key Property RequiredKey Auto                  ; key to unlock (or None)
; Quest Property UnlockQuest Auto               ; quest that unlocks this door
; Int Property UnlockStage = 10 Auto            ; quest stage required to unlock
; Sound Property LockedSound Auto
; Sound Property UnlockedSound Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnOpen(ObjectReference akActionRef)
    ; Door opened.
    If TeleportMarker
        Game.GetPlayer().MoveTo(TeleportMarker)
    EndIf
EndEvent

Event OnActivate(ObjectReference akActionRef)
    ; Check lock / key before allowing activation.
    If Self.IsLocked()
        If RequiredKey && akActionRef == Game.GetPlayer()
            Actor kPlayer = Game.GetPlayer()
            If kPlayer.GetItemCount(RequiredKey) > 0
                Self.Unlock()
                Debug.Notification("{name}: unlocked with key")
            Else
                Debug.Notification("{name}: locked – you need the key")
            EndIf
        ElseIf UnlockQuest && UnlockQuest.GetCurrentStageID() >= UnlockStage
            Self.Unlock()
            Debug.Notification("{name}: unlocked by quest stage")
        Else
            Debug.Notification("{name}: locked")
        EndIf
    EndIf
EndEvent
"""

def _t_quest(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Quest controller script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   ============================================================ /;

ScriptName {name} extends Quest

; ── Properties ──────────────────────────────────────────────────────────────
; ReferenceAlias Property AliasPlayer Auto
; ReferenceAlias Property AliasTarget Auto
; Location Property QuestLocation Auto
; Scene Property IntroScene Auto
; Sound Property QuestStartSound Auto
; GlobalVariable Property GlobalQuestFlag Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnInit()
    ; Called when the quest object is first created / the game starts.
    Debug.Notification("{name}: quest initialised")
EndEvent

; ── Stage fragments ─────────────────────────────────────────────────────────
; These are called by the Creation Kit when you set a stage.
; Add Fragment_Stage_XX_Item_YY functions matching your quest stages.

Function Fragment_Stage_10_Item_00()
    ; Stage 10 – Quest starts
    Debug.Notification("{name}: stage 10 – quest started")
    ; IntroScene.Start()
EndFunction

Function Fragment_Stage_20_Item_00()
    ; Stage 20 – Objective complete
    Debug.Notification("{name}: stage 20 – objective complete")
EndFunction

Function Fragment_Stage_100_Item_00()
    ; Stage 100 – Quest complete
    Debug.Notification("{name}: stage 100 – quest complete")
    ; GlobalQuestFlag.SetValue(1)
    Self.CompleteAllObjectives()
EndFunction

; ── Utility ─────────────────────────────────────────────────────────────────

Function AdvanceToStage(int aiStage)
    ; Call this from another script to advance the quest.
    Self.SetStage(aiStage)
EndFunction

Function IsComplete() bool
    Return (Self.GetCurrentStageID() >= 100)
EndFunction
"""

def _t_magic_effect(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Magic Effect / Spell script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   ============================================================ /;

ScriptName {name} extends ActiveMagicEffect

; ── Properties ──────────────────────────────────────────────────────────────
; Explosion Property HitExplosion Auto
; Sound Property HitSound Auto
; ImageSpaceModifier Property HitISMD Auto
; Float Property EffectDuration = 10.0 Auto
; Float Property DamagePerSecond = 5.0 Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnEffectStart(Actor akTarget, Actor akCaster)
    ; Fires when this magic effect starts on akTarget.
    Debug.Notification("{name}: effect started on " + akTarget.GetDisplayName())
    ; HitExplosion.PlaceAtMe(akTarget)
    ; HitISMD.Apply(EffectDuration)
    ; Start a recurring damage loop:
    ; RegisterForSingleUpdate(1.0)
EndEvent

Event OnEffectFinish(Actor akTarget, Actor akCaster)
    ; Fires when the effect ends (duration elapsed or dispelled).
    Debug.Notification("{name}: effect ended on " + akTarget.GetDisplayName())
    ; HitISMD.Remove()
EndEvent

Event OnUpdate()
    ; Recurring update – called every 1 second if registered above.
    Actor akTarget = GetTargetActor()
    If akTarget && !akTarget.IsDead()
        akTarget.DamageActorValue("Health", DamagePerSecond)
        RegisterForSingleUpdate(1.0)   ; re-register for next tick
    EndIf
EndEvent
"""

def _t_alias_actor(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Quest Actor Alias script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   
   Attach this to a ReferenceAlias (type Actor) in the Creation Kit.
   ============================================================ /;

ScriptName {name} extends ReferenceAlias

; ── Properties ──────────────────────────────────────────────────────────────
; Quest Property OwningQuest Auto
; Int Property KillAdvancesStage = 0 Auto    ; set > 0 to advance quest on death
; Scene Property DeathScene Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnAliasInit()
    ; Fires when the alias is filled (the NPC enters the alias slot).
    Actor kActor = Self.GetActorReference()
    If kActor
        Debug.Notification("{name}: alias filled with " + kActor.GetDisplayName())
        ; Register for AI package change, dialogue, etc.
        RegisterForRemoteEvent(kActor, "OnDeath")
    EndIf
EndEvent

Event OnAliasReset()
    ; Fires when the alias is cleared.
    Debug.Notification("{name}: alias cleared")
EndEvent

Event Actor.OnDeath(Actor akSender, Actor akKiller)
    ; Fires when the aliased actor dies.
    Debug.Notification("{name}: aliased actor died")
    If KillAdvancesStage > 0 && OwningQuest
        OwningQuest.SetStage(KillAdvancesStage)
    EndIf
    If DeathScene
        DeathScene.Start()
    EndIf
EndEvent
"""

def _t_alias_ref(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Quest Reference Alias script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   
   Attach to a ReferenceAlias (any ObjectReference) in the Creation Kit.
   ============================================================ /;

ScriptName {name} extends ReferenceAlias

; ── Properties ──────────────────────────────────────────────────────────────
; Quest Property OwningQuest Auto
; Int Property ActivateAdvancesStage = 0 Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnAliasInit()
    Debug.Notification("{name}: reference alias filled")
    ; Register for activation events on this reference
    ObjectReference kRef = Self.GetReference()
    If kRef
        RegisterForRemoteEvent(kRef, "OnActivate")
    EndIf
EndEvent

Event OnAliasReset()
    Debug.Notification("{name}: reference alias reset")
EndEvent

Event ObjectReference.OnActivate(ObjectReference akSender, ObjectReference akActionRef)
    Debug.Notification("{name}: aliased reference activated")
    If ActivateAdvancesStage > 0 && OwningQuest
        OwningQuest.SetStage(ActivateAdvancesStage)
    EndIf
EndEvent
"""

def _t_terminal(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Terminal script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   
   Attach to a Terminal object in the Creation Kit.
   All terminal page/entry scripts are Fragment_Terminal_... functions.
   ============================================================ /;

ScriptName {name} extends Terminal

; ── Properties ──────────────────────────────────────────────────────────────
; ObjectReference Property LinkedDoor Auto    ; optional door to unlock
; GlobalVariable Property TerminalFlag Auto   ; optional global to set
; Sound Property TerminalSound Auto

; ── Terminal entry fragments ─────────────────────────────────────────────────
; Create one Fragment_Terminal_Entry_XX function per menu entry.
; The Creation Kit links each entry to a function by index.

Function Fragment_Terminal_Entry_00()
    ; Entry 0 – e.g. "Unlock Door"
    Debug.Notification("{name}: Entry 0 selected")
    If LinkedDoor
        LinkedDoor.Unlock()
        Debug.Notification("Door unlocked via terminal")
    EndIf
EndFunction

Function Fragment_Terminal_Entry_01()
    ; Entry 1 – e.g. "Disable security system"
    Debug.Notification("{name}: Entry 1 selected")
    ; TODO: add your effect here
    If TerminalFlag
        TerminalFlag.SetValue(1)
    EndIf
EndFunction

Function Fragment_Terminal_Entry_02()
    ; Entry 2 – e.g. "Read log entry"
    Debug.Notification("{name}: Entry 2 – log entry read")
EndFunction
"""

def _t_holotape(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Holotape script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   
   Attach to a Holotape form in the Creation Kit.
   ============================================================ /;

ScriptName {name} extends Holotape

; ── Properties ──────────────────────────────────────────────────────────────
; Quest Property HolotapeQuest Auto           ; quest to advance on playback
; Int Property PlaybackAdvancesStage = 0 Auto
; Sound Property RecordingComplete Auto

; ── Events ──────────────────────────────────────────────────────────────────

; Note: Holotape game scripts use Fragment_Game_* functions.
; Recording/message holotapes use OnInit and the Quest system.

Event OnInit()
    Debug.Notification("{name}: holotape created")
EndEvent

; ── Game entry fragments ─────────────────────────────────────────────────────
; These are called by the holotape mini-game system.

Function Fragment_Game_Entry_00()
    ; First menu option of the holotape game
    Debug.Notification("{name}: game entry 0 selected")
    If HolotapeQuest && PlaybackAdvancesStage > 0
        HolotapeQuest.SetStage(PlaybackAdvancesStage)
    EndIf
EndFunction
"""

def _t_workshop(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – Workshop / Settlement object script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   
   Attach to a constructible object (COBJ) or workshop item.
   ============================================================ /;

ScriptName {name} extends ObjectReference

; ── Properties ──────────────────────────────────────────────────────────────
; WorkshopScript Property WorkshopRef Auto      ; parent workshop
; Int Property PowerRequired = 2 Auto           ; electrical power draw
; Int Property WaterOutput = 0 Auto
; Int Property FoodOutput = 0 Auto
; Int Property DefenseOutput = 0 Auto
; Int Property BedCount = 0 Auto
; Bool Property bPowered = false Auto           ; set by workshop power grid
; Sound Property PowerOnSound Auto
; Sound Property PowerOffSound Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnInit()
    ; Register with the settlement system.
    If WorkshopRef
        WorkshopRef.AddKeyword(Game.GetFormFromFile(0x054BA6, "Fallout4.esm") as Keyword)
    EndIf
    Debug.Notification("{name}: workshop object initialised")
EndEvent

Event OnWorkshopObjectPlaced(WorkshopScript akWorkshop)
    ; Fires when the player places this object in build mode.
    WorkshopRef = akWorkshop
    Debug.Notification("{name}: placed in settlement")
EndEvent

Event OnWorkshopObjectDestroyed(WorkshopScript akWorkshop)
    ; Fires when the player scraps this object.
    Debug.Notification("{name}: scrapped")
EndEvent

Event OnPowerOn(ObjectReference akPowerGenerator)
    ; Fires when the settlement power grid connects to this object.
    bPowered = true
    Debug.Notification("{name}: powered on")
    ; Start powered effects, animations, sounds…
    ; PlayAnimation("PowerOn")
    ; PowerOnSound.Play(Self)
EndEvent

Event OnPowerOff()
    ; Fires when power is cut.
    bPowered = false
    Debug.Notification("{name}: powered off")
    ; PowerOffSound.Play(Self)
EndEvent
"""

def _t_npc(name: str) -> str:
    return f""";/ ============================================================
   {name}.psc
   Fallout 4 – NPC / Actor script
   Auto-generated by FO4 Mod Assistant (Blender add-on)
   
   Attach to an Actor form (NPC_) in the Creation Kit.
   ============================================================ /;

ScriptName {name} extends Actor

; ── Properties ──────────────────────────────────────────────────────────────
; Quest Property MyQuest Auto
; Int Property TalkAdvancesStage = 0 Auto
; Scene Property GreetScene Auto
; Faction Property MyFaction Auto
; Location Property HomeLocation Auto
; ActorBase Property SpawnTemplate Auto    ; for summoned variants
; Sound Property SpawnSound Auto
; Bool Property bHasGreeted = false Auto

; ── Events ──────────────────────────────────────────────────────────────────

Event OnInit()
    Debug.Notification("{name}: NPC initialised")
    If MyFaction
        Self.AddToFaction(MyFaction)
    EndIf
EndEvent

Event OnLoad()
    ; Called every time this NPC loads into memory (cell attach).
    Debug.Trace("{name}: loaded")
EndEvent

Event OnDeath(Actor akKiller)
    ; Fires when this NPC dies.
    Debug.Notification("{name}: killed by " + akKiller.GetDisplayName())
    If MyQuest
        MyQuest.SetStage(TalkAdvancesStage + 10)   ; advance past talk stage
    EndIf
EndEvent

Event OnHit(ObjectReference akAggressor, Form akSource, Projectile akProjectile, bool abPowerAttack, bool abSneakAttack, bool abBashAttack, bool abHitBlocked)
    ; Fires when this NPC is hit.
    ; React to being attacked:
    ; Self.StartCombat(akAggressor as Actor)
EndEvent

Event OnLocationChange(Location akOldLoc, Location akNewLoc)
    ; Fires when the NPC moves between locations.
EndEvent

; ── Dialogue / scene helper ─────────────────────────────────────────────────

Function GreetPlayer()
    If !bHasGreeted && GreetScene
        bHasGreeted = true
        GreetScene.Start()
    EndIf
EndFunction
"""


# Template dispatch table
_TEMPLATES: dict[str, callable] = {
    "OBJECT":       _t_object,
    "WEAPON":       _t_weapon,
    "ARMOR":        _t_armor,
    "ACTIVATOR":    _t_activator,
    "CONTAINER":    _t_container,
    "DOOR":         _t_door,
    "QUEST":        _t_quest,
    "MAGIC_EFFECT": _t_magic_effect,
    "ALIAS_ACTOR":  _t_alias_actor,
    "ALIAS_REF":    _t_alias_ref,
    "TERMINAL":     _t_terminal,
    "HOLOTAPE":     _t_holotape,
    "WORKSHOP":     _t_workshop,
    "NPC":          _t_npc,
}

TEMPLATE_ENUM_ITEMS = [
    ("OBJECT",       "Object Reference",         "Generic placed-object script (OnInit, OnActivate)"),
    ("WEAPON",       "Weapon",                   "Weapon equip / unequip events"),
    ("ARMOR",        "Armor / Apparel",           "Armor equip / unequip with perk support"),
    ("ACTIVATOR",    "Activator / Trigger",       "Trigger-volume and manual-activate script"),
    ("CONTAINER",    "Container",                 "Container open/close and item add/remove events"),
    ("DOOR",         "Door",                      "Door with lock, key-check, and teleport support"),
    ("QUEST",        "Quest Controller",          "Quest stage fragments and utility functions"),
    ("MAGIC_EFFECT", "Magic Effect",              "ActiveMagicEffect with start/finish/update loop"),
    ("ALIAS_ACTOR",  "Quest Alias – Actor",       "ReferenceAlias for an NPC with death event"),
    ("ALIAS_REF",    "Quest Alias – Reference",   "ReferenceAlias for any object with activate event"),
    ("TERMINAL",     "Terminal",                  "Terminal entry fragments with door/flag support"),
    ("HOLOTAPE",     "Holotape",                  "Holotape game entries with quest stage advance"),
    ("WORKSHOP",     "Workshop / Settlement",     "Constructible object with power on/off events"),
    ("NPC",          "NPC / Actor",               "Actor script with combat, death, and dialogue"),
]


# ---------------------------------------------------------------------------
# PapyrusHelpers
# ---------------------------------------------------------------------------

class PapyrusHelpers:
    """Generate and export Papyrus script templates."""

    @staticmethod
    def generate(template_id: str, script_name: str) -> tuple[bool, str]:
        """Return (True, script_text) for the given template and script name.

        ``script_name`` must be a valid Papyrus identifier (letters, digits,
        underscores).  Spaces are replaced with underscores automatically.
        """
        safe_name = script_name.replace(" ", "_").strip()
        if not safe_name:
            return False, "Script name cannot be empty"

        fn = _TEMPLATES.get(template_id)
        if fn is None:
            return False, f"Unknown template type: {template_id!r}"

        try:
            text = fn(safe_name)
            return True, text
        except Exception as exc:
            return False, f"Template generation failed: {exc}"

    @staticmethod
    def export(template_id: str, script_name: str,
               output_dir: str) -> tuple[bool, str]:
        """Write the script to ``<output_dir>/<ScriptName>.psc``.

        Creates ``output_dir`` if it does not exist.
        """
        ok, content = PapyrusHelpers.generate(template_id, script_name)
        if not ok:
            return False, content

        safe_name = script_name.replace(" ", "_").strip()
        try:
            os.makedirs(output_dir, exist_ok=True)
            filepath = os.path.join(output_dir, f"{safe_name}.psc")
            with open(filepath, "w", encoding="utf-8") as fh:
                fh.write(content)
            return True, f"Script saved: {filepath}"
        except Exception as exc:
            return False, f"Failed to write script: {exc}"

    @staticmethod
    def get_compile_instructions(script_name: str, mod_name: str = "MyMod") -> str:
        """Return a plain-text guide for compiling a .psc file."""
        return f"""Papyrus Compile Instructions for {script_name}.psc
=======================================================

1. In the Creation Kit:
   File → Preferences → Papyrus
   Set 'Source Folder' to your mod's Scripts\\Source\\ folder.

2. Place {script_name}.psc in:
   <FO4 Data>\\Scripts\\Source\\User\\{script_name}.psc

3. Compile via Creation Kit:
   Gameplay → Papyrus Script Manager → right-click → Compile

   OR from command line (PapyrusCompiler.exe from CK install):
   PapyrusCompiler.exe "{script_name}.psc" -f="Institute_Papyrus_Flags.flg" \\
       -i="Data\\Scripts\\Source\\User;Data\\Scripts\\Source\\Base" \\
       -o="Data\\Scripts"

4. The compiled .pex goes to:
   <FO4 Data>\\Scripts\\{script_name}.pex

5. In the Creation Kit, attach {script_name} to your form:
   Open the form → Scripts tab → Add → type '{script_name}'

Documentation: https://falloutck.uesp.net/wiki/Papyrus_Documentation
"""


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------

def register():
    bpy.types.Scene.fo4_papyrus_template    = bpy.props.EnumProperty(
        name="Script Template",
        description="Papyrus script type to generate",
        items=TEMPLATE_ENUM_ITEMS,
        default="OBJECT",
    )
    bpy.types.Scene.fo4_papyrus_script_name = bpy.props.StringProperty(
        name="Script Name",
        description="CamelCase name for the Papyrus script (no spaces)",
        default="MyMod_MyScript",
    )
    bpy.types.Scene.fo4_papyrus_output_dir  = bpy.props.StringProperty(
        name="Output Folder",
        description="Where to save the .psc file (e.g. Data/Scripts/Source/User)",
        subtype="DIR_PATH",
        default="",
    )
    bpy.types.Scene.fo4_papyrus_mod_name    = bpy.props.StringProperty(
        name="Mod Name",
        description="Your mod's prefix (used in compile instructions)",
        default="MyMod",
    )


def unregister():
    for prop in ("fo4_papyrus_template", "fo4_papyrus_script_name",
                 "fo4_papyrus_output_dir", "fo4_papyrus_mod_name"):
        if hasattr(bpy.types.Scene, prop):
            try:
                delattr(bpy.types.Scene, prop)
            except Exception:
                pass
