import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { DraftingCompass, Briefcase, CheckCircle2, Copy, AlertCircle, FileText, FolderOpen, Upload, ClipboardList, Cpu, Shield, Download, RotateCcw } from 'lucide-react';
import { ToolsInstallVerifyPanel } from './components/ToolsInstallVerifyPanel';
import { useWheelScrollProxy } from './components/useWheelScrollProxy';

// ============================================================================
// MOD ARCHITECTURE PLANNER — Blueprint for Fallout 4 Mods
// ============================================================================

interface ModTemplate {
    id: string;
    name: string;
    description: string;
    structure: FileStructure[];
    components: ModComponent[];
    dependencies: string[];
    recommendedTools: string[];
    pluginType: 'ESP' | 'ESL' | 'ESM' | 'None';
    checklist: string[];
}

interface FileStructure {
    path: string;
    type: 'folder' | 'file';
    description: string;
}

interface ModComponent {
    name: string;
    type: string;
    required: boolean;
    description: string;
}

// ============================================================================
// MOD RECIPE DATA — Real Fallout 4 Mod Structures (v2.4.0)
// ============================================================================

const MOD_TEMPLATES: ModTemplate[] = [
    {
        id: 'quest',
        name: 'Quest Mod',
        description: 'Multi-stage quest with dialogue, scripts, and stage index',
        pluginType: 'ESP',
        structure: [
            { path: 'MyQuestMod.esp', type: 'file', description: 'Main plugin (full ESP — quests rarely fit ESL record limits)' },
            { path: 'Data/Scripts/Source/', type: 'folder', description: 'Papyrus source scripts (.psc)' },
            { path: 'Data/Scripts/', type: 'folder', description: 'Compiled Papyrus bytecode (.pex)' },
            { path: 'Data/Seq/', type: 'folder', description: 'Start-game-enabled quest SEQ files (critical — without this the quest never starts)' },
            { path: 'Data/Sound/Voice/MyQuestMod.esp/', type: 'folder', description: 'Voice files — subfolder per NPC FormID (e.g. 000D1234/)' },
            { path: 'Data/Meshes/Actors/Character/FaceGenData/FaceGeom/MyQuestMod.esp/', type: 'folder', description: 'FaceGen geometry for custom NPCs' },
            { path: 'Data/Textures/Actors/Character/FaceCustomization/MyQuestMod.esp/', type: 'folder', description: 'FaceGen tint textures' },
        ],
        components: [
            { name: 'Quest Record', type: 'QUST', required: true, description: 'Main quest with stages, objectives, and aliases' },
            { name: 'Aliases', type: 'ALID', required: true, description: 'References to NPCs / items / locations used in quest' },
            { name: 'Quest Stages', type: 'QOBJ', required: true, description: 'Numbered progression points with completion conditions' },
            { name: 'SEQ File', type: '.seq', required: true, description: 'Generated by CK — makes quest Start-Game-Enabled. Omitting this is the #1 cause of quests not starting.' },
            { name: 'Papyrus Fragments', type: 'SCPT', required: false, description: 'Stage/condition Papyrus fragments auto-generated by CK' },
            { name: 'Dialogue Topics', type: 'DIAL / INFO', required: false, description: 'Quest-specific NPC dialogue with conditions' },
            { name: 'Rewards', type: 'MISC/ARMO/WEAP', required: false, description: 'Items granted on completion via script or leveled list' },
        ],
        dependencies: ['Fallout4.esm'],
        recommendedTools: ['Creation Kit', 'xEdit/FO4Edit', 'Notepad++ with Papyrus syntax', 'Bethini (INI tweaks for CK)'],
        checklist: [
            'SEQ file generated and included in archive',
            'All quest aliases have valid Fill Type conditions',
            'FaceGen data exported from CK (grey-face bug prevention)',
            'Voice files placed in correct subfolder (plugin name / FormID)',
            'No ITM (Identical To Master) records — run xEdit cleaning',
            'No UDR (Undelete and Disable References) — run xEdit cleaning',
            'Quest tested from a clean save (not mid-playthrough)',
            'Stage completion conditions tested in-game',
        ],
    },
    {
        id: 'settlement',
        name: 'Settlement Expansion',
        description: 'New settlement workbenches, plots, and buildable objects',
        pluginType: 'ESP',
        structure: [
            { path: 'SettlementPack.esp', type: 'file', description: 'Main plugin (ESP — DLC masters prevent ESL-flagging without careful record count audit)' },
            { path: 'Data/Meshes/Settlement/', type: 'folder', description: 'Custom settlement object geometry (NIF files)' },
            { path: 'Data/Textures/Settlement/', type: 'folder', description: 'Diffuse (_d), normal (_n), specular (_s) DDS textures' },
            { path: 'Data/Materials/', type: 'folder', description: 'Material swap definitions (BGSM/BGEM files)' },
            { path: 'Data/Scripts/Source/', type: 'folder', description: 'Settlement and workshop logic scripts' },
            { path: 'Data/Scripts/', type: 'folder', description: 'Compiled Papyrus bytecode (.pex)' },
        ],
        components: [
            { name: 'Workshop Marker', type: 'WTST', required: true, description: 'Defines the settlement workshop boundary' },
            { name: 'Static Objects', type: 'STAT', required: false, description: 'Non-interactive decor (walls, floors, structures)' },
            { name: 'Furniture', type: 'FURN', required: false, description: 'Interactive settlement furniture (chairs, benches, crafting stations)' },
            { name: 'Activators', type: 'ACTI', required: false, description: 'Clickable objects (doors, terminals, switches)' },
            { name: 'Build Plots', type: 'PLYM', required: false, description: 'Buildable plot categories — used by Sim Settlements 2' },
            { name: 'Navmesh', type: 'NAVM', required: false, description: 'NPC pathfinding — mandatory if settlers or enemies navigate the area' },
            { name: 'Crafting Recipe', type: 'COBJ', required: false, description: 'Workshop menu entry — category, components, and unlock conditions' },
            { name: 'Leveled Lists', type: 'LVLI', required: false, description: 'Inject items into random loot pools' },
        ],
        dependencies: ['Fallout4.esm', 'DLCWorkshop01.esm', 'DLCWorkshop02.esm', 'DLCWorkshop03.esm'],
        recommendedTools: ['Creation Kit', 'xEdit/FO4Edit', 'NifSkope', 'Outfit Studio (for mesh edits)', 'Material Editor'],
        checklist: [
            'Crafting recipes (COBJ) point to correct workshop menu keyword',
            'Navmesh finalized and checked for open edges',
            'Workshop marker covers the entire intended build area',
            'Textures are power-of-two (512, 1024, 2048) and BC7 compressed',
            'NIF files have correct BSTriShape / BSLightingShaderProperty paths',
            'No ITM/UDR — run xEdit cleaning',
            'Test in a fresh settlement with no other mods active',
        ],
    },
    {
        id: 'companion',
        name: 'NPC Companion',
        description: 'New follower with dialogue, perks, and AI packages',
        pluginType: 'ESP',
        structure: [
            { path: 'CompanionMod.esp', type: 'file', description: 'Main plugin (full ESP)' },
            { path: 'Data/Meshes/Actors/Character/FaceGenData/FaceGeom/CompanionMod.esp/', type: 'folder', description: 'FaceGen geometry — one subfolder per NPC FormID' },
            { path: 'Data/Textures/Actors/Character/FaceCustomization/CompanionMod.esp/', type: 'folder', description: 'FaceGen tint / complexion textures' },
            { path: 'Data/Sound/Voice/CompanionMod.esp/', type: 'folder', description: 'Voice lines (XWM recommended; WAV supported but larger)' },
            { path: 'Data/Scripts/Source/', type: 'folder', description: 'Companion AI, follow/dismiss logic' },
            { path: 'Data/Scripts/', type: 'folder', description: 'Compiled Papyrus bytecode (.pex)' },
        ],
        components: [
            { name: 'NPC Record', type: 'NPC_', required: true, description: 'Full character data: race, stats, default outfit, AI data' },
            { name: 'Dialogue Topics', type: 'DIAL / INFO', required: true, description: 'Greeting, idle comments, follow/dismiss voice lines' },
            { name: 'AI Packages', type: 'PACK', required: true, description: 'Daily schedules and behavior routines (sandbox, follow, sleep)' },
            { name: 'Companion Package', type: 'PACK (DialogueFollow)', required: true, description: 'The DialogueFollow package that makes the NPC followable' },
            { name: 'Default Outfit', type: 'OTFT', required: true, description: 'What the companion wears by default' },
            { name: 'Faction Membership', type: 'FACT', required: false, description: 'Player ally faction + companion faction for proper detection' },
            { name: 'Companion Perk', type: 'PERK', required: false, description: 'Special perk granted while companion is active' },
            { name: 'Combat Style', type: 'CSTL', required: false, description: 'Ranged/melee preference, aggression, cover usage' },
            { name: 'FaceGen Data', type: 'FaceGeom + Tints', required: true, description: 'Export from CK — prevents grey/black face bug' },
        ],
        dependencies: ['Fallout4.esm'],
        recommendedTools: ['Creation Kit', 'xEdit/FO4Edit', 'FaceRipper (for porting heads)', 'LooksMenu (for custom appearance)'],
        checklist: [
            'FaceGen exported from CK (Char Gen → Export All)',
            'DialogueFollow package is the first package in priority order',
            'Voice lines placed at correct path and matched to INFO FormID',
            'Companion joins player ally faction after hire dialogue',
            'Tested dismiss and rehire dialogue fully',
            'Test combat behavior at various distances',
            'No grey/black face — verify FaceGen path matches plugin name exactly',
        ],
    },
    {
        id: 'weapons',
        name: 'Weapon / Armor Pack',
        description: 'New weapons or armor with meshes, textures, and mod attachments',
        pluginType: 'ESL',
        structure: [
            { path: 'WeaponPack.esl', type: 'file', description: 'ESL plugin if record count ≤ 2047 new records (avoids eating an ESP slot)' },
            { path: 'Data/Meshes/Weapons/MyWeapon/', type: 'folder', description: '1st-person mesh (_1st.nif) and 3rd-person mesh' },
            { path: 'Data/Meshes/Armor/MyArmor/', type: 'folder', description: 'Armor geometry — separate files per body slot' },
            { path: 'Data/Textures/Weapons/MyWeapon/', type: 'folder', description: 'Diffuse (_d.dds), Normal (_n.dds), Specular (_s.dds)' },
            { path: 'Data/Textures/Armor/MyArmor/', type: 'folder', description: 'Armor texture sets' },
            { path: 'Data/Sound/FX/Weapons/', type: 'folder', description: 'Custom fire, reload, equip sounds (XWM or WAV)' },
        ],
        components: [
            { name: 'Weapon Record', type: 'WEAP', required: true, description: 'Stats: damage, fire rate, range, accuracy, keywords' },
            { name: 'Armor Record', type: 'ARMO + ARMA', required: true, description: 'ARMO = container record (slots, stats); ARMA = mesh/texture assignments per race' },
            { name: 'Keywords', type: 'KYWD', required: true, description: 'WeaponTypeRifle, ArmorHeavy, etc — controls perk and crafting behaviour' },
            { name: 'Model (NIF)', type: 'MODL', required: true, description: '1st-person and 3rd-person NIF references with physics (bhkCollisionObject)' },
            { name: 'Texture Set', type: 'TXST', required: true, description: 'Links DDS texture paths to model materials' },
            { name: 'Crafting Recipe', type: 'COBJ', required: false, description: 'Chemistry station / weapon workbench recipe with perk conditions' },
            { name: 'Leveled List Injection', type: 'LVLI (via script)', required: false, description: 'Add weapon to vendor / loot lists without hard-editing vanilla records' },
            { name: 'Mod Attachments', type: 'OMOD', required: false, description: 'Weapon mod slots: barrels, sights, stocks (Object Modification records)' },
        ],
        dependencies: ['Fallout4.esm'],
        recommendedTools: ['Blender + NIF Plugin', 'NifSkope', 'Outfit Studio', 'Substance Painter / GIMP for textures', 'xEdit for LList injection'],
        checklist: [
            'Both 1st-person (_1st) and 3rd-person NIF files present',
            'BSLightingShaderProperty flags set correctly (PBR: specular enabled)',
            'Texture paths in NIF match actual DDS file locations exactly',
            'Weapon keywords set (type, material) for perk compatibility',
            'Sound descriptors assigned to fire, reload, equip slots',
            'Crafting recipe requires appropriate perk and materials',
            'ESL record limit audit: ≤2047 new FormIDs if using .esl extension',
        ],
    },
    {
        id: 'worldexpansion',
        name: 'World Expansion',
        description: 'New cells, encounters, and environmental storytelling in the Commonwealth',
        pluginType: 'ESP',
        structure: [
            { path: 'WorldExpansion.esp', type: 'file', description: 'Main plugin (full ESP — world edits almost always exceed ESL limits)' },
            { path: 'Data/Meshes/Architecture/MyExpansion/', type: 'folder', description: 'Custom architecture and environmental objects' },
            { path: 'Data/Textures/Architecture/MyExpansion/', type: 'folder', description: 'Surface textures for custom assets' },
            { path: 'Data/Scripts/Source/', type: 'folder', description: 'Encounter, trap, and trigger scripting' },
            { path: 'Data/Scripts/', type: 'folder', description: 'Compiled Papyrus bytecode (.pex)' },
            { path: 'Data/Vis/', type: 'folder', description: 'Pre-combined mesh data (Previs) — required for performance in dense areas' },
        ],
        components: [
            { name: 'Worldspace / Cell', type: 'CELL / WRLD', required: true, description: 'Interior CELL or exterior Worldspace record defining the area' },
            { name: 'Object References', type: 'REFR', required: true, description: 'Every placed object, NPC, container, light — placed references' },
            { name: 'Navmesh', type: 'NAVM', required: true, description: 'NPC pathfinding — required if any NPCs or enemies are present' },
            { name: 'Precombines', type: 'PCMB / Vis', required: false, description: 'Merged meshes for performance — run PRP or CK precombine workflow' },
            { name: 'Creatures / Spawns', type: 'NPC_ / LVLN', required: false, description: 'Encounter zone creatures via encounter zone or leveled NPC lists' },
            { name: 'Lighting', type: 'LIGH / REGN', required: false, description: 'Light sources and image space adjustments for mood' },
            { name: 'Triggers / Traps', type: 'ACTI / HAZD', required: false, description: 'Pressure plates, laser tripwires, environmental hazards' },
        ],
        dependencies: ['Fallout4.esm'],
        recommendedTools: ['Creation Kit', 'xEdit/FO4Edit', 'PRP (Previs Repair Pack) for precombines', 'NifSkope', 'TexGen + xLODGen for LOD (DynDOLOD.exe itself does not support FO4)'],
        checklist: [
            'Navmesh covers all walkable surfaces and has no open edges',
            'Encounter zone set (prevents enemies from being level-capped)',
            'Precombines generated or existing precombines not broken',
            'LOD generated for exterior worldspace cells',
            'No floating or clipping objects — check in CK preview',
            'Performance tested — exterior cells should hold >30 FPS',
            'No ITM/UDR — run xEdit cleaning',
        ],
    },
    {
        id: 'playerhome',
        name: 'Player Home / Interior',
        description: 'Custom interior cell with player storage, fast-travel, and optional settlement',
        pluginType: 'ESL',
        structure: [
            { path: 'PlayerHome.esl', type: 'file', description: 'ESL if ≤2047 new records — player homes are typically small enough' },
            { path: 'Data/Meshes/PlayerHome/', type: 'folder', description: 'Any custom architectural or furniture meshes' },
            { path: 'Data/Textures/PlayerHome/', type: 'folder', description: 'Custom surface textures' },
            { path: 'Data/Scripts/Source/', type: 'folder', description: 'Key/door scripts, fast-travel activation, ownership scripts' },
            { path: 'Data/Scripts/', type: 'folder', description: 'Compiled Papyrus bytecode (.pex)' },
        ],
        components: [
            { name: 'Interior Cell', type: 'CELL', required: true, description: 'The interior CELL record — set lighting template, encounter zone, owner faction' },
            { name: 'Exterior Door', type: 'DOOR / REFR', required: true, description: 'The world-side door that teleports the player in' },
            { name: 'Interior Door', type: 'DOOR / REFR', required: true, description: 'The inside door that teleports the player out' },
            { name: 'Player Ownership', type: 'FACT (ownership)', required: true, description: 'Set ownership on all containers to player — prevents "stolen" items' },
            { name: 'Storage Containers', type: 'CONT', required: false, description: 'Chests/safes for player inventory — set respawn=false' },
            { name: 'Map Marker', type: 'REFR (MapMarker)', required: false, description: 'Fast-travel marker — discovered automatically via script on first entry' },
            { name: 'Settlement Workbench', type: 'FURN (WorkbenchType)', required: false, description: 'Turns the home into a settlement — requires DLC Workshop ESMs' },
        ],
        dependencies: ['Fallout4.esm'],
        recommendedTools: ['Creation Kit', 'xEdit/FO4Edit', 'NifSkope for mesh inspection'],
        checklist: [
            'Both entry and exit doors have correct teleport marker pairs',
            'All containers set to player-owned faction (no "stolen" flag)',
            'Container respawn = Never (players lose items if set to respawn)',
            'Map marker unlocked via script on first entry',
            'Lighting template appropriate for interior mood',
            'No navmesh errors (if companions should enter)',
            'ESL record count audit if using .esl extension',
        ],
    },
    {
        id: 'texturereplacer',
        name: 'Texture / Mesh Replacer',
        description: 'Replaces vanilla textures or meshes with no ESP plugin required',
        pluginType: 'None',
        structure: [
            { path: '(No .esp/.esl needed)', type: 'file', description: 'Loose file replacers require no plugin — files overwrite vanilla by filename match' },
            { path: 'Data/Textures/', type: 'folder', description: 'Mirror the vanilla path exactly — e.g. Data/Textures/Terrain/Commonwealth/' },
            { path: 'Data/Meshes/', type: 'folder', description: 'Mirror the vanilla NIF path exactly for mesh replacers' },
            { path: 'Data/Materials/', type: 'folder', description: 'BGSM/BGEM material swap files if altering material properties' },
        ],
        components: [
            { name: 'DDS Textures', type: '.dds (BC7 / BC1 / BC5)', required: true, description: 'BC7 for diffuse/complex, BC5 for normals, BC1 for single-channel masks. Must be power-of-two.' },
            { name: 'Mipmaps', type: 'DDS Mipmaps', required: true, description: 'Always generate full mipmap chains — missing mipmaps cause stutters at distance' },
            { name: 'NIF Meshes', type: '.nif', required: false, description: 'For mesh replacers — must match vanilla NIF version and BSTriShape structure' },
            { name: 'BGSM Material', type: '.bgsm / .bgem', required: false, description: 'Material definition file — controls PBR properties, shader flags, texture paths' },
        ],
        dependencies: [],
        recommendedTools: ['GIMP with DDS plugin', 'Photopea', 'Intel Texture Works (Photoshop)', 'NifSkope', 'Cathedral Assets Optimizer (CAO)'],
        checklist: [
            'All textures are power-of-two dimensions (512, 1024, 2048, 4096)',
            'Full mipmap chains generated for every DDS file',
            'BC7 used for diffuse/complex maps (best quality)',
            'BC5 used for normal maps (RG channels only)',
            'File paths mirror vanilla paths exactly (case-sensitive on some systems)',
            'Run Cathedral Assets Optimizer to verify format compatibility',
            'Test at various distances for mip quality and no pop-in',
        ],
    },
    {
        id: 'compatpatch',
        name: 'Compatibility Patch',
        description: 'ESP that resolves conflicts between two or more existing mods',
        pluginType: 'ESL',
        structure: [
            { path: 'ModA-ModB-Patch.esl', type: 'file', description: 'ESL-flagged patch — patches are almost always small enough for ESL limit' },
            { path: 'Data/Scripts/Source/', type: 'folder', description: 'Patching scripts if record edits alone are insufficient' },
        ],
        components: [
            { name: 'Overriding Records', type: 'Winning Overrides', required: true, description: 'Copy-as-override records from both mods, merged manually in xEdit' },
            { name: 'Forwarded Values', type: 'xEdit Forward', required: true, description: 'Each conflicting field resolved — right-click Forward in xEdit' },
            { name: 'Masters Declaration', type: 'File Header', required: true, description: 'Patch ESP must list both conflicting mods as masters' },
        ],
        dependencies: ['Fallout4.esm', '(ModA.esp)', '(ModB.esp)'],
        recommendedTools: ['xEdit/FO4Edit (primary tool)', 'LOOT for load order verification', 'BethINI'],
        checklist: [
            'Both conflicting mods listed as masters in patch header',
            'All conflicting records identified via xEdit conflict filter',
            'Each conflicting field manually resolved (not just one mod winning)',
            'Patch loads after both parent mods in load order',
            'ESL flag set if record count allows (saves an ESP slot for users)',
            'Tested with both mods active — no remaining red conflicts in xEdit',
            'Load order documentation included for users (README)',
        ],
    },
    {
        id: 'fomod',
        name: 'FOMOD Installer',
        description: 'XML-driven installer that lets users choose options during mod installation',
        pluginType: 'None',
        structure: [
            { path: 'fomod/', type: 'folder', description: 'FOMOD root folder — must be at the archive root, not inside Data/' },
            { path: 'fomod/info.xml', type: 'file', description: 'Mod metadata: name, author, version, website, description' },
            { path: 'fomod/ModuleConfig.xml', type: 'file', description: 'The installer logic: pages, options, conditions, file installs' },
            { path: 'fomod/images/', type: 'folder', description: 'Option preview images (JPG/PNG) referenced in ModuleConfig.xml' },
            { path: 'Core/', type: 'folder', description: 'Files always installed (no condition) — placed at archive root alongside fomod/' },
            { path: 'Options/OptionA/', type: 'folder', description: 'Files for optional choice A — installed only when user selects it' },
            { path: 'Options/OptionB/', type: 'folder', description: 'Files for optional choice B — mutual or independent of A' },
        ],
        components: [
            { name: 'info.xml', type: 'XML', required: true, description: 'Minimal required fields: Name, Author, Version. Website and Description recommended.' },
            { name: 'ModuleConfig.xml', type: 'XML', required: true, description: 'Defines install steps, option groups (SelectAny / SelectExactlyOne), and file mappings' },
            { name: 'Option Images', type: 'JPG/PNG', required: false, description: '300×200px thumbnails shown in the installer preview pane for each option' },
            { name: 'Core Files', type: 'Any', required: false, description: 'Files installed unconditionally — typically the main ESP and shared assets' },
            { name: 'Option File Sets', type: 'Any', required: false, description: 'One folder per option variant — only installed when the user selects that option' },
            { name: 'Conditional Flags', type: 'XML flags', required: false, description: 'Logic flags set by option selection, used to conditionally install files in later steps' },
        ],
        dependencies: [],
        recommendedTools: ['Mod Organizer 2 (test FOMOD in Preview mode)', 'FOMOD Creation Tool (standalone editor)', 'Notepad++ for XML editing', 'Wrye Bash (alternative installer test)'],
        checklist: [
            'fomod/ folder is at the archive root (not inside Data/)',
            'info.xml has valid Name, Author, Version fields',
            'ModuleConfig.xml validates without XML errors',
            'All image paths in ModuleConfig.xml match actual files in fomod/images/',
            'All file source paths in install steps match actual archive structure',
            'Tested in Mod Organizer 2 FOMOD preview — all options install correct files',
            'Tested in Vortex — installer renders and options work',
            'No missing files — every source referenced in XML exists in the archive',
        ],
    },
    {
        id: 'animation',
        name: 'Animation Mod (OAR/IAF/NAF)',
        description: 'Custom animations using Open Animation Replacer, Idle Animation Framework, or New Animation Framework',
        pluginType: 'ESL',
        structure: [
            { path: 'AnimMod.esl', type: 'file', description: 'ESL plugin — required only if you add new animation records (IDLE/ANIO). Pure OAR replacers need no plugin.' },
            { path: 'Data/meshes/actors/character/animations/OpenAnimationReplacer/MyMod/', type: 'folder', description: 'OAR root for your mod — subfolders per condition set. No plugin needed for replacers.' },
            { path: 'Data/meshes/actors/character/animations/OpenAnimationReplacer/MyMod/config.json', type: 'file', description: 'OAR condition file — JSON defining which actors / situations trigger the replacement' },
            { path: 'Data/meshes/actors/character/animations/MyMod/', type: 'folder', description: 'HKX animation files — Havok behavior graph clip files (.hkx)' },
            { path: 'Data/F4SE/Plugins/', type: 'folder', description: 'F4SE DLL plugins — required if using OAR, IAF, or NAF themselves (they ship DLLs here)' },
        ],
        components: [
            { name: 'HKX Animation Files', type: '.hkx (Havok Clip)', required: true, description: 'Actual animation data — exported from Blender via hkxcmd or Havok Content Tools. Must match skeleton version.' },
            { name: 'OAR config.json', type: 'JSON condition file', required: false, description: 'Defines replacement conditions: actor base, keyword, faction, location, equipped item — highly granular.' },
            { name: 'IDLE Records', type: 'IDLE (CK/xEdit)', required: false, description: 'New idle animation records — required if adding entirely new behaviors not replacing vanilla ones.' },
            { name: 'Behavior Graph Patch', type: 'HKX graph', required: false, description: 'For complex new behavior nodes — requires Havok behavior graph editing tools.' },
            { name: 'F4SE Dependency', type: 'F4SE + Address Library', required: true, description: 'OAR, IAF, and NAF all require F4SE 0.7.7+ and the matching Address Library build.' },
        ],
        dependencies: ['Fallout4.esm'],
        recommendedTools: [
            'Open Animation Replacer (Nexus — required runtime)',
            'hkxcmd (HKX conversion from Blender)',
            'Blender 3.6 + FO4 HKX export plugin',
            'Havok Content Tools (official Havok SDK — for behavior graphs)',
            'F4SE 0.7.7+ + Address Library (runtime dependencies)',
        ],
        checklist: [
            'HKX files exported at the correct Havok version for FO4 (2014.1.0)',
            'Skeleton compatibility verified — custom animations must match the target skeleton rig',
            'OAR config.json validates as valid JSON (use jsonlint.com)',
            'OAR condition priority set correctly (lower number = higher priority)',
            'F4SE + Address Library in user load order documentation / readme',
            'Tested with OAR MCM to confirm replacer is detected and active',
            'No animation clipping or T-pose — test in-game with target actor',
            'Performance checked — complex condition checks on large actor sets can cause lag',
        ],
    },
];

type ActiveTab = 'structure' | 'components' | 'dependencies' | 'checklist';

const TheBlueprint: React.FC = () => {
    const [selectedTemplate, setSelectedTemplate] = useState<ModTemplate>(MOD_TEMPLATES[0]);
    const [activeTab, setActiveTab] = useState<ActiveTab>('structure');
    const [copiedPath, setCopiedPath] = useState<string | null>(null);
    const [attachedSources, setAttachedSources] = useState<Record<string, string>>({});
    const [checkedItems, setCheckedItems] = useState<Record<string, boolean>>(() => {
        try {
            const stored = localStorage.getItem('mossy_blueprint_checklist');
            return stored ? (JSON.parse(stored) as Record<string, boolean>) : {};
        } catch {
            return {};
        }
    });

    const detailsScrollRef = useRef<HTMLDivElement | null>(null);
    const fileInputRefs = useRef<Record<string, HTMLInputElement | null>>({});
    const wheelProxy = useWheelScrollProxy(detailsScrollRef);

    const handleCopyStructure = async () => {
        const structureText = selectedTemplate.structure
            .map(item => `${item.type === 'folder' ? '[folder]' : '[file]'} ${item.path} — ${item.description}`)
            .join('\n');
        navigator.clipboard.writeText(structureText);
        setCopiedPath('all');
        setTimeout(() => setCopiedPath(null), 2000);
    };

    const handleCopyPath = (path: string) => {
        navigator.clipboard.writeText(path);
        setCopiedPath(path);
        setTimeout(() => setCopiedPath(null), 2000);
    };

    const getSelectedName = (sourcePath: string) => {
        const segments = sourcePath.split(/[\\/]/).filter(Boolean);
        return segments.length > 0 ? segments[segments.length - 1] : sourcePath;
    };

    const getAcceptForPath = (path: string) => {
        const match = path.match(/\.([a-z0-9]+)$/i);
        return match ? `.${match[1].toLowerCase()}` : undefined;
    };

    const handlePickSource = async (item: FileStructure) => {
        const api = (window as any).electron?.api || (window as any).electronAPI;
        if (item.type === 'folder') {
            const picker = api?.pickDirectory || api?.selectDirectory;
            if (!picker) return;
            const selected = await picker(`Select source for ${item.path}`);
            if (selected) setAttachedSources(prev => ({ ...prev, [item.path]: selected }));
            return;
        }
        const input = fileInputRefs.current[item.path];
        input?.click();
    };

    const handleFileSelected = (itemPath: string, files: FileList | null) => {
        if (!files || files.length === 0) return;
        const selected = files[0] as File & { path?: string };
        const resolvedPath = selected.path || selected.name;
        if (!resolvedPath) return;
        setAttachedSources(prev => ({ ...prev, [itemPath]: resolvedPath }));
    };

    const toggleCheck = (key: string) => {
        setCheckedItems(prev => ({ ...prev, [key]: !prev[key] }));
    };

    const checklistKey = (templateId: string, idx: number) => `${templateId}:${idx}`;

    useEffect(() => {
        try { localStorage.setItem('mossy_blueprint_checklist', JSON.stringify(checkedItems)); }
        catch { /* ignore */ }
    }, [checkedItems]);

    const exportChecklist = () => {
        const lines: string[] = [
            `# ${selectedTemplate.name} — Pre-Release Checklist`,
            '',
            `**Template:** ${selectedTemplate.name}  `,
            `**Progress:** ${completedCount}/${selectedTemplate.checklist.length} complete`,
            '',
        ];
        selectedTemplate.checklist.forEach((item, idx) => {
            const key = checklistKey(selectedTemplate.id, idx);
            lines.push(`- [${checkedItems[key] ? 'x' : ' '}] ${item}`);
        });
        const md = lines.join('\n');
        const blob = new Blob([md], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${selectedTemplate.id}-checklist.md`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const resetChecklist = () => {
        setCheckedItems(prev => {
            const next = { ...prev };
            selectedTemplate.checklist.forEach((_, i) => {
                delete next[checklistKey(selectedTemplate.id, i)];
            });
            return next;
        });
    };

    const pluginBadgeColor = (type: ModTemplate['pluginType']) => {
        switch (type) {
            case 'ESL': return 'bg-emerald-900/40 text-emerald-300 border-emerald-600/40';
            case 'ESP': return 'bg-amber-900/40 text-amber-300 border-amber-600/40';
            case 'ESM': return 'bg-blue-900/40 text-blue-300 border-blue-600/40';
            default: return 'bg-slate-800 text-slate-400 border-slate-600';
        }
    };

    const completedCount = selectedTemplate.checklist.filter((_, i) => checkedItems[checklistKey(selectedTemplate.id, i)]).length;

    return (
        <div className="h-full flex flex-col bg-[#1e1e1e] text-slate-200 font-sans overflow-hidden min-h-0" onWheel={wheelProxy}>
            {/* Header */}
            <div className="p-4 border-b border-black bg-[#2d2d2d] flex justify-between items-center shadow-md">
                <div>
                    <h2 className="text-lg font-bold text-white flex items-center gap-2">
                        <DraftingCompass className="w-5 h-5 text-amber-400" />
                        The Blueprint
                    </h2>
                    <p className="text-[10px] text-slate-400 font-mono mt-0.5">Mod Architecture Planner v2.4.0</p>
                </div>
                <div className="flex items-center gap-2">
                    <div className="px-3 py-1 bg-black rounded border border-slate-600 font-mono text-xs text-amber-400">
                        {MOD_TEMPLATES.length} Templates
                    </div>
                    <Link
                        to="/reference"
                        className="px-3 py-1 text-[10px] font-black uppercase tracking-widest rounded-lg bg-amber-900/30 border border-amber-500/30 text-amber-100 hover:bg-amber-900/40 transition-colors"
                        title="Open help"
                    >
                        Help
                    </Link>
                </div>
            </div>

            <div className="p-4 border-b border-black bg-[#1e1e1e]">
                <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
                    <ToolsInstallVerifyPanel
                        accentClassName="text-amber-300"
                        description="Blueprint is a planner: it helps you choose a sane mod structure and copy paths/components without guessing the file layout. It doesn't download tools or generate plugins by itself."
                        tools={[]}
                        verify={[
                            'Click a template and confirm Folder Structure/Components tabs update.',
                            'Use Copy to clipboard and paste into a text editor to confirm paths copied.',
                        ]}
                        firstTestLoop={[
                            'Pick a template that matches your mod type (Quest/Settlement/etc).',
                            'Copy the structure list, then create folders/files in your real mod workspace.',
                            'Open Chat and ask Mossy to review the planned structure for missing pieces.',
                        ]}
                        troubleshooting={[
                            'If copy fails, your browser/Electron clipboard permission may be blocked; try again after restarting the app.',
                            'If a template doesn\'t match your scope, treat it as a baseline and add only what you actually ship.',
                        ]}
                    />
                </div>
            </div>

            <div className="flex-1 min-h-0 flex overflow-hidden">
                {/* Left: Template List */}
                <div className="w-64 bg-[#252526] border-r border-black flex flex-col min-h-0">
                    <div className="p-2 bg-[#333333] border-b border-black text-[10px] font-bold text-slate-300 uppercase tracking-wider">
                        Mod Templates
                    </div>
                    <div className="flex-1 min-h-0 overflow-y-auto">
                        {MOD_TEMPLATES.map((template) => (
                            <div
                                key={template.id}
                                onClick={() => { setSelectedTemplate(template); setActiveTab('structure'); }}
                                className={`p-3 border-b border-slate-800 cursor-pointer transition-colors ${
                                    selectedTemplate.id === template.id
                                        ? 'bg-amber-900/30 border-l-4 border-l-amber-400'
                                        : 'hover:bg-[#2d2d30]'
                                }`}
                            >
                                <div className="font-semibold text-slate-200 text-sm">{template.name}</div>
                                <div className="text-[10px] text-slate-500 mt-0.5">{template.description}</div>
                                <div className="flex gap-1 mt-2 flex-wrap">
                                    <span className={`px-1.5 py-0.5 text-[9px] font-bold rounded border ${pluginBadgeColor(template.pluginType)}`}>
                                        {template.pluginType === 'None' ? 'No Plugin' : template.pluginType}
                                    </span>
                                    <span className="px-1.5 py-0.5 bg-slate-800 text-[9px] text-slate-400 rounded">
                                        {template.components.length} components
                                    </span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Center/Right: Template Details */}
                <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
                    {/* Template Tabs */}
                    <div className="flex border-b border-black bg-[#252526] items-center justify-between pr-3">
                        <div className="flex">
                            {(['structure', 'components', 'dependencies', 'checklist'] as ActiveTab[]).map(tab => (
                                <button
                                    key={tab}
                                    onClick={() => setActiveTab(tab)}
                                    className={`px-4 py-2 text-xs font-semibold border-b-2 transition-colors capitalize ${
                                        activeTab === tab
                                            ? 'border-amber-400 text-amber-300'
                                            : 'border-transparent text-slate-400 hover:text-slate-300'
                                    }`}
                                >
                                    {tab === 'checklist' ? `Checklist (${completedCount}/${selectedTemplate.checklist.length})` : tab === 'dependencies' ? 'Dependencies' : tab === 'components' ? 'Required Components' : 'Folder Structure'}
                                </button>
                            ))}
                        </div>
                        {/* Plugin type badge */}
                        <span className={`px-2 py-0.5 text-[9px] font-bold rounded border ${pluginBadgeColor(selectedTemplate.pluginType)}`}>
                            {selectedTemplate.pluginType === 'None' ? 'No Plugin Needed' : `Plugin: ${selectedTemplate.pluginType}`}
                        </span>
                    </div>

                    {/* Content Area */}
                    <div ref={detailsScrollRef} className="flex-1 min-h-0 overflow-y-auto overflow-x-auto p-4">

                        {/* FOLDER STRUCTURE TAB */}
                        {activeTab === 'structure' && (
                            <div className="space-y-2">
                                <div className="flex justify-between items-center mb-4">
                                    <h3 className="font-semibold text-slate-200">Folder & File Structure</h3>
                                    <button onClick={handleCopyStructure} className="p-1 hover:bg-slate-700 rounded transition-colors">
                                        {copiedPath === 'all' ? <CheckCircle2 className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4 text-slate-400" />}
                                    </button>
                                </div>
                                {selectedTemplate.structure.map((item, idx) => (
                                    <div key={idx} className="w-full text-left bg-[#252526] border border-slate-700 rounded p-3 hover:border-amber-500/60 hover:bg-[#2d2d30] transition-colors">
                                        <div className="flex items-start justify-between mb-1">
                                            <div className="flex items-center gap-2">
                                                {item.type === 'folder'
                                                    ? <FolderOpen className="w-4 h-4 text-amber-400 shrink-0" />
                                                    : <FileText className="w-4 h-4 text-slate-400 shrink-0" />
                                                }
                                                <code className="text-slate-300 font-mono text-xs">{item.path}</code>
                                            </div>
                                            <div className="flex items-center gap-1 shrink-0">
                                                <button
                                                    type="button"
                                                    onClick={(e) => { e.stopPropagation(); void handlePickSource(item); }}
                                                    className="p-1 rounded hover:bg-slate-700/80 transition-colors"
                                                    title={item.type === 'folder' ? 'Select source folder' : 'Select source file'}
                                                >
                                                    <Upload className={`w-3 h-3 ${attachedSources[item.path] ? 'text-green-400' : 'text-slate-500'}`} />
                                                </button>
                                                <button
                                                    type="button"
                                                    onClick={(e) => { e.stopPropagation(); handleCopyPath(item.path); }}
                                                    className="p-1 rounded hover:bg-slate-700/80 transition-colors"
                                                    title="Copy path"
                                                >
                                                    {copiedPath === item.path ? <CheckCircle2 className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3 text-slate-500" />}
                                                </button>
                                            </div>
                                        </div>
                                        <p className="text-[10px] text-slate-500 pl-6">{item.description}</p>
                                        {attachedSources[item.path] && (
                                            <p className="text-[10px] text-green-400/90 pl-6 mt-1">
                                                Selected: {getSelectedName(attachedSources[item.path])}
                                            </p>
                                        )}
                                        {item.type === 'file' && (
                                            <input
                                                id={`blueprint-source-input-${idx}`}
                                                ref={(el) => { fileInputRefs.current[item.path] = el; }}
                                                type="file"
                                                className="hidden"
                                                accept={getAcceptForPath(item.path)}
                                                onClick={(e) => e.stopPropagation()}
                                                onChange={(e) => handleFileSelected(item.path, e.target.files)}
                                            />
                                        )}
                                    </div>
                                ))}
                            </div>
                        )}

                        {/* COMPONENTS TAB */}
                        {activeTab === 'components' && (
                            <div className="space-y-3">
                                <h3 className="font-semibold text-slate-200 mb-4">Required & Optional Components</h3>
                                {selectedTemplate.components.map((comp, idx) => (
                                    <div key={idx} className={`bg-[#252526] border rounded p-3 ${comp.required ? 'border-red-700/50' : 'border-slate-700'}`}>
                                        <div className="flex items-start justify-between mb-2">
                                            <div>
                                                <div className="font-semibold text-slate-200 text-sm flex items-center gap-2">
                                                    {comp.name}
                                                    {comp.required && (
                                                        <span className="px-1.5 py-0.5 bg-red-900/40 text-red-300 text-[8px] font-bold rounded">REQUIRED</span>
                                                    )}
                                                </div>
                                                <div className="text-[10px] text-slate-500 font-mono">{comp.type}</div>
                                            </div>
                                        </div>
                                        <p className="text-[10px] text-slate-400">{comp.description}</p>
                                    </div>
                                ))}
                            </div>
                        )}

                        {/* DEPENDENCIES TAB */}
                        {activeTab === 'dependencies' && (
                            <div className="space-y-4">
                                <div>
                                    <h3 className="font-semibold text-slate-200 mb-4">Master Files & Dependencies</h3>
                                    <div className="space-y-2">
                                        {selectedTemplate.dependencies.length > 0 ? (
                                            selectedTemplate.dependencies.map((dep, idx) => (
                                                <div key={idx} className="bg-[#252526] border border-blue-700/50 rounded p-3">
                                                    <div className="flex items-center gap-2">
                                                        <Briefcase className="w-4 h-4 text-blue-400 shrink-0" />
                                                        <div>
                                                            <div className="font-semibold text-slate-200 text-sm">{dep}</div>
                                                            <div className="text-[10px] text-slate-500 mt-0.5">
                                                                {dep === 'Fallout4.esm' && 'Base game master file — required for all FO4 mods'}
                                                                {dep === 'DLCWorkshop01.esm' && 'Wasteland Workshop DLC master file'}
                                                                {dep === 'DLCWorkshop02.esm' && 'Contraptions Workshop DLC master file'}
                                                                {dep === 'DLCWorkshop03.esm' && 'Vault-Tec Workshop DLC master file'}
                                                                {dep.startsWith('(') && 'Variable — add the specific mod ESP/ESL this patch targets'}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            ))
                                        ) : (
                                            <div className="bg-[#252526] border border-emerald-700/40 rounded p-3 text-emerald-300 text-xs">
                                                No plugin master dependencies — this is a loose file replacer.
                                            </div>
                                        )}
                                    </div>
                                </div>

                                {/* Plugin type guidance */}
                                <div className="mt-4">
                                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Plugin Type Guidance</h4>
                                    <div className="space-y-2">
                                        <div className="bg-[#252526] border border-emerald-700/40 rounded p-3">
                                            <div className="text-xs font-bold text-emerald-300 mb-1">ESL (Light Plugin)</div>
                                            <p className="text-[10px] text-slate-400">≤2,048 new FormIDs (0x800–0xFFF). Does not consume an ESP slot in the 254-plugin limit. Ideal for small patches, weapon packs, texture mods with a plugin.</p>
                                        </div>
                                        <div className="bg-[#252526] border border-amber-700/40 rounded p-3">
                                            <div className="text-xs font-bold text-amber-300 mb-1">ESP (Standard Plugin)</div>
                                            <p className="text-[10px] text-slate-400">Up to 16 million FormIDs. Counts against the 254-plugin limit. Required for large quests, world expansions, and anything that adds many records.</p>
                                        </div>
                                        <div className="bg-[#252526] border border-blue-700/40 rounded p-3">
                                            <div className="text-xs font-bold text-blue-300 mb-1">ESL-Flagged ESP</div>
                                            <p className="text-[10px] text-slate-400">An ESP with the ESL flag set in xEdit. Acts like an ESL (no slot consumed) but can be opened in CK. Use when the file was built as an ESP but stays within 2047 new records.</p>
                                        </div>
                                    </div>
                                </div>

                                {/* Recommended Tools */}
                                <div className="mt-4">
                                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Recommended Tools</h4>
                                    <div className="space-y-1">
                                        {selectedTemplate.recommendedTools.map((tool, idx) => (
                                            <div key={idx} className="flex items-center gap-2 bg-[#252526] border border-slate-700 rounded px-3 py-2">
                                                <Cpu className="w-3 h-3 text-amber-400 shrink-0" />
                                                <span className="text-xs text-slate-300">{tool}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        )}

                        {/* CHECKLIST TAB */}
                        {activeTab === 'checklist' && (
                            <div className="space-y-3">
                                <div className="flex items-center justify-between mb-2">
                                    <h3 className="font-semibold text-slate-200 flex items-center gap-2">
                                        <ClipboardList className="w-4 h-4 text-amber-400" />
                                        Pre-Release Checklist
                                    </h3>
                                    <div className="flex items-center gap-2">
                                        <span className={`text-xs font-bold ${completedCount === selectedTemplate.checklist.length ? 'text-green-400' : 'text-amber-300'}`}>
                                            {completedCount}
                                        </span>
                                        <span className="text-xs text-slate-500">/{selectedTemplate.checklist.length}</span>
                                        <button
                                            onClick={exportChecklist}
                                            className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 border border-slate-700 text-[10px] font-semibold flex items-center gap-1.5 text-slate-300"
                                            title="Export checklist as Markdown"
                                        >
                                            <Download className="w-3 h-3" /> Export
                                        </button>
                                        <button
                                            onClick={resetChecklist}
                                            className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 border border-slate-700 text-[10px] font-semibold flex items-center gap-1.5 text-slate-400"
                                            title="Reset checklist for this template"
                                        >
                                            <RotateCcw className="w-3 h-3" />
                                        </button>
                                    </div>
                                </div>

                                {/* Progress bar */}
                                <div className="w-full h-1.5 bg-slate-800 rounded-full overflow-hidden mb-4">
                                    <div
                                        className="h-full bg-amber-400 rounded-full transition-all"
                                        style={{ width: `${selectedTemplate.checklist.length > 0 ? (completedCount / selectedTemplate.checklist.length) * 100 : 0}%` }}
                                    />
                                </div>

                                {selectedTemplate.checklist.map((item, idx) => {
                                    const key = checklistKey(selectedTemplate.id, idx);
                                    const checked = !!checkedItems[key];
                                    return (
                                        <div
                                            key={idx}
                                            onClick={() => toggleCheck(key)}
                                            className={`flex items-start gap-3 p-3 rounded border cursor-pointer transition-colors ${
                                                checked
                                                    ? 'bg-green-900/20 border-green-700/40'
                                                    : 'bg-[#252526] border-slate-700 hover:border-amber-500/40'
                                            }`}
                                        >
                                            <div className={`mt-0.5 w-4 h-4 rounded border-2 flex items-center justify-center shrink-0 transition-colors ${
                                                checked ? 'bg-green-500 border-green-500' : 'border-slate-500'
                                            }`}>
                                                {checked && <CheckCircle2 className="w-3 h-3 text-white" />}
                                            </div>
                                            <span className={`text-xs leading-relaxed ${checked ? 'text-slate-500 line-through' : 'text-slate-300'}`}>
                                                {item}
                                            </span>
                                        </div>
                                    );
                                })}

                                {completedCount === selectedTemplate.checklist.length && selectedTemplate.checklist.length > 0 && (
                                    <div className="mt-4 p-3 bg-green-900/20 border border-green-600/40 rounded text-center">
                                        <Shield className="w-5 h-5 text-green-400 mx-auto mb-1" />
                                        <p className="text-xs text-green-300 font-bold">All checks passed — ready to package!</p>
                                    </div>
                                )}
                            </div>
                        )}

                    </div>
                </div>
            </div>
        </div>
    );
};

export default TheBlueprint;
