#!/usr/bin/env python3
"""
check_parity.py — fails loudly when brain-b's two forked service files
(gemma_service_enhanced.py, the dev/GPU build, and nexus/brain_b_slim.py, the
shipped/CPU build) diverge in the pieces that are supposed to be identical.

Why this exists: the same divergence has happened three times.
  1. gemma_service_enhanced.py got a probe_k=30 retrieval fix that never
     reached brain_b_slim.py — the unfixed version shipped in a public
     GitHub Release for a full day before anyone noticed.
  2. retrieval_tuning.py's constants moved into a shared module specifically
     to fix #1 structurally — but brain-b/nexus/retrieval_tuning.py (a
     gitignored build artifact, regenerated by build_nexus_package.py on
     every real build) was found stale on disk anyway, because nothing
     forced the copy step to have actually run before the file was read.
  3. classify_mode() and its keyword-fallback siblings were extended with a
     scene_related flag by hand in both files, "kept byte-identical" purely
     by the author's own care — the exact arrangement that caused #1.

"Someone remembers to keep them in sync" has failed three times now — the
third time was an enumerated allowlist (SHARED_FUNCTIONS) that stayed silent
about a function nobody had added to it yet, the same failure shape as #1,
just relocated. So the actual check is INVERTED: every function name that
exists under the same name in BOTH files must be classified into exactly one
of SHARED_FUNCTIONS (must stay byte-identical) or ALLOWED_TO_DIFFER (a dict —
values are the reason it's expected to differ). A new same-named function
that isn't in either one fails CI and forces the decision, instead of quietly
joining "nobody's checking this" the way classify_mode's siblings did before
this script existed.

What this does NOT try to fix: classify_mode() calls _generate_json(), which
calls a locally-defined generate_answer() — genuinely different between the
two files (cloud-first-with-local-Unsloth-fallback vs. cloud-only, see each
file's own module docstring for why). That coupling is why these functions
are hand-duplicated instead of extracted into one shared module the way
retrieval_tuning.py's pure functions were — a real shared module would need
generate_answer() itself to be injected/parameterized, which is a larger
refactor than a parity check justifies on its own. If that refactor ever
happens, this script becomes unnecessary for whatever it covers.

Usage: python brain-b/check_parity.py
Exit 0 = every common function is classified and every SHARED_FUNCTIONS entry
matches. Exit 1 = an unclassified common function was found, a SHARED_FUNCTIONS
entry diverged (printed as a unified diff), or a build artifact is stale
relative to its source of truth.
"""
from __future__ import annotations

import ast
import difflib
import sys
from pathlib import Path

BRAIN_B_DIR = Path(__file__).resolve().parent
DEV_FILE = BRAIN_B_DIR / "gemma_service_enhanced.py"
NEXUS_FILE = BRAIN_B_DIR / "nexus" / "brain_b_slim.py"

# Functions that must be BYTE-IDENTICAL between the two service files.
SHARED_FUNCTIONS = [
    "_answer_level_prompt_fragment", "_build_bm25", "_build_knowledge_graph",
    "_citation_from_result", "_classify_mode_keywords", "_extract_json",
    "_generate_json", "_is_action_related_keywords", "_is_scene_related_keywords",
    "_is_app_help_keywords", "_is_game_data_related_keywords",
    "_is_conversational_keywords", "_is_ck_diagnosis_keywords", "_require_auth",
    "_split_identifier", "_tokenize",
    "auto_save_to_chroma", "classify_and_diagnose",
    "classify_mode", "compute_answer_level", "contract", "contract_fields", "diagnose",
    "enrich", "episodes_list", "expand_to_parent", "extract_skill_ids", "feedback",
    "generate_text_backend", "get_graph", "get_runtime_collection", "graph_expand",
    "init_db", "knowledge_add", "knowledge_count", "log_contract_failure",
    "log_learner_signal", "log_mode_classification", "log_retrieval", "reflect",
    "save_episode", "search_episodes", "suggest_next_skill",
    "update_learner_state", "web_search",
]

# Functions that exist under the SAME NAME in both files but are expected to
# differ — each needs a real reason, so the list documents itself rather than
# requiring archaeology later. This is the inverted half of the check: every
# name common to both files must appear in exactly one of SHARED_FUNCTIONS or
# this dict. A new same-named function landing in both files that isn't in
# either one fails CI instead of silently joining "different by default" —
# that silence is the exact failure shape this script exists to close.
ALLOWED_TO_DIFFER = {
    "embed": "fastembed/ONNX (nexus, CPU) vs sentence-transformers (dev, GPU) — "
             "different embedding backends, see each file's own comment on embed().",
    "generate_answer": "cloud-with-local-Unsloth-fallback (dev) vs cloud-only, no local "
                        "model at all (nexus) — see generate_answer()'s own docstring.",
    "get_curated_collection": "passes embed_fn=embed (nexus, fastembed) vs an "
                               "EMBEDDING_MODEL_NAME check (dev, sentence-transformers) "
                               "into knowledge_manifest.check_embedding_model — follows "
                               "directly from the embed() split above.",
    "get_embed_model": "loads fastembed (nexus, CPU, no torch dependency) vs "
                        "sentence-transformers on a second CUDA device when available "
                        "(dev) — see get_embed_model()'s own docstring for why fastembed "
                        "was chosen for the shipped build specifically.",
    "health": "reports GPU/model-loaded state (dev) vs edition/backend-configured state "
              "(nexus) — intentionally different response shapes for two different "
              "runtime pictures, both read by BrainBSettings.tsx.",
    "hybrid_retrieve": "same retrieval logic, but the module docstring differs — dev's "
                        "notes a margin-based signal as a future gating candidate, "
                        "nexus's is trimmed. Functional bodies match; only the comment "
                        "differs. If this ever shows a REAL logic diff, escalate — this "
                        "entry assumes comment-only drift, not correctness drift.",
    "infer": "the /infer Flask route itself — dev branches on use_langgraph (LangGraph "
              "workflow vs _simple_infer), nexus always calls infer_answer() since it has "
              "no LangGraph dependency at all. The parts that ARE meant to stay identical "
              "within this route (classify_mode call, abstention gate, get_context "
              "handling) are covered by the SHARED_FUNCTIONS they call into instead.",
}

# Files that must match their source of truth WHEN PRESENT on disk — exact
# text comparison, not the AST-based per-function check SHARED_FUNCTIONS
# does, because these aren't expected to have ANY legitimate per-fork
# differences (unlike the two brain_b_slim.py forks, which do).
#
# nexus/retrieval_tuning.py is gitignored (regenerated by
# build_nexus_package.py's step 0 on every real build), so it usually won't
# exist in a fresh CI checkout — that's fine, this check just skips it then.
# It exists as a local-dev safety net: if you've built once and the source
# has since moved on, this catches it before you notice the hard way.
#
# nexus/game_data_index.py is NOT gitignored — both copies are committed and
# hand-maintained (no build step regenerates it), so this pair exists purely
# to catch someone editing one copy and forgetting the other.
ARTIFACT_PAIRS = [
    (BRAIN_B_DIR / "retrieval_tuning.py", BRAIN_B_DIR / "nexus" / "retrieval_tuning.py"),
    (BRAIN_B_DIR / "game_data_index.py", BRAIN_B_DIR / "nexus" / "game_data_index.py"),
]


def top_level_function_names(file_path: Path) -> set[str]:
    tree = ast.parse(file_path.read_text(encoding="utf-8"), filename=str(file_path))
    return {n.name for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))}


def extract_function_source(file_path: Path, func_name: str) -> str | None:
    """Returns the exact source text of a top-level function definition, or
    None if it doesn't exist. Uses ast, not regex, so it's exact regardless
    of what follows the function (another def, a comment block, EOF)."""
    source = file_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(file_path))
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name == func_name:
            return ast.get_source_segment(source, node)
    return None


def diff(a: str, b: str, label_a: str, label_b: str) -> str:
    return "".join(difflib.unified_diff(
        a.splitlines(keepends=True), b.splitlines(keepends=True),
        fromfile=label_a, tofile=label_b,
    ))


def main() -> int:
    failures: list[str] = []

    if not DEV_FILE.exists() or not NEXUS_FILE.exists():
        print(f"FATAL: expected both {DEV_FILE} and {NEXUS_FILE} to exist.")
        return 1

    # Inverted check, run FIRST: every function name common to both files must
    # be classified into exactly one of SHARED_FUNCTIONS or ALLOWED_TO_DIFFER.
    # This is what makes the guard self-maintaining — a new same-named function
    # landing in both files fails CI immediately instead of silently defaulting
    # to "nobody checks this one," which is the actual failure shape that let
    # classify_mode's scene_related addition ship as hand-duplicated code with
    # no guard at all until this script existed.
    common_names = top_level_function_names(DEV_FILE) & top_level_function_names(NEXUS_FILE)
    classified = set(SHARED_FUNCTIONS) | set(ALLOWED_TO_DIFFER)
    unclassified = sorted(common_names - classified)
    if unclassified:
        failures.append(
            "New function(s) with the same name exist in BOTH files but aren't classified "
            "in check_parity.py yet:\n  " + "\n  ".join(unclassified) +
            "\n\nAdd each to SHARED_FUNCTIONS (if it must stay byte-identical) or to "
            "ALLOWED_TO_DIFFER (with a real reason, if it's intentionally different)."
        )
    stale_entries = sorted(classified - common_names)
    if stale_entries:
        print(f"NOTE: these classified names no longer exist in both files (harmless, but "
              f"worth pruning from check_parity.py): {stale_entries}")

    for func_name in SHARED_FUNCTIONS:
        dev_src = extract_function_source(DEV_FILE, func_name)
        nexus_src = extract_function_source(NEXUS_FILE, func_name)

        if dev_src is None and nexus_src is None:
            failures.append(
                f"'{func_name}' is missing from BOTH files — remove it from "
                f"SHARED_FUNCTIONS if it was deliberately deleted, or restore it."
            )
            continue
        if dev_src is None:
            failures.append(f"'{func_name}' exists in {NEXUS_FILE.name} but not in {DEV_FILE.name}.")
            continue
        if nexus_src is None:
            failures.append(f"'{func_name}' exists in {DEV_FILE.name} but not in {NEXUS_FILE.name}.")
            continue

        if dev_src != nexus_src:
            failures.append(
                f"'{func_name}' has diverged between {DEV_FILE.name} and {NEXUS_FILE.name}:\n"
                + diff(dev_src, nexus_src, f"{DEV_FILE.name}:{func_name}", f"{NEXUS_FILE.name}:{func_name}")
            )

    for source_of_truth, artifact in ARTIFACT_PAIRS:
        if not artifact.exists():
            print(f"SKIP: {artifact} not present (expected — gitignored build artifact).")
            continue
        a_text = source_of_truth.read_text(encoding="utf-8")
        b_text = artifact.read_text(encoding="utf-8")
        if a_text != b_text:
            failures.append(
                f"{artifact} is STALE relative to its source of truth {source_of_truth}.\n"
                f"Fix: re-run the copy step in build_nexus_package.py, or just:\n"
                f"  cp {source_of_truth} {artifact}\n"
                + diff(a_text, b_text, str(source_of_truth), str(artifact))
            )

    if failures:
        print(f"\n{'=' * 70}\nFORK PARITY CHECK FAILED — {len(failures)} issue(s)\n{'=' * 70}\n")
        for f in failures:
            print(f)
            print()
        return 1

    print(f"OK — {len(SHARED_FUNCTIONS)} shared function(s) identical, "
          f"{len(ARTIFACT_PAIRS)} artifact pair(s) checked (skipped if absent).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
