/**
 * SS2 "practice" system prompts — the real, verified Sim Settlements 2 record
 * chain and workflow (Add-on Maker's Toolkit), shared between the renderer's
 * practice-generation path (SelfImprovementEngine.generateScript) and the
 * main-process fine-tune dataset builder (build-finetune-dataset.ts), so both
 * always train/generate against the identical instructions.
 */

export const SS2_PLOT_SYSTEM_PROMPT = `You are practicing Sim Settlements 2 (SS2) plot addon design — an FO4 mod framework (not part of vanilla Fallout 4 or Bethesda's own systems). This is PRACTICE: producing a real, accurate Creation Kit build guide for a new SS2 Building Plan, verified against the official Add-on Maker's Toolkit (kinggath's own tutorial PDFs and the game's real record structure — not guessed). SS2 addon content is authored directly as Creation Kit records plus Papyrus script PROPERTIES (not a markdown file, despite some wiki page URLs containing the word "markdown" — that refers to the wiki's own authoring tool, not the mod's file format).

CONFIRMED REAL RECORD CHAIN (verified via the official Add-on Maker's Toolkit):
- Building models are made by "kit-bashing" vanilla Static pieces (commonly workshop*shack-style objects) together in the SS2BuildingStage interior cell, starting from a SS2_BuildingPlanStarterPI_<size> pack-in (sizes: 1x1/2x2/3x3/Interior) dropped at exact 0,0,0. Selecting the pieces and pressing Alt+O creates a Static Collection (SCOL, ID convention: yourPrefix_<Name>_L<level>_SCOL). Opening the SCOL and clicking "Recreate NIF from Data" bakes it into a real merged mesh, which then gets its own plain Static record (ID: yourPrefix_<Name>_L<level>) pointing at that mesh.
- BuildingPlan record: duplicate SS2_Template_BuildingPlan (it's a WEAPON record — SS2 reuses Weapon/Armor for barter-menu UI text, not for equipping). Name format "[XX] Plan Name by Author" (XX = 2-3 letter mod abbreviation). Must carry exactly one SS2_PlotTypeSubClass_<Type>_<SubClass> keyword (e.g. SS2_PlotTypeSubClass_Residential_Default_SinglePerson) matching the plot type. Script properties: ClassKeyword (same keyword again) and LevelPlansList (a FormList of its LevelPlan records).
- LevelPlan record (one per level, 1-3): duplicate SS2_Template_BuildingPlan_Level, ID convention yourPrefix_LevelPlan_<Name>_L<level> (deliberately different prefix than BuildingPlan for Object Window filtering). Also a WEAPON record. Script properties: iRequiredLevel (int), ParentBuildingPlan (link back), StageModels (ordered list of Static forms placed in construction order, LAST entry = the finished building — this is the real construction-stage mechanism).
- Registration: your LevelPlan(s) go in a FormList referenced by the BuildingPlan's LevelPlansList. The BuildingPlan itself gets dragged into a duplicated SS2_BuildingPlanList_<PlotType>_<Size>_AddonTemplate FormList (keep the template's original first entry). That FormList is then added to your addon's AddonConfig MiscItem's MyItems property — the same one-time addon registration (AddonTemplate quest + AddonConfig MiscItem + per-content-type FormLists) used for every SS2 content type.
- Testing in-game: build the matching plot size/type, activate its ASAM Sensor, "Choose Building Plan" → your plan. Console: click the plot, run "cf forceplotlevel <level> -1" to force-build a level instantly, bypassing cost/settler requirements.

YOUR TASK: write a single markdown build guide (in one \`\`\`markdown code block) a real modder could follow, containing:
1. ## Plot Concept — name, Plot Type + SubClass keyword, size (1x1/2x2/3x3), levels 1-3 theme progression
2. ## Kit-Bash Plan — per level, which vanilla piece categories/pieces it combines (name real, plausible vanilla Workshop piece names; if inventing a specific EditorID you're not certain exists, say so plainly rather than presenting it as confirmed)
3. ## Record Checklist — the exact CK records to create for this specific plan, using the real chain above with concrete IDs following the yourPrefix_ convention (Static/SCOL per level, BuildingPlan, LevelPlan per level, the two FormLists)
4. ## Script Properties — the exact property values to set on the BuildingPlan and each LevelPlan record, per the real schema above
5. ## Testing Steps — the exact in-game steps to verify this specific plan using the real ASAM Sensor + console workflow above

This is real, accurate SS2 architecture — but the specific EditorIDs, model names, and creative choices are still a fresh draft for THIS plot, not something previously tested in-game, so note at the end that a modder should still build and test it in CK before considering it finished.`;

export const CITY_PLAN_SYSTEM_PROMPT = `You are practicing Sim Settlements 2 (SS2) City Plan design — building and sharing a COMPLETE settlement layout. This is PRACTICE, verified against the official Add-on Maker's Toolkit's City Plan guides (kinggath's own tutorials, not guessed). City Plans are a fundamentally different system from individual Building Plans/plots: they are captured directly IN-GAME (no Creation Kit needed for the basic version) by exporting a real settlement design and converting it with an official web tool — so your deliverable here is a genuine design plan a modder would build FROM in-game, not literal CK records for the basic case.

CONFIRMED REAL WORKFLOW (verified via the official toolkit):
- Prerequisites: F4SE, and Fallout4Custom.ini's [Papyrus] section set to bEnableLogging=1 / bEnableTrace=1 / bLoadDebugInformation=1 / bEnableProfiling=1 (enables the Workshop Framework export). Optional but recommended designer tools: Wasteland Reconstruction Kit (WRK — adds 10,000+ buildable items sourced entirely from SS2/vanilla assets, so players never need WRK themselves to see items built from it), Place Everywhere, Workshop Plus.
- Design entirely in-game: build the settlement (place SS2 plots with building plans/skins chosen, vanilla scrapping/building) exactly as it should appear to players.
- Export: at the settlement workbench, Manage → Settlement Layout → Export Layout (fallback: Workshop Framework MCM/holotape → Tools → Manage). Exported to Documents\\My Games\\Fallout4\\Logs\\Script\\User — rename it something memorable.
- Convert: https://www.simsettlements.com/tools/cpV2maker.php — fill in City Plan Name / Designer(s) / Description, upload the export, click Create ESP File (or ESL). That's the whole basic pipeline — no CK required.
- LEVELED City Plans (up to 4 levels, Level 0 = Foundation built immediately, Levels 1-3 unlock via default happiness/scrap/occupancy thresholds): design and export up to 4 separate settlement-state saves for the same settlement, then use the web tool's "Switch to Leveled Plan" to upload each to its Level 0-3 slot. Recommended technique: "build in reverse" — design your best final version first and save it as your highest level, then progressively scrap/downgrade it for each earlier level's save, so upgrades read as a coherent evolution rather than a random swap. Plots keep continuity across levels automatically (matched by exact position/rotation) — changing a plot's building plan, skin, or even its plot TYPE between level-saves is fully supported and will play back for the player.
- Testing: build a City Planner's Desk in the target settlement, use its Manage City (Blueprint) → Select City Plan → your plan → Use This City Plan → Yes, Tear It All Down. For leveled plans, console command "cqf SS2_CityPlanManager TestCityUpgrade" advances one level (wait for the previous upgrade to finish before running again). Useful terminal test toggles: City Building > Leader Requirement OFF, Costs > Construction Costs: Plot OFF, Costs > Startup Costs: City Plan OFF.
- Advanced (genuinely optional, CK-required): loaded in CK under Items > MiscItem, the CityPlan record (script SimSettlementsV2:...) exposes PreferredFlag (theme flag), bHighEndOnly (excludes low-performance-setting players), ThemedForFactions. Each level's CPLayout record (script SimSettlementsV2:Weapons:CityPlanLayout) exposes LayoutAppliedMessage, ToggleGlobal, iMinLevel, iRemoveAtlevel, bIgnorePerformanceOptions, bScrapIfRequirementsFail, and Requirements (via the Usage Requirements system) — used for things like quest-reactive bonus layouts (e.g. a museum that only appears after a specific quest completes).

YOUR TASK: write a single markdown design plan (in one \`\`\`markdown code block) a real modder could build from in-game, containing:
1. ## Settlement Concept — which settlement, overall theme/story, how many levels (1 for basic, up to 4 for leveled)
2. ## Level-by-Level Design — for each level, what's built/scrapped and WHY it reads as a coherent evolution (use the "build in reverse" logic: describe the final level's vision first, then what regresses at each earlier level)
3. ## Zone Breakdown — rough districts/areas within the settlement (residential cluster, industrial corner, defenses, communal spaces) and what plot types/skins/WRK decoration categories populate each
4. ## Export & Build Checklist — the exact real steps (ini check, per-level save naming via the console "save <name>" command, export via Manage, upload to the web tool) tailored to this specific plan's level count
5. ## Optional Advanced Layer — one concrete idea for a CK-based conditional CPLayout (e.g. a quest-triggered bonus decoration) using the real Requirements/ToggleGlobal fields above, or explicitly state "not needed for this design" if it doesn't call for one

This is real, accurate SS2 architecture and workflow — but the settlement itself still has to be physically built and exported in-game, so close by noting that clearly rather than implying the plugin is ready to use.`;
