"""
fo4_lod_generator.py
====================
Automatic LOD mesh generation and high-to-low poly texture baking for FO4.

LOD system
----------
FO4 uses separate NIF files for each LOD level, referenced by the ESP/ESM:
  LOD0 (full detail):   up to 65,535 triangles
  LOD1 (medium):        ~25–35% of LOD0 triangles
  LOD2 (far):           ~10–15% of LOD0 triangles
  LOD3 (very far):      ~3–5%   of LOD0 triangles

NIF naming convention for LODs (mod-folder relative -- no "Data\" wrapper,
since mod_folder IS the MO2 mod folder that already holds
Meshes/Materials/Textures directly). Verified directly against a real
game-exported reference folder (F:\FO4 WORKING FLODER), e.g.
Meshes/LOD/Landscape/Trees/Maple/TreeMapleForest01_LOD_0/1/2/3.nif:
  Meshes/[path]/[name].nif               (LOD0, full quality — used in-game close-up)
  Meshes/LOD/[path]/[name]_LOD_0.nif     (LOD1, medium distance)
  Meshes/LOD/[path]/[name]_LOD_1.nif     (LOD2, far)
  Meshes/LOD/[path]/[name]_LOD_2.nif     (LOD3, very far)

The real suffix is "_LOD_<n>" with an underscore before a ZERO-BASED index
-- NOT "_lod1"/"_lod2"/"_lod3" (this module's own LOD1/LOD2/LOD3 internal
naming is one-based, so the exported suffix index is level-number minus 1).
Some simpler assets (building-kit pieces, etc.) only ever get a single swap
and use a plain "_LOD.nif" suffix with no index at all -- not currently
generated by this module, which always produces the full LOD1/2/3 chain.

The farthest billboard/flat-card level uses its own separate convention: a
"_LOD_FLAT.nif" suffix, sitting in the SAME folder as the LOD0 source mesh
(NOT under Meshes/LOD/) -- e.g. Meshes/Landscape/Trees/TreeMapleForest01_LOD_FLAT.nif.
generate_billboard_lod() below builds this shape but is not currently wired
into FO4_OT_GenerateLODs's execute() -- there is no UI path that calls it.

LOD1/2/3 NIFs, their downscaled textures, and their .bgsm materials all live
under a shared "LOD" subfolder mirrored across Meshes/, Textures/, and
Materials/ (Meshes/LOD/…, Textures/LOD/…, Materials/LOD/…) — confirmed
against a real mod's on-disk layout. Only LOD0 (the full-detail mesh, not
generated by this module) stays in the plain, non-LOD path.

For carnivorous plants: the LOD meshes typically have the jaws merged/simplified
and leaf bones removed (leaves become vertex-color alpha fade).

Texture baking
--------------
High-to-low poly baking workflow:
  1. High-poly mesh: sculpted detail, many polygons
  2. Low-poly mesh: game-ready, ~10–30k tris
  3. Bake: normal map, AO, curvature from high → low
  4. Result: low-poly mesh looks as detailed as high-poly in-game

Baked maps:
  Normal (tangent-space) → _n.dds
  AO (ambient occlusion) → multiplied onto _d.dds or stored in _s.dds R channel
  Cavity / curvature     → multiplied onto _d.dds for contact shadow detail

FO4 bake settings:
  Normal map: tangent-space, OpenGL convention (for use with UE5 converter)
              OR DirectX convention (native FO4) — depends on source
  Ray distance: 0.05–0.1 FO4 units for most props
  Margin: 4–8 px per 1K texture
"""

from __future__ import annotations

import os
import re
import traceback

try:
    import bpy
    from bpy.types import Operator
    from bpy.props import (
        StringProperty, BoolProperty, FloatProperty,
        EnumProperty, IntProperty, FloatVectorProperty,
    )
except ImportError:
    bpy      = None  # type: ignore[assignment]
    Operator = object  # type: ignore[assignment]

# FO4 LOD triangle budgets (ratio of LOD0 triangle count)
_LOD_RATIOS = {
    "LOD0": 1.00,
    "LOD1": 0.30,
    "LOD2": 0.12,
    "LOD3": 0.08,
}

# FO4 recommended max triangles per LOD level
_LOD_MAX_TRIS = {
    "LOD0": 65535,
    "LOD1": 8000,
    "LOD2": 3000,
    "LOD3": 1000,
}


# ── LOD helpers ───────────────────────────────────────────────────────────────

def generate_lod_mesh(source_obj, ratio: float, lod_name: str) -> "tuple[object, str]":
    """
    Create a decimated copy of *source_obj* as a new object.

    Parameters
    ----------
    source_obj : Source Blender mesh object.
    ratio      : Decimate ratio (0.0–1.0, where 1.0 = original).
    lod_name   : Name for the new LOD object.

    Returns (new_obj, message).
    """
    # Duplicate
    new_mesh = source_obj.data.copy()
    new_obj  = source_obj.copy()
    new_obj.data = new_mesh
    new_obj.name = lod_name
    new_mesh.name = lod_name
    bpy.context.collection.objects.link(new_obj)

    # Explicitly carry material slots from source (handles both DATA- and
    # OBJECT-linked slots; ensures PyNifly-imported textures travel with the LOD)
    new_obj.data.materials.clear()
    for slot in source_obj.material_slots:
        new_obj.data.materials.append(slot.material)

    # Strip shape keys before decimating — Blender refuses to apply any
    # modifier to a mesh that has shape keys (RuntimeError).  LOD copies never
    # need shape keys (they are distance-based mesh replacements, not morphs).
    bpy.context.view_layer.objects.active = new_obj
    new_obj.select_set(True)
    if new_obj.data.shape_keys:
        try:
            bpy.ops.object.shape_key_remove(all=True)
        except Exception:
            pass

    # Apply decimate modifier
    mod = new_obj.modifiers.new("FO4_LOD_Decimate", 'DECIMATE')
    mod.decimate_type = 'COLLAPSE'
    mod.ratio = max(0.001, min(1.0, ratio))
    # use_collapse_triangulate=True forces triangulation before edge collapse,
    # which destroys quad flow on organic/plant meshes — leave it False.
    mod.use_collapse_triangulate = False
    mod.use_symmetry = False

    # Apply modifier. Check the result -- an unchecked CANCELLED here (e.g.
    # new_obj somehow isn't the active/context object at call time) would
    # leave the Decimate modifier un-applied while every triangle-count/
    # loose-vertex cleanup step below silently keeps running against the
    # full, un-decimated mesh and reports it as a successful LOD.
    bpy.context.view_layer.objects.active = new_obj
    _apply_result = bpy.ops.object.modifier_apply(modifier=mod.name)
    if 'FINISHED' not in _apply_result:
        print(f"[FO4 Add-on] LOD decimate modifier_apply did not finish for "
              f"'{new_obj.name}': {_apply_result} -- LOD mesh may still be at full density")

    # Decimate's COLLAPSE algorithm can strand vertices whose surrounding
    # faces all collapsed away without cleaning up the vertex itself --
    # worse at aggressive ratios (low LOD levels). Confirmed on a real asset:
    # loose-vertex count climbed with each more-aggressive LOD, visible as
    # holes/gaps in the mesh and propagating into any collision hull built
    # from it. Strip them here so every consumer of this LOD gets clean data.
    import bmesh as _bmesh
    _loose_bm = _bmesh.new()
    _loose_bm.from_mesh(new_obj.data)
    _loose_verts = [v for v in _loose_bm.verts if not v.link_faces]
    if _loose_verts:
        _bmesh.ops.delete(_loose_bm, geom=_loose_verts, context='VERTS')
        _loose_bm.to_mesh(new_obj.data)
        new_obj.data.update()
    _loose_bm.free()

    n_tris = sum(len(p.loop_indices) - 2 for p in new_obj.data.polygons)
    msg = (
        f"LOD '{lod_name}': {n_tris} triangles "
        f"({ratio*100:.0f}% of original)"
    )
    return new_obj, msg


# ── Texture baking setup ──────────────────────────────────────────────────────

def _create_bake_image(name: str, width: int, height: int,
                        is_data: bool = True) -> "bpy.types.Image":
    """Create (or reuse) a Blender image for baking."""
    if name in bpy.data.images:
        img = bpy.data.images[name]
        if img.size[0] != width or img.size[1] != height:
            img.scale(width, height)
        return img
    img = bpy.data.images.new(name, width=width, height=height, alpha=False)
    img.colorspace_settings.name = 'Non-Color' if is_data else 'sRGB'
    img.file_format = 'PNG'
    return img


def setup_bake_target_node(mat, img) -> None:
    """Add/select a TEX_IMAGE node in *mat* pointing at *img* for baking."""
    mat.use_nodes = True
    # Find or create the bake target node
    bake_node = mat.node_tree.nodes.get("FO4_BakeTarget")
    if not bake_node:
        bake_node = mat.node_tree.nodes.new('ShaderNodeTexImage')
        bake_node.name  = "FO4_BakeTarget"
        bake_node.label = "FO4 Bake Target"
        bake_node.location = (300, -400)
    bake_node.image = img
    # Select it (Blender bakes to the active/selected image node)
    mat.node_tree.nodes.active = bake_node


def prepare_normal_bake(low_obj, high_obj, tex_size: int = 2048,
                         ray_dist: float = 0.05) -> tuple:
    """
    Set up the scene for a high-to-low normal map bake.

    Selects high_obj + low_obj, configures Cycles bake settings.
    Returns (bake_image, message).

    The caller must then call bpy.ops.object.bake(type='NORMAL') to run it.
    """
    bpy.context.scene.render.engine = 'CYCLES'
    bpy.context.scene.cycles.bake_type = 'NORMAL'
    bpy.context.scene.render.bake.use_selected_to_active = True
    bpy.context.scene.render.bake.use_cage = True
    bpy.context.scene.render.bake.cage_extrusion = ray_dist
    bpy.context.scene.render.bake.normal_space = 'TANGENT'
    bpy.context.scene.render.bake.margin = max(4, tex_size // 256)

    img_name = f"{low_obj.name}_n_BAKED"
    bake_img = _create_bake_image(img_name, tex_size, tex_size, is_data=True)

    # Set bake target on every material of the low-poly
    for slot in low_obj.material_slots:
        if slot.material:
            setup_bake_target_node(slot.material, bake_img)

    # Select: high (active source), low (selected target)
    bpy.ops.object.select_all(action='DESELECT')
    high_obj.select_set(True)
    low_obj.select_set(True)
    bpy.context.view_layer.objects.active = low_obj  # bake TARGET = active

    return bake_img, (
        f"Normal bake ready: {img_name} ({tex_size}×{tex_size}px). "
        f"Ray distance: {ray_dist}. "
        "Click 'Bake' in Render Properties, then save the image."
    )


def prepare_ao_bake(low_obj, tex_size: int = 2048) -> tuple:
    """Set up scene for ambient occlusion bake on low_obj."""
    bpy.context.scene.render.engine = 'CYCLES'
    bpy.context.scene.cycles.bake_type = 'AO'
    bpy.context.scene.render.bake.use_selected_to_active = False
    bpy.context.scene.render.bake.margin = max(4, tex_size // 256)

    img_name = f"{low_obj.name}_ao_BAKED"
    bake_img = _create_bake_image(img_name, tex_size, tex_size, is_data=True)

    for slot in low_obj.material_slots:
        if slot.material:
            setup_bake_target_node(slot.material, bake_img)

    bpy.ops.object.select_all(action='DESELECT')
    low_obj.select_set(True)
    bpy.context.view_layer.objects.active = low_obj

    return bake_img, (
        f"AO bake ready: {img_name} ({tex_size}×{tex_size}px). "
        "Click 'Bake' in Render Properties → Ambient Occlusion."
    )


# ── LOD texture downscaling (match real FO4's smaller LOD-specific textures) ──
# Real FO4 assets use dedicated, much smaller textures for their real-mesh LOD
# levels — e.g. vanilla BlastedForestBurntTreeUpright01's LOD1 references a
# small shared 'LOD/Trees/BlastedForestTrunksLOD_d.dds' atlas, not its full
# resolution hero texture, and only the farthest billboard level gets its own
# separate (also small) texture. Until this was added, every LOD generated by
# this add-on only decimated geometry and left the LOD pointing at the exact
# same full-resolution material as the source — the in-game LOD saved
# triangle/vertex cost but NONE of the texture memory/bandwidth cost LODs are
# also meant to save.

def _nearest_pow2(n: int) -> int:
    """Round n to the nearest power of two (minimum 64 — FO4's smallest
    common texture size). FO4/DDS textures are conventionally power-of-two."""
    n = max(64, int(n))
    lower = 1 << (n.bit_length() - 1)
    upper = lower << 1
    return upper if (n - lower) > (upper - n) else lower


def _lod_texture_output_dir(src_path: str, out_subdir: str = "LOD") -> str:
    """Directory to write a downscaled LOD texture into, mirroring real FO4's
    ``Textures\\LOD\\...`` convention (see the vanilla
    ``LOD/Trees/BlastedForestTrunksLOD_d.dds`` reference in the comment
    above) -- confirmed as a real bug: this used to be
    ``os.path.join(os.path.dirname(src_path), out_subdir)``, which drops a
    ``LOD`` folder next to wherever the source texture happens to live (e.g.
    ``.../Textures/Architecture/SomeBuilding/LOD/``). FO4 and every real mod
    instead keeps ONE ``LOD`` folder directly under the mod's ``Textures``
    root and mirrors the rest of the source's subpath underneath it (e.g.
    ``.../Textures/LOD/Architecture/SomeBuilding/``) -- that's also where
    Creation Kit and the game engine actually look for object-LOD textures,
    so the old layout produced files nothing in the pipeline would find.

    Finds the last path segment named exactly "textures" (case-insensitive,
    since Windows/MO2 paths are case-insensitive) and rebuilds the LOD
    output path relative to that root. Falls back to the old
    dirname-adjacent behaviour only if no "Textures" segment is found (e.g.
    a texture loaded from somewhere outside any recognizable mod/game
    folder structure), since there's nothing better to anchor to there.
    """
    norm = os.path.normpath(src_path)
    parts = norm.split(os.sep)
    tex_idx = next(
        (i for i in range(len(parts) - 1, -1, -1) if parts[i].lower() == "textures"),
        None,
    )
    if tex_idx is None:
        return os.path.join(os.path.dirname(src_path), out_subdir)

    textures_root = os.sep.join(parts[:tex_idx + 1])
    rel_parts = [p for p in parts[tex_idx + 1:-1] if p]  # everything between Textures/ and the filename
    # Re-running LOD generation on the same object reuses its material, whose
    # texture node by then already points at THIS function's own previous
    # output (e.g. ".../Textures/LOD/Landscape/Plants/x.png") -- using that
    # as the next call's src_path re-derives a rel_subdir that already
    # starts with "LOD" and inserting out_subdir again nests it one folder
    # deeper every re-run (.../Textures/LOD/LOD/..., then LOD/LOD/LOD/...).
    # Confirmed directly from a real exported NIF referencing
    # "textures\lod\lod\gsfungusgroup02bramble01_d.dds". Strip any leading
    # out_subdir segment(s) already present before adding this call's own.
    while rel_parts and rel_parts[0].lower() == out_subdir.lower():
        rel_parts.pop(0)
    rel_subdir = os.sep.join(rel_parts)
    return os.path.join(textures_root, out_subdir, rel_subdir) if rel_subdir else os.path.join(textures_root, out_subdir)


def create_lod_textures(lod_objects: list, scale_factor: float = 0.25,
                         out_subdir: str = "LOD") -> tuple:
    """Give every object in *lod_objects* a shared, downscaled copy of the
    source's textures instead of the full-resolution original.

    Every object in *lod_objects* gets the SAME downscaled image per unique
    source texture — matching real FO4 LOD atlases, which are shared across
    every real-mesh LOD level of an asset (only the farthest billboard level
    gets its own separate texture, handled separately by
    :func:`generate_billboard_lod`). The first LOD object whose texture node
    references a given source file creates the downscaled image/file; every
    later object referencing that same source file reuses it, so this never
    saves more than one new file per original texture no matter how many LOD
    levels are passed in.

    Each object's material is made single-user first, so downscaling a LOD's
    textures never touches the source mesh's own (still full-resolution)
    material — ``duplicate()``/``generate_lod_mesh`` share the source's
    material by default until something makes it single-user.

    Saved as PNG (not DDS) deliberately: export_textures_for_object /
    write_bgsm's existing texture-export pipeline already converts any
    non-DDS source to DDS via texconv/NVTT at actual export time, so this
    does not need its own separate DDS-conversion path or texconv
    configuration to be useful immediately after generation.

    Returns (bool success, str message).
    """
    if not lod_objects:
        return False, "No LOD objects provided"

    shared_cache: dict = {}
    processed = 0
    skipped = []

    for lod_obj in lod_objects:
        if lod_obj is None or lod_obj.type != 'MESH' or not lod_obj.data.materials:
            continue
        for slot in lod_obj.material_slots:
            mat = slot.material
            if mat is None or not getattr(mat, "use_nodes", False):
                continue
            if mat.users > 1:
                mat = mat.copy()
                slot.material = mat

            for node in mat.node_tree.nodes:
                if node.type != 'TEX_IMAGE' or not node.image:
                    continue
                img = node.image

                # Re-running LOD generation on an object whose material was
                # already downscaled by a previous run used to treat that
                # already-small LOD image as a fresh "source" and downscale
                # it AGAIN -- compounding quality loss on every re-run (this
                # is the same root cause behind an earlier real incident: a
                # mod-wide batch of ~1,268 degraded 64x64 textures from
                # repeated LOD generation attempts). Images this function
                # itself created are tagged fo4_lod_generated=True; skip
                # touching them further -- they're already the right size.
                if img.get("fo4_lod_generated"):
                    key = os.path.normcase(os.path.normpath(
                        bpy.path.abspath(img.filepath))) if img.filepath else img.name
                    shared_cache.setdefault(key, img)
                    node.image = img
                    processed += 1
                    continue

                try:
                    src_path = bpy.path.abspath(img.filepath) if img.filepath else ""
                except Exception:
                    src_path = ""
                if not src_path or not os.path.isfile(src_path):
                    skipped.append(f"'{node.name}' on '{lod_obj.name}': no source file on disk")
                    continue

                key = os.path.normcase(os.path.normpath(src_path))
                if key in shared_cache:
                    node.image = shared_cache[key]
                    processed += 1
                    continue

                # Force a reload before trusting img.size -- a newly-linked or
                # not-yet-fully-loaded Blender Image can report a stale/
                # placeholder size (much smaller than the real file) until
                # something forces it to actually read pixel data. Trusting
                # that stale size here used to silently bake a tiny (as low
                # as the 64x64 floor) LOD texture from a real 4096x4096
                # source -- confirmed as a real bug from a user report: the
                # resulting texture was so small it read as a flat white
                # blob in-game instead of the actual image.
                try:
                    img.reload()
                except Exception:
                    pass

                src_w, src_h = img.size[0], img.size[1]
                if src_w <= 0 or src_h <= 0:
                    skipped.append(
                        f"'{node.name}' on '{lod_obj.name}': image '{img.name}' "
                        f"reports {src_w}x{src_h} even after reload -- skipped "
                        "rather than risk baking a broken LOD texture"
                    )
                    continue

                new_w = _nearest_pow2(src_w * scale_factor)
                new_h = _nearest_pow2(src_h * scale_factor)
                if new_w >= src_w and new_h >= src_h:
                    shared_cache[key] = img  # already small enough — share as-is
                    node.image = img
                    processed += 1
                    continue

                stem = os.path.splitext(os.path.basename(src_path))[0]
                new_img = img.copy()
                new_img.name = f"{stem}_LOD"
                new_img.scale(new_w, new_h)

                out_dir = _lod_texture_output_dir(src_path, out_subdir)
                os.makedirs(out_dir, exist_ok=True)
                out_path = os.path.join(out_dir, f"{stem}.png")
                new_img.filepath_raw = out_path
                new_img.file_format = 'PNG'
                new_img.save()
                # Mark this image as an addon-generated LOD texture so a
                # future re-run treats it as already-downscaled instead of
                # downscaling it again (see the fo4_lod_generated check
                # above this loop).
                new_img["fo4_lod_generated"] = True

                shared_cache[key] = new_img
                node.image = new_img
                processed += 1

    if processed == 0:
        msg = "No texture nodes with a source file found to downscale"
        if skipped:
            msg += " (" + "; ".join(skipped) + ")"
        return False, msg
    return True, (
        f"{len(shared_cache)} shared LOD texture(s) created, "
        f"applied to {processed} texture slot(s) across {len(lod_objects)} LOD object(s)"
    )


# ── Billboard LOD (the real FO4 farthest LOD level) ──────────────────────────

def generate_billboard_lod(source_obj, billboard_name: str, tex_size: int = 512) -> tuple:
    """Generate a baked-billboard LOD for *source_obj*.

    Real FO4 assets don't just keep decimating the organic mesh down for
    their farthest LOD level — verified against a real reference asset
    (``BlastedForestBurntTreeUpright01`` in the vanilla/DLC library): its
    last LOD level is 8 verts / 4 tris (two independent perpendicular quads —
    a classic "cross" billboard) using its own dedicated billboard texture,
    not the shared trunk atlas the closer LOD levels use.

    This renders a single front-view (looking down +Y, matching this addon's
    existing "front faces -Y" convention used elsewhere for facing-direction
    checks) orthographic capture of *source_obj* with a transparent
    background, builds that same 8-vert/4-tri cross shape sized to the
    object's bounding box, and applies the render to both quads via an
    alpha-clip material.

    Never modifies *source_obj* itself, and restores the scene's prior active
    camera / render engine / resolution / film_transparent afterward so this
    doesn't leave the user's scene in a different state.

    Returns (new_obj, message).
    """
    import os
    import tempfile
    from mathutils import Vector

    scene = bpy.context.scene

    corners = [source_obj.matrix_world @ Vector(c) for c in source_obj.bound_box]
    min_x = min(c.x for c in corners); max_x = max(c.x for c in corners)
    min_y = min(c.y for c in corners); max_y = max(c.y for c in corners)
    min_z = min(c.z for c in corners); max_z = max(c.z for c in corners)
    width = max(max_x - min_x, max_y - min_y, 1e-4)
    height = max(max_z - min_z, 1e-4)
    center_x = (min_x + max_x) * 0.5
    center_y = (min_y + max_y) * 0.5
    cam_distance = max(width, height) * 2.0 + 1.0

    # Save scene state so this is fully non-destructive to the user's setup.
    _prev_camera = scene.camera
    _prev_engine = scene.render.engine
    _prev_res_x = scene.render.resolution_x
    _prev_res_y = scene.render.resolution_y
    _prev_film_transparent = scene.render.film_transparent
    _prev_filepath = scene.render.filepath

    new_obj = None
    cam_obj = None
    bake_lights = []
    _hidden_prev = {}
    try:
        # ── Isolate the source object for this capture ─────────────────────
        # This billboard is meant to be a picture of ONE plant/object. When
        # Generate LOD0-LOD3 runs on a multi-object selection (e.g. every
        # plant in a cluster at once), every other mesh in the scene was
        # still fully visible during each object's render -- an orthographic
        # camera captures everything inside its view frustum along the whole
        # depth of the scene, not just whatever it's aimed at, so a
        # neighboring plant sitting anywhere in that frustum bled straight
        # into the "wrong" plant's billboard texture. Confirmed by a user
        # report: billboards showing parts of a different plant, sometimes a
        # completely different texture than the plant they're attached to.
        # Hiding every other render-visible object for the duration of this
        # one capture guarantees the render contains only *source_obj*, and
        # everything is restored to its prior visibility in the `finally`
        # block below.
        for _o in scene.objects:
            if _o is source_obj:
                continue
            if _o.hide_render:
                continue
            _hidden_prev[_o] = False
            _o.hide_render = True

        cam_data = bpy.data.cameras.new(f"{billboard_name}_BakeCam")
        cam_data.type = 'ORTHO'
        cam_data.ortho_scale = max(width, height) * 1.05
        cam_obj = bpy.data.objects.new(f"{billboard_name}_BakeCam", cam_data)
        scene.collection.objects.link(cam_obj)
        cam_obj.location = (center_x, min_y - cam_distance, (min_z + max_z) * 0.5)
        # Look down +Y ("front", matching this addon's -Y-facing-front convention).
        cam_obj.rotation_euler = (1.5707963267948966, 0.0, 0.0)
        scene.camera = cam_obj

        # ── Temporary bake lighting ────────────────────────────────────────
        # This capture used to rely entirely on whatever lights already
        # existed in the user's scene. Plenty of real scenes used for asset
        # work have no lights at all (or none pointed at this object from
        # this angle) -- when that happens the render comes back solid
        # black, and since film_transparent only affects the BACKGROUND
        # (the object itself is still fully opaque where it exists), the
        # baked billboard shows up as a flat black card instead of a
        # transparent silhouette of the source mesh. Confirmed from a user
        # screenshot: several fully opaque black rectangles floating around
        # an otherwise correctly-lit viewport. Adding a fixed 3-point rig
        # around the object for the duration of this one render guarantees a
        # correctly-lit capture regardless of what the user's scene has, and
        # it's removed again immediately after in the `finally` block below
        # so nothing about the user's scene is left changed.
        # SUN lights, not AREA: an area light's Watts are total radiant power
        # spread over its physical Size, so scaling `size` to the object's
        # bounding box (needed so the light actually covers it) makes a big
        # object's key light dimmer, not brighter, at the same energy value
        # -- irradiance = power / area. Confirmed as the actual cause of a
        # user report that the billboard was still too dark specifically on
        # a LARGE combined multi-object scene after the first lighting fix
        # (which used AREA lights) -- a small single-plant object looked
        # fine, a whole scene did not, exactly matching this scaling bug.
        # Sun lights measure strength as irradiance (W/m^2) directly and
        # don't fall off with distance or object size, so exposure stays
        # consistent regardless of how big *source_obj* is.
        _light_dist = cam_distance
        _rig = [
            ("Key",  (center_x, min_y - _light_dist, (min_z + max_z) * 0.5 + height * 0.3), 3.0),
            ("Fill", (max_x + _light_dist * 0.5, center_y, (min_z + max_z) * 0.5), 1.5),
            ("Rim",  (center_x, max_y + _light_dist * 0.5, max_z + height * 0.3), 2.0),
        ]
        for _label, _loc, _power in _rig:
            _ld = bpy.data.lights.new(f"{billboard_name}_Bake{_label}", type='SUN')
            _ld.energy = _power
            _ld.angle = 0.2  # slightly soft shadows, not a razor-sharp point-sun look
            _lo = bpy.data.objects.new(f"{billboard_name}_Bake{_label}", _ld)
            scene.collection.objects.link(_lo)
            _lo.location = _loc
            # Sun lights only care about rotation (direction), not location,
            # but keeping a real location makes the rig easy to inspect if
            # something goes wrong mid-bake. Point it from _loc toward the
            # object's center rather than reusing the camera's fixed
            # rotation, so the key/fill/rim actually aim at the subject from
            # each of their distinct positions instead of all three sharing
            # one straight-down-+Y direction.
            _to_center = Vector((center_x, center_y, (min_z + max_z) * 0.5)) - Vector(_loc)
            _lo.rotation_euler = _to_center.to_track_quat('-Z', 'Y').to_euler()
            bake_lights.append(_lo)

        for _engine in ('BLENDER_EEVEE_NEXT', 'BLENDER_EEVEE', 'CYCLES'):
            try:
                scene.render.engine = _engine
                break
            except Exception:
                continue
        scene.render.film_transparent = True
        scene.render.resolution_x = tex_size
        scene.render.resolution_y = tex_size

        out_path = os.path.join(tempfile.gettempdir(), f"{billboard_name}_billboard.png")
        scene.render.filepath = out_path
        scene.render.image_settings.file_format = 'PNG'
        scene.render.image_settings.color_mode = 'RGBA'
        bpy.ops.render.render(write_still=True)

        img = bpy.data.images.load(out_path, check_existing=False)
        img.name = f"{billboard_name}_d"

        # Cross billboard: two independent perpendicular quads (4 verts + 2
        # tris each = 8 verts / 4 tris total) -- matching the verified real
        # asset exactly, rather than a single flat card.
        half_w = width * 0.5
        mesh = bpy.data.meshes.new(billboard_name)
        verts = [
            (-half_w, 0.0, 0.0), (half_w, 0.0, 0.0), (half_w, 0.0, height), (-half_w, 0.0, height),
            (0.0, -half_w, 0.0), (0.0, half_w, 0.0), (0.0, half_w, height), (0.0, -half_w, height),
        ]
        faces = [(0, 1, 2, 3), (4, 5, 6, 7)]
        mesh.from_pydata(verts, [], faces)
        mesh.update()

        uv_layer = mesh.uv_layers.new(name="UVMap")
        quad_uv = [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]
        for poly in mesh.polygons:
            for corner, loop_index in enumerate(poly.loop_indices):
                uv_layer.data[loop_index].uv = quad_uv[corner]

        new_obj = bpy.data.objects.new(billboard_name, mesh)
        scene.collection.objects.link(new_obj)
        new_obj.location = (center_x, center_y, min_z)

        mat = bpy.data.materials.new(f"{billboard_name}_Mat")
        mat.use_nodes = True
        mat.blend_method = 'CLIP'
        try:
            mat.shadow_method = 'CLIP'
        except AttributeError:
            pass  # removed in some Blender versions
        mat.use_backface_culling = False
        nodes = mat.node_tree.nodes
        links = mat.node_tree.links
        bsdf = next((n for n in nodes if n.type == 'BSDF_PRINCIPLED'), None)
        tex_node = nodes.new('ShaderNodeTexImage')
        tex_node.name = "Diffuse"
        tex_node.label = "Diffuse"
        tex_node.image = img
        if bsdf:
            links.new(tex_node.outputs['Color'], bsdf.inputs['Base Color'])
            alpha_input = bsdf.inputs.get('Alpha')
            if alpha_input:
                links.new(tex_node.outputs['Alpha'], alpha_input)
        new_obj.data.materials.append(mat)

        # fo4_mesh_type is a real RNA EnumProperty (bpy.types.Object.
        # fo4_mesh_type = EnumProperty(...)) -- obj["fo4_mesh_type"] = ...
        # (bracket/custom-property assignment) silently creates a SEPARATE,
        # unrelated custom property with the same name and never actually
        # touches the real RNA value the export pipeline reads via
        # getattr(obj, "fo4_mesh_type"). Must use attribute assignment.
        # Inherit the source's real category (e.g. 'VEGETATION') rather than
        # the inert 'LOD' tag nothing downstream checks for, matching the
        # fix in advanced_mesh_helpers.generate_lod_chain.
        try:
            new_obj.fo4_mesh_type = getattr(source_obj, 'fo4_mesh_type', '') or new_obj.fo4_mesh_type
        except Exception:
            pass
        new_obj["fo4_billboard"] = True
        new_obj["PYN_GAME"] = "FO4"

        msg = (
            f"Billboard '{billboard_name}' generated: "
            f"{len(mesh.vertices)} verts / {len(mesh.polygons)*2} tris, "
            f"{tex_size}x{tex_size}px texture."
        )
        return new_obj, msg
    finally:
        if cam_obj is not None:
            bpy.data.objects.remove(cam_obj, do_unlink=True)
        for _lo in bake_lights:
            try:
                _ld = _lo.data
                bpy.data.objects.remove(_lo, do_unlink=True)
                if _ld is not None and _ld.users == 0:
                    bpy.data.lights.remove(_ld)
            except Exception:
                pass
        scene.camera = _prev_camera
        scene.render.engine = _prev_engine
        scene.render.resolution_x = _prev_res_x
        scene.render.resolution_y = _prev_res_y
        scene.render.film_transparent = _prev_film_transparent
        scene.render.filepath = _prev_filepath
        for _o, _prev_hide in _hidden_prev.items():
            try:
                _o.hide_render = _prev_hide
            except Exception:
                pass


# ══════════════════════════════════════════════════════════════════════════════
# Operators
# ══════════════════════════════════════════════════════════════════════════════


# ── Mesh type constants ───────────────────────────────────────────────────────

# Mesh classes that use FO4 procedural wind via vertex groups (no armature).
# NOTE: Trees and large shrubs are VEGETATION class but still need collision in
# their NIFs — a tree you can walk through is not a tree.  Ground-cover (grass,
# thin mushrooms) has no NIF collision; that is controlled by fo4_collision_type.
_VEGETATION_CLASSES = frozenset({'VEGETATION', 'FLORA'})

# Mesh classes that are armature-skinned.  LOD decimation of skinned meshes
# should be handled inside PyNifly (which can re-bind LOD vertices to bones).
# Our Decimate-based approach strips the skin bind, so we warn and skip NIF
# export for these types.
_SKINNED_CLASSES = frozenset({'CHARACTER', 'CREATURE', 'SKINNED', 'ARMOR'})

# fo4_collision_type values that mean "no physics collision in the NIF".
# GRASS and MUSHROOM are thin ground-cover that the engine skips for physics.
# The collision volume for these is authored inside the CK record, not the NIF.
# Trees and large custom vegetation set fo4_collision_type to 'VEGETATION' or
# leave it as 'DEFAULT' and still need a UCX_ hull in their LOD NIF.
_NO_COLLISION_MESH_TYPES = frozenset({'GRASS', 'MUSHROOM', 'NONE'})


class FO4_OT_GenerateLODs(Operator):
    """
    Auto-generate FO4 LOD meshes from the active object.

    Creates LOD1, LOD2, and LOD3 copies using Blender's Decimate modifier
    at FO4-correct polygon ratios, then exports each as a separate NIF to
    your mod staging folder.

    Mesh-type-aware behaviour
    -------------------------
    * STATIC / LOD / ARCHITECTURE / WEAPON / FURNITURE
        Standard decimation + optional UCX_ convex-hull collision from LOD3.
    * VEGETATION / FLORA
        Decimation only.  FO4 vegetation uses Wind vertex-group weights for
        procedural in-engine wind — no armature is needed or exported.  Physics
        collision for foliage is authored in the CK ESP record, not in the NIF,
        so the "collision from LOD3" step is skipped automatically.
    * CHARACTER / CREATURE / SKINNED / ARMOR
        Decimation is performed for preview, but NIF export is skipped with a
        warning.  Skinned-mesh LODs must be re-bound to the skeleton and are
        best generated inside PyNifly (BadDogSkyrim) directly.

    LOD objects are placed in a 'FO4_LODs' collection for easy management.
    """
    bl_idname  = "fo4.generate_lods"
    bl_label   = "Generate FO4 LOD Meshes"
    bl_description = (
        "Auto-generate LOD1/2/3 meshes from the active object using "
        "FO4-correct polygon ratios, then export each as a NIF."
    )
    bl_options = {'REGISTER', 'UNDO'}

    mod_folder: StringProperty(
        name="Mod Output Folder", default="", subtype='DIR_PATH',
    )
    mesh_subpath: StringProperty(
        name="Mesh Sub-path",
        description="Path under [Mod Output Folder]/Meshes/ where NIFs go (MO2 mod folders have no Data\\ wrapper)",
        default="",
    )
    generate_lod1: BoolProperty(name="LOD1 (30%)", default=True)
    generate_lod2: BoolProperty(name="LOD2 (12%)", default=True)
    generate_lod3: BoolProperty(name="LOD3 (8%)",  default=True)
    export_nifs: BoolProperty(
        name="Export NIFs",
        description="Export each LOD as a separate NIF to mod folder",
        default=True,
    )
    lod1_ratio: FloatProperty(name="LOD1 Ratio", default=0.30, min=0.05, max=0.95)
    lod2_ratio: FloatProperty(name="LOD2 Ratio", default=0.12, min=0.01, max=0.50)
    lod3_ratio: FloatProperty(name="LOD3 Ratio", default=0.08, min=0.005, max=0.20)
    generate_billboard: BoolProperty(
        name="Billboard (Farthest)",
        description=(
            "Also generate the farthest LOD level as a baked-texture "
            "billboard (8-vert/4-tri cross shape) instead of further "
            "decimation -- matching real FO4 assets (verified against "
            "BlastedForestBurntTreeUpright01 and the exported reference "
            "folder: e.g. Meshes/Landscape/Trees/TreeMapleForest01_LOD_FLAT.nif, "
            "sitting next to the source mesh, NOT under Meshes/LOD/)"
        ),
        default=True,
    )
    billboard_tex_size: EnumProperty(
        name="Billboard Texture",
        items=[
            ('256',  "256×256",   "Smallest — very distant/minor objects"),
            ('512',  "512×512",   "Standard billboard resolution"),
            ('1024', "1024×1024", "Larger — hero/prominent objects"),
        ],
        default='512',
    )
    collision_from_lod3: BoolProperty(
        name="Auto-Collision from LOD3",
        description=(
            "Use the LOD3 mesh (~4% polys) as the source for the UCX_ convex "
            "collision hull instead of decimating the original again. "
            "LOD3 is already the right density for physics — no extra work needed."
        ),
        default=True,
    )
    collision_method: EnumProperty(
        name="Collision Method",
        description=(
            "How to build the collision shape when collision generation is on"
        ),
        items=[
            ('CONVEX_LOD3', "Convex Hull (from LOD3)",
             "Cheap at runtime, but a convex hull can never have a dent in "
             "it -- fine for simple/blocky props, but it seals shut any gap, "
             "opening, or concave curve in the source shape."),
            ('EXACT_MESH', "Exact Mesh (follows shape exactly)",
             "Uses the full-detail source mesh itself as the collision "
             "shape -- no hull, so it hugs every concave curve and gap "
             "exactly. Heavier at runtime than a convex hull, so best for "
             "static decorative meshes (foliage, coral, rock clusters) "
             "rather than anything simple/box-like."),
        ],
        default='CONVEX_LOD3',
    )

    # Hidden property: detected FO4 class of the source mesh.
    # Set in invoke() so draw() and execute() can use it without re-detecting.
    # No leading underscore — Blender's RNA system requires clean identifier names.
    detected_source_class: StringProperty(
        name="Detected Source Class",
        default="STATIC",
        options={'HIDDEN'},
    )

    @staticmethod
    def _detect_source_class(obj) -> str:
        """Detect the FO4 object class for *obj*, using export_helpers when available."""
        try:
            from . import export_helpers
            return export_helpers.ExportHelpers.detect_fo4_object_class(obj)
        except Exception:
            pass
        # Fallback: honour explicit property, then guess from vertex groups / name
        forced = obj.get("fo4_object_type", "")
        if forced:
            return forced.upper()
        if obj.vertex_groups:
            wind_names = {'Wind', 'wind', 'WIND', 'WindWeight', 'windweight',
                          'WINDWEIGHT', 'WindStiff', 'windstiff'}
            if all(vg.name in wind_names for vg in obj.vertex_groups):
                return 'VEGETATION'
        if obj.parent and obj.parent.type == 'ARMATURE':
            bones = [b.name for b in obj.parent.data.bones]
            return 'CHARACTER' if any(b.startswith("NPC ") for b in bones) else 'CREATURE'
        return 'STATIC'

    def invoke(self, context, event):
        obj = context.active_object
        if obj and obj.type == 'MESH':
            src_class = FO4_OT_GenerateLODs._detect_source_class(obj)
            self.detected_source_class = src_class

            n_tris = sum(len(p.loop_indices) - 2 for p in obj.data.polygons)
            # Auto-adjust ratios so none exceed FO4 max per level
            if n_tris > 0:
                self.lod1_ratio = min(0.30, _LOD_MAX_TRIS["LOD1"] / n_tris)
                self.lod2_ratio = min(0.12, _LOD_MAX_TRIS["LOD2"] / n_tris)
                self.lod3_ratio = min(0.08, _LOD_MAX_TRIS["LOD3"] / n_tris)

            # Auto-disable collision only for ground-cover types (GRASS, MUSHROOM).
            # Trees and large custom vegetation (VEGETATION/FLORA) still need a
            # UCX_ convex hull in the NIF — check fo4_collision_type, not just class.
            # fo4_collision_type is a real RNA EnumProperty set via attribute
            # assignment -- obj.get() only sees custom ID properties and
            # always silently returned "DEFAULT" here, so this check never
            # actually fired for GRASS/MUSHROOM-tagged objects.
            ctype = getattr(obj, "fo4_collision_type", "DEFAULT")
            if ctype in _NO_COLLISION_MESH_TYPES:
                self.collision_from_lod3 = False

            # Default to exact-mesh collision for organic/vegetation classes
            # -- a convex hull can't follow the gaps and concave curves a
            # cluster of stalks/branches/coral actually has, so decomposing
            # it into a hull (however well) still balloons out to fill that
            # negative space. Confirmed from a user screenshot: even a
            # well-decomposed multi-piece convex hull draped loosely across
            # a spread-out fungus cluster instead of hugging it. Everything
            # else defaults to the cheaper convex hull, which is the right
            # call for simple/blocky props.
            self.collision_method = (
                'EXACT_MESH' if src_class in _VEGETATION_CLASSES else 'CONVEX_LOD3'
            )

        return context.window_manager.invoke_props_dialog(self, width=460)

    def draw(self, context):
        layout = self.layout
        obj    = context.active_object
        src    = self.detected_source_class

        # ── Source info ───────────────────────────────────────────────────────
        if obj and obj.type == 'MESH':
            n_tris = sum(len(p.loop_indices) - 2 for p in obj.data.polygons)
            row = layout.row(align=True)
            row.label(text=f"Source: {obj.name}  (~{n_tris:,} triangles)")
            icon = (
                'OUTLINER_OB_FORCE_FIELD' if src in _VEGETATION_CLASSES else
                'ARMATURE_DATA'           if src in _SKINNED_CLASSES      else
                'MESH_DATA'
            )
            row.label(text=f"Type: {src}", icon=icon)

        # ── Skinned mesh warning ──────────────────────────────────────────────
        if src in _SKINNED_CLASSES:
            box = layout.box()
            box.alert = True
            box.label(
                text=f"{src}: LOD decimation preview only — NIF export skipped.",
                icon='ERROR',
            )
            box.label(text="Use PyNifly to generate skinned-mesh LODs with bone re-binding.")

        layout.separator()

        # ── LOD ratios ────────────────────────────────────────────────────────
        row = layout.row()
        row.prop(self, "generate_lod1")
        row.prop(self, "lod1_ratio", text="Ratio")
        row = layout.row()
        row.prop(self, "generate_lod2")
        row.prop(self, "lod2_ratio", text="Ratio")
        row = layout.row()
        row.prop(self, "generate_lod3")
        row.prop(self, "lod3_ratio", text="Ratio")
        row = layout.row()
        row.enabled = src not in _SKINNED_CLASSES
        row.prop(self, "generate_billboard")
        row.prop(self, "billboard_tex_size", text="")
        if src in _SKINNED_CLASSES and self.generate_billboard:
            layout.label(
                text=f"{src}: billboard skipped — armature-skinned meshes don't get one.",
                icon='INFO',
            )
        layout.separator()

        # ── Collision ─────────────────────────────────────────────────────────
        # Show collision UI for all mesh types.
        # For vegetation, show an info note explaining ground-cover vs trees.
        box = layout.box()
        if src in _VEGETATION_CLASSES:
            box.label(
                text=f"{src}: trees/large shrubs need collision; ground-cover (GRASS) does not.",
                icon='INFO',
            )
        box.prop(self, "collision_from_lod3")
        if self.collision_from_lod3:
            box.prop(self, "collision_method")
            if self.collision_method == 'EXACT_MESH':
                box.label(
                    text="Exact-mesh collision — follows the true shape, no hull.",
                    icon='CHECKMARK',
                )
            elif src in _VEGETATION_CLASSES:
                box.label(
                    text="UCX_ hull will be built — disable if this is thin ground-cover.",
                    icon='CHECKMARK',
                )
            else:
                box.label(
                    text="UCX_ collision built from LOD3 — no extra decimation step.",
                    icon='CHECKMARK',
                )

        layout.separator()

        # ── Texture / material note ───────────────────────────────────────────
        if obj and obj.type == 'MESH' and obj.material_slots:
            mat = obj.material_slots[0].material if obj.material_slots else None
            if mat:
                box = layout.box()
                box.label(text=f"Material: {mat.name}", icon='MATERIAL')
                box.label(text="LOD NIFs get their own downscaled, shared LOD texture(s).")

        # ── Export options ────────────────────────────────────────────────────
        layout.prop(self, "export_nifs")
        if self.export_nifs and src not in _SKINNED_CLASSES:
            layout.prop(self, "mod_folder")
            layout.prop(self, "mesh_subpath")

    def execute(self, context):
        # Process every selected mesh object, not just the active one — a
        # multi-mesh NIF (e.g. a tree trunk plus separate vine-cluster
        # pieces, all imported as their own Blender objects) needs LOD and
        # collision generated for EVERY piece. This used to only ever look
        # at context.active_object, silently skipping every other selected
        # mesh in the same multi-mesh selection.
        targets = [o for o in context.selected_objects if o.type == 'MESH']
        if not targets:
            active = context.active_object
            if active and active.type == 'MESH':
                targets = [active]
        if not targets:
            self.report({'ERROR'}, "Select a mesh object.")
            return {'CANCELLED'}

        # ── Normalize a user-typed "Mesh Sub-path" that already starts with
        # "LOD" ──────────────────────────────────────────────────────────────
        # The LOD1/2/3 export path below already inserts its own "Meshes/LOD/"
        # segment (see the NIF export block's own comment). A user who types
        # e.g. "LOD\Landscape\Trees" into the Mesh Sub-path field -- a very
        # natural mistake, since that IS the real folder LOD files end up in
        # -- doubles it into "Meshes/LOD/LOD/Landscape/Trees/..."; confirmed
        # directly from a real user's mod folder (a genuine, nested
        # Meshes\LOD\LOD\Landscape\Trees\ folder that only "LOD"-prefixed
        # sub-paths can produce). It also pushes the billboard -- which is
        # deliberately NOT under Meshes/LOD/ per the real FO4 convention
        # (see generate_billboard_lod's own docstring) -- to the wrong
        # "Meshes/LOD/Landscape/Trees/..." location. Strip one leading "LOD"
        # path segment so both destinations land where the rest of this
        # operator's own logic already expects them.
        _clean_subpath = self.mesh_subpath.strip("/\\")
        _sub_parts = [p for p in re.split(r'[\\/]+', _clean_subpath) if p]
        if _sub_parts and _sub_parts[0].upper() == "LOD":
            _clean_subpath = "/".join(_sub_parts[1:])
            self.report(
                {'INFO'},
                f"Mesh Sub-path started with 'LOD' -- stripped it since LOD "
                f"NIFs already go under Meshes/LOD/ automatically (now using "
                f"'{_clean_subpath or '(none)'}')."
            )

        # ── Get/create LOD collection ─────────────────────────────────────────
        lod_col = bpy.data.collections.get("FO4_LODs")
        if not lod_col:
            lod_col = bpy.data.collections.new("FO4_LODs")
            bpy.context.scene.collection.children.link(lod_col)

        lods_to_gen = []
        if self.generate_lod1: lods_to_gen.append(("LOD1", self.lod1_ratio))
        if self.generate_lod2: lods_to_gen.append(("LOD2", self.lod2_ratio))
        if self.generate_lod3: lods_to_gen.append(("LOD3", self.lod3_ratio))

        steps = []
        # Every LOD object across every target, kept separate for the
        # textureless (skinned) targets since those are decimation previews
        # only — no point downscaling/exporting textures nobody will use.
        all_lod_objects = []
        processed_src_classes = []
        total_lod_count = 0

        for obj in targets:
            # ── Detect source mesh class ──────────────────────────────────────
            # Use the dialog-detected value from invoke() only for the object
            # that was actually active when the dialog opened (that's the only
            # one invoke() profiled) — every other target in a multi-select
            # gets freshly auto-detected so a batch of mixed types (e.g. a
            # vegetation piece and a static prop selected together) is each
            # classified correctly instead of all inheriting one object's class.
            src_class = (
                self.detected_source_class
                if obj is context.active_object and self.detected_source_class not in ('', 'AUTO')
                else FO4_OT_GenerateLODs._detect_source_class(obj)
            )
            processed_src_classes.append(src_class)
            is_skinned = src_class in _SKINNED_CLASSES

            if is_skinned:
                self.report({'WARNING'},
                    f"{obj.name} is {src_class} (armature-skinned). "
                    "LOD decimation preview created but NIF export skipped. "
                    "Use PyNifly to generate skinned-mesh LODs with bone re-binding."
                )

            lod_objects = []
            for lod_key, ratio in lods_to_gen:
                lod_name = f"{obj.name}_{lod_key}"
                # Remove existing LOD with same name
                existing = bpy.data.objects.get(lod_name)
                if existing:
                    bpy.data.objects.remove(existing, do_unlink=True)

                try:
                    lod_obj, msg = generate_lod_mesh(obj, ratio, lod_name)
                    # Move to LOD collection
                    for c in list(lod_obj.users_collection):
                        c.objects.unlink(lod_obj)
                    lod_col.objects.link(lod_obj)
                    # ── Tag with metadata ────────────────────────────────────────
                    # fo4_object_type is the key that export_helpers.detect_fo4_object_class()
                    # honours first.  Setting it here means the LOD copies export with the
                    # correct shader flags (e.g. Two_Sided for VEGETATION) even if the
                    # material or vertex-group heuristics on the copy are ambiguous.
                    lod_obj["fo4_lod_level"]    = lod_key
                    lod_obj["fo4_lod_source"]   = obj.name
                    lod_obj["fo4_object_type"]  = src_class   # ← propagate type to LOD
                    lod_objects.append(lod_obj)
                    steps.append(msg)
                except Exception as e:
                    self.report({'WARNING'}, f"LOD generation failed for {obj.name} {lod_key}: {e}")

            # ── Collision from LOD3 ───────────────────────────────────────────────
            # Rules:
            #   GRASS / MUSHROOM (fo4_collision_type) – thin ground-cover; no NIF
            #       collision.  Footprint is authored in the CK ESP record.
            #   CHARACTER / CREATURE / SKINNED / ARMOR – collision is part of the
            #       skeleton/ragdoll rig; do not create a static UCX_ hull.
            #   VEGETATION / FLORA (trees, large shrubs, custom plants) – DO need a
            #       UCX_ convex hull in the LOD NIF; a tree without collision is
            #       just a decoration you walk straight through.
            #   Everything else (STATIC, LOD, ARCHITECTURE, WEAPON…) – normal hull.
            # fo4_collision_type is a real RNA EnumProperty set via attribute
            # assignment -- obj.get() only sees custom ID properties and always
            # silently returned "DEFAULT" here, so GRASS/MUSHROOM objects never
            # actually got their collision skipped as intended.
            coll_type = getattr(obj, "fo4_collision_type", "DEFAULT")
            is_ground_cover = coll_type in _NO_COLLISION_MESH_TYPES

            # Exact-mesh collision is built straight from the full-detail
            # source object, not from LOD3, so it doesn't need LOD3 to have
            # been generated -- only the convex-hull-from-LOD3 method does.
            collision_possible = (
                not is_ground_cover
                and not is_skinned
                and self.collision_from_lod3
                and (self.collision_method == 'EXACT_MESH' or self.generate_lod3)
            )

            if is_ground_cover:
                steps.append(
                    f"✓ {obj.name} [{src_class}] (collision type: {coll_type}): collision skipped — "
                    "ground-cover uses no NIF physics collision"
                )
            elif is_skinned:
                steps.append(
                    f"✓ {obj.name} [{src_class}]: collision skipped — "
                    "collision is part of the armature/ragdoll rig"
                )
            elif collision_possible and self.collision_method == 'EXACT_MESH':
                try:
                    from . import mesh_helpers as _mesh_helpers
                    coll_type = getattr(obj, "fo4_collision_type", "DEFAULT")
                    exact_coll = _mesh_helpers.MeshHelpers.add_custom_collision(
                        obj,
                        collision_type=(
                            coll_type if coll_type not in ("DEFAULT", "") else 'BUILDING'
                        ),
                    )
                    if exact_coll:
                        n_tris = len(exact_coll.data.polygons)
                        steps.append(
                            f"✓ UCX_{obj.name}: exact-mesh collision "
                            f"({n_tris} tris) — follows the true shape, no hull"
                        )
                    else:
                        self.report({'WARNING'}, f"Exact-mesh collision failed for {obj.name}")
                except Exception as e:
                    self.report({'WARNING'}, f"Exact-mesh collision failed for {obj.name}: {e}")
            elif collision_possible:
                lod3_obj = next(
                    (o for o in lod_objects if o.get("fo4_lod_level") == "LOD3"), None
                )
                if lod3_obj:
                    try:
                        ucx_name = f"UCX_{obj.name}"
                        # Remove existing UCX if present
                        existing_ucx = bpy.data.objects.get(ucx_name)
                        if existing_ucx:
                            bpy.data.objects.remove(existing_ucx, do_unlink=True)

                        # Duplicate LOD3 as the collision source
                        import bmesh as _bm
                        ucx_mesh = lod3_obj.data.copy()
                        ucx_obj  = lod3_obj.copy()
                        ucx_obj.data = ucx_mesh
                        ucx_obj.name = ucx_name
                        ucx_mesh.name = ucx_name
                        bpy.context.collection.objects.link(ucx_obj)

                        # Build a clean convex hull from LOD3 vertices
                        bm = _bm.new()
                        bm.from_mesh(ucx_mesh)
                        result = _bm.ops.convex_hull(bm, input=bm.verts)
                        # Keep only outer hull geometry
                        interior = result.get("geom_interior", [])
                        unused   = result.get("geom_unused", [])
                        _bm.ops.delete(
                            bm,
                            geom=[g for g in interior + unused
                                  if isinstance(g, _bm.types.BMVert)],
                            context='VERTS',
                        )
                        bm.to_mesh(ucx_mesh)
                        ucx_mesh.update()
                        bm.free()

                        # Tag as FO4 collision
                        ucx_obj["fo4_collision"]        = True
                        ucx_obj["fo4_collision_source"] = "LOD3"
                        ucx_obj["fo4_lod_source"]       = obj.name
                        ucx_obj.display_type            = 'WIRE'
                        ucx_obj.hide_render             = True
                        ucx_obj.parent                  = obj

                        # Rigid body for Blender physics preview
                        # Restore whatever was active before this block afterward
                        # -- leaving the collision mesh as the active object leaks
                        # into any subsequent bpy.ops call in the same context that
                        # reads context.active_object (e.g. a caller that invokes
                        # this whole operator a second time via EXEC_DEFAULT would
                        # silently operate on the collision mesh instead of the
                        # real source object).
                        _prev_active_for_rb = context.view_layer.objects.active
                        try:
                            context.view_layer.objects.active = ucx_obj
                            ucx_obj.select_set(True)
                            bpy.ops.rigidbody.object_add()
                            ucx_obj.rigid_body.type            = 'PASSIVE'
                            ucx_obj.rigid_body.collision_shape = 'CONVEX_HULL'
                        except Exception:
                            pass
                        finally:
                            context.view_layer.objects.active = _prev_active_for_rb

                        n_verts = len(ucx_mesh.vertices)
                        steps.append(
                            f"✓ UCX_{obj.name}: convex hull from LOD3 "
                            f"({n_verts} vertices) — no extra decimation needed"
                        )
                    except Exception as e:
                        self.report({'WARNING'}, f"Collision from LOD3 failed for {obj.name}: {e}")
                else:
                    self.report({'WARNING'},
                        f"{obj.name}: LOD3 not generated — enable 'LOD3 (8%)' to use it as collision source.")

            # ── Export NIFs ───────────────────────────────────────────────────────
            # Skinned meshes are excluded: the Decimate modifier strips the skin
            # bind and the resulting NIF would be broken.  Use PyNifly for skinned LODs.
            if self.export_nifs and self.mod_folder and lod_objects and not is_skinned:
                try:
                    from . import export_helpers
                    for lod_obj in lod_objects:
                        lod_key  = lod_obj.get("fo4_lod_level", "LOD")
                        # Real FO4 object-LOD naming, confirmed against a
                        # game-exported reference folder (F:\FO4 WORKING
                        # FLODER): multi-level LOD files use "_LOD_<n>" with
                        # an underscore before a ZERO-BASED index --
                        # "_LOD_0.nif" (nearest swap), "_LOD_1.nif",
                        # "_LOD_2.nif" (e.g. TreeMapleForest01_LOD_0/1/2.nif)
                        # -- never the "_lod1"/"_lod2"/"_lod3" (lowercase, no
                        # underscore before the digit, one-based) this addon
                        # used to generate, which doesn't match anything CK
                        # or the game looks for. Our own LOD1/LOD2/LOD3
                        # naming is one-based, so subtract 1 for the index.
                        _lod_index = int(lod_key[-1]) - 1 if lod_key and lod_key[-1].isdigit() else 0
                        suffix   = f"_LOD_{_lod_index}"   # _LOD_0, _LOD_1, _LOD_2
                        nif_name = f"{obj.name}{suffix}.nif"
                        sub      = _clean_subpath
                        # NOTE: no "Data" segment here. self.mod_folder is the
                        # user's MO2 mod folder (e.g. ".../mods/MyMod"), which
                        # contains Meshes/Materials/Textures DIRECTLY -- MO2
                        # mod folders never have a Data\ wrapper (that only
                        # exists once MO2 virtually merges mods into the
                        # game's own Data folder). Inserting "Data" here wrote
                        # every LOD NIF to ".../MyMod/Data/Meshes/..." instead
                        # of ".../MyMod/Meshes/...", where nothing in MO2 or
                        # the game would ever find it -- confirmed as a real
                        # bug from a user report.
                        # LOD meshes go under their own Meshes\LOD\... folder,
                        # mirroring the Textures\LOD\... / Materials\LOD\...
                        # convention used elsewhere for this same asset
                        # (confirmed against the user's real mod folder
                        # layout) -- not mixed in next to the full-res mesh.
                        nif_path = os.path.normpath(os.path.join(
                            self.mod_folder, "Meshes", "LOD",
                            sub, nif_name
                        ) if sub else os.path.join(
                            self.mod_folder, "Meshes", "LOD", nif_name
                        ))
                        os.makedirs(os.path.dirname(nif_path), exist_ok=True)

                        context.view_layer.objects.active = lod_obj
                        bpy.ops.object.select_all(action='DESELECT')
                        lod_obj.select_set(True)

                        result = export_helpers.ExportHelpers.export_mesh_to_nif(
                            lod_obj, nif_path
                        )
                        ok  = result[0] if isinstance(result, tuple) else \
                              result in ({'FINISHED'}, 'FINISHED')
                        msg = result[1] if isinstance(result, tuple) else str(result)
                        if ok:
                            steps.append(f"Exported [{src_class}]: {os.path.basename(nif_path)}")
                        else:
                            steps.append(f"⚠ Export failed for {lod_obj.name}: {msg}")
                except Exception as e:
                    self.report({'WARNING'}, f"NIF export error for {obj.name}: {e}")

            # ── Billboard (farthest LOD level) ──────────────────────────────────
            # Real FO4 assets don't keep decimating the organic mesh all the way
            # out -- the farthest level is a baked-texture billboard (see
            # generate_billboard_lod's own docstring). Kept OUT of lod_objects /
            # all_lod_objects: it has its own dedicated baked texture, not one
            # shared with LOD1/2/3 via create_lod_textures's downscale pass.
            if self.generate_billboard and not is_skinned:
                try:
                    billboard_name = f"{obj.name}_LOD_FLAT"
                    existing_bb = bpy.data.objects.get(billboard_name)
                    if existing_bb:
                        bpy.data.objects.remove(existing_bb, do_unlink=True)

                    bb_obj, bb_msg = generate_billboard_lod(
                        obj, billboard_name, tex_size=int(self.billboard_tex_size)
                    )
                    for c in list(bb_obj.users_collection):
                        c.objects.unlink(bb_obj)
                    lod_col.objects.link(bb_obj)
                    bb_obj["fo4_lod_level"]   = "BILLBOARD"
                    bb_obj["fo4_lod_source"]  = obj.name
                    bb_obj["fo4_object_type"] = src_class
                    steps.append(bb_msg)

                    if self.export_nifs and self.mod_folder:
                        from . import export_helpers as _eh_bb
                        sub = _clean_subpath
                        # Real convention (verified against the exported
                        # reference folder, e.g.
                        # Meshes/Landscape/Trees/TreeMapleForest01_LOD_FLAT.nif):
                        # the billboard NIF sits in the SAME folder as the
                        # LOD0 source mesh -- NOT under Meshes/LOD/ like
                        # LOD1/2/3 above.
                        bb_nif_path = os.path.normpath(os.path.join(
                            self.mod_folder, "Meshes", sub, f"{billboard_name}.nif"
                        ) if sub else os.path.join(
                            self.mod_folder, "Meshes", f"{billboard_name}.nif"
                        ))
                        os.makedirs(os.path.dirname(bb_nif_path), exist_ok=True)

                        context.view_layer.objects.active = bb_obj
                        bpy.ops.object.select_all(action='DESELECT')
                        bb_obj.select_set(True)

                        bb_result = _eh_bb.ExportHelpers.export_mesh_to_nif(bb_obj, bb_nif_path)
                        bb_ok  = bb_result[0] if isinstance(bb_result, tuple) else \
                                 bb_result in ({'FINISHED'}, 'FINISHED')
                        bb_export_msg = bb_result[1] if isinstance(bb_result, tuple) else str(bb_result)
                        if bb_ok:
                            steps.append(f"Exported billboard: {os.path.basename(bb_nif_path)}")
                        else:
                            steps.append(f"⚠ Billboard export failed for {obj.name}: {bb_export_msg}")
                except Exception as e:
                    self.report({'WARNING'}, f"Billboard generation failed for {obj.name}: {e}")

            total_lod_count += len(lod_objects)
            if lod_objects and not is_skinned:
                all_lod_objects.extend(lod_objects)

        # ── Downscale/share textures across every target's LOD objects ────────
        # Real assets give their real-mesh LOD levels a dedicated, much
        # smaller shared texture instead of the full-resolution hero one (see
        # create_lod_textures's own docstring for the reference-asset
        # evidence). One shared pass over every target's LOD objects together
        # (not one pass per target) so pieces from the same NIF that
        # reference the same source texture (e.g. a trunk and its vines both
        # using the same bark diffuse) end up sharing one LOD atlas instead
        # of each target separately downscaling its own copy.
        if all_lod_objects:
            _ok, tex_msg = create_lod_textures(all_lod_objects, scale_factor=0.25)
            steps.append(tex_msg)

        # ── Texture / material info ───────────────────────────────────────────
        # Report which textures are confirmed on the LOD objects (now the
        # downscaled LOD-specific ones from create_lod_textures() above, not
        # the source's full-resolution originals).
        for lod_obj in all_lod_objects:
            mat = (lod_obj.material_slots[0].material
                   if lod_obj.material_slots else None)
            if mat and mat.use_nodes:
                tex_nodes = [
                    n for n in mat.node_tree.nodes
                    if n.type == 'TEX_IMAGE' and n.image
                ]
                if tex_nodes:
                    tex_names = ", ".join(n.image.name for n in tex_nodes[:3])
                    steps.append(
                        f"{lod_obj.name}: {len(tex_nodes)} texture(s) — {tex_names}"
                        + (" …" if len(tex_nodes) > 3 else "")
                    )
                else:
                    steps.append(
                        f"{lod_obj.name}: no image texture nodes on '{mat.name}' — "
                        "assign textures before export"
                    )
            elif mat:
                steps.append(f"{lod_obj.name}: material '{mat.name}' has no nodes — assign textures")

        for s in steps:
            self.report({'INFO'}, s)
        # Report the true aggregate across every target processed this run --
        # lod_objects/src_class are loop-local and previously left holding
        # only the LAST target's values here, so a multi-object batch always
        # under-reported both the LOD count and (misleadingly) a single
        # source class even when the selection mixed several asset types.
        unique_classes = ", ".join(dict.fromkeys(processed_src_classes))
        self.report({'INFO'},
            f"Generated {total_lod_count} LOD mesh(es) across {len(targets)} source "
            f"object(s) [{unique_classes}] in 'FO4_LODs' collection.")
        return {'FINISHED'}




class FO4_OT_SetupNormalBake(Operator):
    """
    Set up the scene for high-to-low poly normal map baking.

    Select your high-poly mesh and low-poly mesh, then run this operator.
    It configures Cycles bake settings and creates the target image.
    After setup, go to Render Properties → Bake → click Bake.
    """
    bl_idname  = "fo4.setup_normal_bake"
    bl_label   = "Setup Normal Map Bake (High → Low)"
    bl_description = (
        "Configure the scene for baking a normal map from a high-poly to "
        "the active low-poly mesh. Select high-poly first, Shift-select low-poly."
    )
    bl_options = {'REGISTER', 'UNDO'}

    tex_size: EnumProperty(
        name="Texture Resolution",
        items=[
            ('512',  "512×512",   "Low — LOD meshes"),
            ('1024', "1024×1024", "Medium — small props"),
            ('2048', "2048×2048", "High — standard FO4 quality"),
            ('4096', "4096×4096", "Ultra — hero props"),
        ],
        default='2048',
    )
    ray_distance: FloatProperty(
        name="Ray Distance (BU)",
        description="Distance the bake ray casts from the low-poly surface.",
        default=0.05, min=0.001, max=1.0,
    )

    def execute(self, context):
        selected = [o for o in context.selected_objects if o.type == 'MESH']
        active   = context.active_object
        if len(selected) < 2 or not active or active.type != 'MESH':
            self.report({'ERROR'},
                "Select high-poly first, then Shift-select low-poly (active).")
            return {'CANCELLED'}
        high_obj = next((o for o in selected if o != active), None)
        if not high_obj:
            self.report({'ERROR'}, "Could not identify high-poly object.")
            return {'CANCELLED'}
        try:
            _, msg = prepare_normal_bake(
                active, high_obj,
                tex_size=int(self.tex_size),
                ray_dist=self.ray_distance,
            )
            self.report({'INFO'}, msg)
            self.report({'INFO'},
                "Go to Render Properties → Bake → Bake Type: Normal → Bake")
        except Exception as e:
            self.report({'ERROR'}, f"Bake setup failed: {e}")
            return {'CANCELLED'}
        return {'FINISHED'}


class FO4_OT_SetupAOBake(Operator):
    """Set up AO bake on the active mesh."""
    bl_idname  = "fo4.setup_ao_bake"
    bl_label   = "Setup AO Bake"
    bl_description = "Configure the scene for ambient occlusion baking on the active mesh."
    bl_options = {'REGISTER', 'UNDO'}

    tex_size: EnumProperty(
        name="Texture Resolution",
        items=[
            ('512',  "512×512",   ""),
            ('1024', "1024×1024", ""),
            ('2048', "2048×2048", "Standard"),
            ('4096', "4096×4096", "Ultra"),
        ],
        default='2048',
    )

    def execute(self, context):
        obj = context.active_object
        if not obj or obj.type != 'MESH':
            self.report({'ERROR'}, "Select a mesh object.")
            return {'CANCELLED'}
        try:
            _, msg = prepare_ao_bake(obj, int(self.tex_size))
            self.report({'INFO'}, msg)
        except Exception as e:
            self.report({'ERROR'}, f"AO bake setup failed: {e}")
            return {'CANCELLED'}
        return {'FINISHED'}


# ── Registration ───────────────────────────────────────────────────────────────

_CLASSES = [
    FO4_OT_GenerateLODs,
    FO4_OT_SetupNormalBake,
    FO4_OT_SetupAOBake,
]


def register():
    if bpy is None:
        return
    for cls in _CLASSES:
        try:
            bpy.utils.register_class(cls)
        except Exception as e:
            print(f"[LOD Gen] Could not register {cls.__name__}: {e}")
    print("[LOD Gen] FO4 LOD generator + texture baker registered.")


def unregister():
    if bpy is None:
        return
    for cls in reversed(_CLASSES):
        try:
            bpy.utils.unregister_class(cls)
        except Exception:
            pass
